///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Drawing;
using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace Sage50.Repository
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    /// The class representing the CommonObjectsRes element repository.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", "8.0")]
    [RepositoryFolder("ceedd480-7940-4a95-93ce-57f0f33908a7")]
    public partial class CommonObjectsRes : RepoGenBaseFolder
    {
        static CommonObjectsRes instance = new CommonObjectsRes();
        CommonObjectsResFolders.SaveTheFileAsAppFolder _savethefileas;
        CommonObjectsResFolders.DialogJournalSearchAppFolder _dialogjournalsearch;
        CommonObjectsResFolders.SelectAccountAppFolder _selectaccount;
        CommonObjectsResFolders.PrintToFileAppFolder _printtofile;
        CommonObjectsResFolders.ProjAllocationAppFolder _projallocation;
        CommonObjectsResFolders.DotNetJournalSearchAppFolder _dotnetjournalsearch;

        /// <summary>
        /// Gets the singleton class instance representing the CommonObjectsRes element repository.
        /// </summary>
        [RepositoryFolder("ceedd480-7940-4a95-93ce-57f0f33908a7")]
        public static CommonObjectsRes Instance
        {
            get { return instance; }
        }

        /// <summary>
        /// Repository class constructor.
        /// </summary>
        public CommonObjectsRes() 
            : base("CommonObjectsRes", "/", null, 0, false, "ceedd480-7940-4a95-93ce-57f0f33908a7", ".\\RepositoryImages\\CommonObjectsResceedd480.rximgres")
        {
            _savethefileas = new CommonObjectsResFolders.SaveTheFileAsAppFolder(this);
            _dialogjournalsearch = new CommonObjectsResFolders.DialogJournalSearchAppFolder(this);
            _selectaccount = new CommonObjectsResFolders.SelectAccountAppFolder(this);
            _printtofile = new CommonObjectsResFolders.PrintToFileAppFolder(this);
            _projallocation = new CommonObjectsResFolders.ProjAllocationAppFolder(this);
            _dotnetjournalsearch = new CommonObjectsResFolders.DotNetJournalSearchAppFolder(this);
        }

#region Variables

        string _DotnetSelect = "/form[@controlname='AccountLedgerFinderDialog']";

        /// <summary>
        /// Gets or sets the value of variable DotnetSelect.
        /// </summary>
        [TestVariable("6fe354fa-b10a-45b2-83ea-ec18bd6c6373")]
        public string DotnetSelect
        {
            get { return _DotnetSelect; }
            set { _DotnetSelect = value; }
        }

#endregion

        /// <summary>
        /// The Self item info.
        /// </summary>
        [RepositoryItemInfo("ceedd480-7940-4a95-93ce-57f0f33908a7")]
        public virtual RepoItemInfo SelfInfo
        {
            get
            {
                return _selfInfo;
            }
        }

        /// <summary>
        /// The SaveTheFileAs folder.
        /// </summary>
        [RepositoryFolder("6e5ba39e-5966-4e35-a028-d59b10d04ea1")]
        public virtual CommonObjectsResFolders.SaveTheFileAsAppFolder SaveTheFileAs
        {
            get { return _savethefileas; }
        }

        /// <summary>
        /// The DialogJournalSearch folder.
        /// </summary>
        [RepositoryFolder("24617776-38b6-48a6-9831-295059f175eb")]
        public virtual CommonObjectsResFolders.DialogJournalSearchAppFolder DialogJournalSearch
        {
            get { return _dialogjournalsearch; }
        }

        /// <summary>
        /// The SelectAccount folder.
        /// </summary>
        [RepositoryFolder("c8c6be3e-833b-4efe-937e-c55c2764d67c")]
        public virtual CommonObjectsResFolders.SelectAccountAppFolder SelectAccount
        {
            get { return _selectaccount; }
        }

        /// <summary>
        /// The PrintToFile folder.
        /// </summary>
        [RepositoryFolder("9eb0a1a2-a9da-453e-b6b5-1cec9cfe46d7")]
        public virtual CommonObjectsResFolders.PrintToFileAppFolder PrintToFile
        {
            get { return _printtofile; }
        }

        /// <summary>
        /// The ProjAllocation folder.
        /// </summary>
        [RepositoryFolder("858b264d-bd93-469b-bd7a-4638895f2800")]
        public virtual CommonObjectsResFolders.ProjAllocationAppFolder ProjAllocation
        {
            get { return _projallocation; }
        }

        /// <summary>
        /// The DotNetJournalSearch folder.
        /// </summary>
        [RepositoryFolder("04f84130-641f-46a3-9f23-9bbfba7731a1")]
        public virtual CommonObjectsResFolders.DotNetJournalSearchAppFolder DotNetJournalSearch
        {
            get { return _dotnetjournalsearch; }
        }
    }

    /// <summary>
    /// Inner folder classes.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", "8.0")]
    public partial class CommonObjectsResFolders
    {
        /// <summary>
        /// The SaveTheFileAsAppFolder folder.
        /// </summary>
        [RepositoryFolder("6e5ba39e-5966-4e35-a028-d59b10d04ea1")]
        public partial class SaveTheFileAsAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _filenameInfo;
            RepoItemInfo _saveInfo;

            /// <summary>
            /// Creates a new SaveTheFileAs  folder.
            /// </summary>
            public SaveTheFileAsAppFolder(RepoGenBaseFolder parentFolder) :
                    base("SaveTheFileAs", "/form[@title='Save the file as']", parentFolder, 5000, null, true, "6e5ba39e-5966-4e35-a028-d59b10d04ea1", "")
            {
                _filenameInfo = new RepoItemInfo(this, "FileName", "element[@class='DUIViewWndClassName']//combobox[@class='ComboBox']/text[@controlid='1001']", 5000, null, "3557dd9b-ffd4-4365-9030-1ccdfd2e962a");
                _saveInfo = new RepoItemInfo(this, "Save", "button[@text='&Save']", 5000, null, "edc11a31-ab61-4db7-8834-fed2044eec65");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("6e5ba39e-5966-4e35-a028-d59b10d04ea1")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("6e5ba39e-5966-4e35-a028-d59b10d04ea1")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The FileName item.
            /// </summary>
            [RepositoryItem("3557dd9b-ffd4-4365-9030-1ccdfd2e962a")]
            public virtual Ranorex.Text FileName
            {
                get
                {
                    return _filenameInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The FileName item info.
            /// </summary>
            [RepositoryItemInfo("3557dd9b-ffd4-4365-9030-1ccdfd2e962a")]
            public virtual RepoItemInfo FileNameInfo
            {
                get
                {
                    return _filenameInfo;
                }
            }

            /// <summary>
            /// The Save item.
            /// </summary>
            [RepositoryItem("edc11a31-ab61-4db7-8834-fed2044eec65")]
            public virtual Ranorex.Button Save
            {
                get
                {
                    return _saveInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The Save item info.
            /// </summary>
            [RepositoryItemInfo("edc11a31-ab61-4db7-8834-fed2044eec65")]
            public virtual RepoItemInfo SaveInfo
            {
                get
                {
                    return _saveInfo;
                }
            }
        }

        /// <summary>
        /// The DialogJournalSearchAppFolder folder.
        /// </summary>
        [RepositoryFolder("24617776-38b6-48a6-9831-295059f175eb")]
        public partial class DialogJournalSearchAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _nameInfo;
            RepoItemInfo _sourceInfo;
            RepoItemInfo _okInfo;
            RepoItemInfo _startdateInfo;
            RepoItemInfo _finishdateInfo;
            RepoItemInfo _journalentryInfo;
            RepoItemInfo _amountInfo;

            /// <summary>
            /// Creates a new DialogJournalSearch  folder.
            /// </summary>
            public DialogJournalSearchAppFolder(RepoGenBaseFolder parentFolder) :
                    base("DialogJournalSearch", "/form[@title='Search']", parentFolder, 5000, null, true, "24617776-38b6-48a6-9831-295059f175eb", "")
            {
                _nameInfo = new RepoItemInfo(this, "Name", "?/?/combobox[@controlid='207']", 5000, null, "2452813d-8cac-4d15-8c27-5ff8faa6a7e8");
                _sourceInfo = new RepoItemInfo(this, "Source", "container[@caption='Basic']/?/?/text[@accessiblename='Cheque Number:' and @accessiblerole='Text']", 5000, null, "7aec0cae-8160-44ec-ae04-098e7d17d20a");
                _okInfo = new RepoItemInfo(this, "OK", "button[@text='OK']", 5000, null, "b14e5e01-ebfc-400d-86d8-cd282ec2a71b");
                _startdateInfo = new RepoItemInfo(this, "StartDate", "?/?/combobox[@controlid='201']", 5000, null, "45f044a0-7ca1-4199-b7db-1b01ed989983");
                _finishdateInfo = new RepoItemInfo(this, "FinishDate", "?/?/combobox[@controlid='204']", 5000, null, "c744057c-1a8b-4e50-b484-345407319cf2");
                _journalentryInfo = new RepoItemInfo(this, "JournalEntry", "?/?/element[@controlid='211']/text", 30000, null, "a0238f39-256b-4d9a-ae3a-8b271de3c48b");
                _amountInfo = new RepoItemInfo(this, "Amount", "?/?/element[@controlid='213']/text", 30000, null, "ebb46aa2-0a88-4a15-bc18-77b37cbf0308");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("24617776-38b6-48a6-9831-295059f175eb")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("24617776-38b6-48a6-9831-295059f175eb")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The Name item.
            /// </summary>
            [RepositoryItem("2452813d-8cac-4d15-8c27-5ff8faa6a7e8")]
            public virtual Ranorex.ComboBox Name
            {
                get
                {
                    return _nameInfo.CreateAdapter<Ranorex.ComboBox>(true);
                }
            }

            /// <summary>
            /// The Name item info.
            /// </summary>
            [RepositoryItemInfo("2452813d-8cac-4d15-8c27-5ff8faa6a7e8")]
            public virtual RepoItemInfo NameInfo
            {
                get
                {
                    return _nameInfo;
                }
            }

            /// <summary>
            /// The Source item.
            /// </summary>
            [RepositoryItem("7aec0cae-8160-44ec-ae04-098e7d17d20a")]
            public virtual Ranorex.Text Source
            {
                get
                {
                    return _sourceInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The Source item info.
            /// </summary>
            [RepositoryItemInfo("7aec0cae-8160-44ec-ae04-098e7d17d20a")]
            public virtual RepoItemInfo SourceInfo
            {
                get
                {
                    return _sourceInfo;
                }
            }

            /// <summary>
            /// The OK item.
            /// </summary>
            [RepositoryItem("b14e5e01-ebfc-400d-86d8-cd282ec2a71b")]
            public virtual Ranorex.Button OK
            {
                get
                {
                    return _okInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The OK item info.
            /// </summary>
            [RepositoryItemInfo("b14e5e01-ebfc-400d-86d8-cd282ec2a71b")]
            public virtual RepoItemInfo OKInfo
            {
                get
                {
                    return _okInfo;
                }
            }

            /// <summary>
            /// The StartDate item.
            /// </summary>
            [RepositoryItem("45f044a0-7ca1-4199-b7db-1b01ed989983")]
            public virtual Ranorex.ComboBox StartDate
            {
                get
                {
                    return _startdateInfo.CreateAdapter<Ranorex.ComboBox>(true);
                }
            }

            /// <summary>
            /// The StartDate item info.
            /// </summary>
            [RepositoryItemInfo("45f044a0-7ca1-4199-b7db-1b01ed989983")]
            public virtual RepoItemInfo StartDateInfo
            {
                get
                {
                    return _startdateInfo;
                }
            }

            /// <summary>
            /// The FinishDate item.
            /// </summary>
            [RepositoryItem("c744057c-1a8b-4e50-b484-345407319cf2")]
            public virtual Ranorex.ComboBox FinishDate
            {
                get
                {
                    return _finishdateInfo.CreateAdapter<Ranorex.ComboBox>(true);
                }
            }

            /// <summary>
            /// The FinishDate item info.
            /// </summary>
            [RepositoryItemInfo("c744057c-1a8b-4e50-b484-345407319cf2")]
            public virtual RepoItemInfo FinishDateInfo
            {
                get
                {
                    return _finishdateInfo;
                }
            }

            /// <summary>
            /// The JournalEntry item.
            /// </summary>
            [RepositoryItem("a0238f39-256b-4d9a-ae3a-8b271de3c48b")]
            public virtual Ranorex.Text JournalEntry
            {
                get
                {
                    return _journalentryInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The JournalEntry item info.
            /// </summary>
            [RepositoryItemInfo("a0238f39-256b-4d9a-ae3a-8b271de3c48b")]
            public virtual RepoItemInfo JournalEntryInfo
            {
                get
                {
                    return _journalentryInfo;
                }
            }

            /// <summary>
            /// The Amount item.
            /// </summary>
            [RepositoryItem("ebb46aa2-0a88-4a15-bc18-77b37cbf0308")]
            public virtual Ranorex.Text Amount
            {
                get
                {
                    return _amountInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The Amount item info.
            /// </summary>
            [RepositoryItemInfo("ebb46aa2-0a88-4a15-bc18-77b37cbf0308")]
            public virtual RepoItemInfo AmountInfo
            {
                get
                {
                    return _amountInfo;
                }
            }
        }

        /// <summary>
        /// The SelectAccountAppFolder folder.
        /// </summary>
        [RepositoryFolder("c8c6be3e-833b-4efe-937e-c55c2764d67c")]
        public partial class SelectAccountAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _accountnameInfo;
            RepoItemInfo _dotnetaccountnameInfo;
            RepoItemInfo _selectInfo;
            RepoItemInfo _cancelInfo;

            /// <summary>
            /// Creates a new SelectAccount  folder.
            /// </summary>
            public SelectAccountAppFolder(RepoGenBaseFolder parentFolder) :
                    base("SelectAccount", "/form[@title='Select Account' or @controlname='AccountLedgerFinderDialog']", parentFolder, 5000, null, true, "c8c6be3e-833b-4efe-937e-c55c2764d67c", "")
            {
                _accountnameInfo = new RepoItemInfo(this, "AccountName", "?/?/tree[@accessiblename='Item Description']", 5000, null, "1c726ec4-2bfe-4ded-9119-304d9a37c3ef");
                _dotnetaccountnameInfo = new RepoItemInfo(this, "DotNetAccountName", ".//tree[@controlname='m_itemTree']/tree[@accessiblename='Select account:']", 5000, null, "eeb88af9-3d9b-44c8-86d1-ef2395618b9a");
                _selectInfo = new RepoItemInfo(this, "Select", "button[@text='&Select' or @controlname='m_OKButton']", 5000, null, "303ae0e5-1ebd-48a0-9189-a313522b41c8");
                _cancelInfo = new RepoItemInfo(this, "Cancel", "button[@text='&Cancel']", 30000, null, "4898ab7c-79b1-4b38-acbf-1eee307765ef");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("c8c6be3e-833b-4efe-937e-c55c2764d67c")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("c8c6be3e-833b-4efe-937e-c55c2764d67c")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The AccountName item.
            /// </summary>
            [RepositoryItem("1c726ec4-2bfe-4ded-9119-304d9a37c3ef")]
            public virtual Ranorex.Tree AccountName
            {
                get
                {
                    return _accountnameInfo.CreateAdapter<Ranorex.Tree>(true);
                }
            }

            /// <summary>
            /// The AccountName item info.
            /// </summary>
            [RepositoryItemInfo("1c726ec4-2bfe-4ded-9119-304d9a37c3ef")]
            public virtual RepoItemInfo AccountNameInfo
            {
                get
                {
                    return _accountnameInfo;
                }
            }

            /// <summary>
            /// The DotNetAccountName item.
            /// </summary>
            [RepositoryItem("eeb88af9-3d9b-44c8-86d1-ef2395618b9a")]
            public virtual Ranorex.Tree DotNetAccountName
            {
                get
                {
                    return _dotnetaccountnameInfo.CreateAdapter<Ranorex.Tree>(true);
                }
            }

            /// <summary>
            /// The DotNetAccountName item info.
            /// </summary>
            [RepositoryItemInfo("eeb88af9-3d9b-44c8-86d1-ef2395618b9a")]
            public virtual RepoItemInfo DotNetAccountNameInfo
            {
                get
                {
                    return _dotnetaccountnameInfo;
                }
            }

            /// <summary>
            /// The Select item.
            /// </summary>
            [RepositoryItem("303ae0e5-1ebd-48a0-9189-a313522b41c8")]
            public virtual Ranorex.Button Select
            {
                get
                {
                    return _selectInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The Select item info.
            /// </summary>
            [RepositoryItemInfo("303ae0e5-1ebd-48a0-9189-a313522b41c8")]
            public virtual RepoItemInfo SelectInfo
            {
                get
                {
                    return _selectInfo;
                }
            }

            /// <summary>
            /// The Cancel item.
            /// </summary>
            [RepositoryItem("4898ab7c-79b1-4b38-acbf-1eee307765ef")]
            public virtual Ranorex.Button Cancel
            {
                get
                {
                    return _cancelInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The Cancel item info.
            /// </summary>
            [RepositoryItemInfo("4898ab7c-79b1-4b38-acbf-1eee307765ef")]
            public virtual RepoItemInfo CancelInfo
            {
                get
                {
                    return _cancelInfo;
                }
            }
        }

        /// <summary>
        /// The PrintToFileAppFolder folder.
        /// </summary>
        [RepositoryFolder("9eb0a1a2-a9da-453e-b6b5-1cec9cfe46d7")]
        public partial class PrintToFileAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _outputfilenameInfo;
            RepoItemInfo _okInfo;

            /// <summary>
            /// Creates a new PrintToFile  folder.
            /// </summary>
            public PrintToFileAppFolder(RepoGenBaseFolder parentFolder) :
                    base("PrintToFile", "/form[@title='Print to File']", parentFolder, 5000, null, true, "9eb0a1a2-a9da-453e-b6b5-1cec9cfe46d7", "")
            {
                _outputfilenameInfo = new RepoItemInfo(this, "OutputFileName", "text[@controlid='201']", 5000, null, "a79bfac5-0e1d-495d-8569-2a20856ba014");
                _okInfo = new RepoItemInfo(this, "OK", "button[@text='OK']", 5000, null, "29851488-326e-4e7b-9e55-ff1fd92ffa34");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("9eb0a1a2-a9da-453e-b6b5-1cec9cfe46d7")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("9eb0a1a2-a9da-453e-b6b5-1cec9cfe46d7")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The OutputFileName item.
            /// </summary>
            [RepositoryItem("a79bfac5-0e1d-495d-8569-2a20856ba014")]
            public virtual Ranorex.Text OutputFileName
            {
                get
                {
                    return _outputfilenameInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The OutputFileName item info.
            /// </summary>
            [RepositoryItemInfo("a79bfac5-0e1d-495d-8569-2a20856ba014")]
            public virtual RepoItemInfo OutputFileNameInfo
            {
                get
                {
                    return _outputfilenameInfo;
                }
            }

            /// <summary>
            /// The OK item.
            /// </summary>
            [RepositoryItem("29851488-326e-4e7b-9e55-ff1fd92ffa34")]
            public virtual Ranorex.Button OK
            {
                get
                {
                    return _okInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The OK item info.
            /// </summary>
            [RepositoryItemInfo("29851488-326e-4e7b-9e55-ff1fd92ffa34")]
            public virtual RepoItemInfo OKInfo
            {
                get
                {
                    return _okInfo;
                }
            }
        }

        /// <summary>
        /// The ProjAllocationAppFolder folder.
        /// </summary>
        [RepositoryFolder("858b264d-bd93-469b-bd7a-4638895f2800")]
        public partial class ProjAllocationAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _cancelInfo;
            RepoItemInfo _datagridInfo;
            RepoItemInfo _okInfo;

            /// <summary>
            /// Creates a new ProjAllocation  folder.
            /// </summary>
            public ProjAllocationAppFolder(RepoGenBaseFolder parentFolder) :
                    base("ProjAllocation", "/form[@controlname='ProjAllocForm']", parentFolder, 3000, null, true, "858b264d-bd93-469b-bd7a-4638895f2800", "")
            {
                _cancelInfo = new RepoItemInfo(this, "Cancel", "button[@controlname='m_cancelButton']", 3000, null, "21bc9f97-d6ec-4f2a-81c6-fd220937f3f3");
                _datagridInfo = new RepoItemInfo(this, "DataGrid", "table[@controlname='m_dataGrid']", 3000, null, "81c734a7-260c-4c7c-8349-e6f14aef46a5");
                _okInfo = new RepoItemInfo(this, "OK", "button[@controlname='m_OKButton']", 3000, null, "0918c98a-5b78-4740-ae2d-f1e9b13240c6");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("858b264d-bd93-469b-bd7a-4638895f2800")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("858b264d-bd93-469b-bd7a-4638895f2800")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The Cancel item.
            /// </summary>
            [RepositoryItem("21bc9f97-d6ec-4f2a-81c6-fd220937f3f3")]
            public virtual Ranorex.Button Cancel
            {
                get
                {
                    return _cancelInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The Cancel item info.
            /// </summary>
            [RepositoryItemInfo("21bc9f97-d6ec-4f2a-81c6-fd220937f3f3")]
            public virtual RepoItemInfo CancelInfo
            {
                get
                {
                    return _cancelInfo;
                }
            }

            /// <summary>
            /// The DataGrid item.
            /// </summary>
            [RepositoryItem("81c734a7-260c-4c7c-8349-e6f14aef46a5")]
            public virtual Ranorex.Table DataGrid
            {
                get
                {
                    return _datagridInfo.CreateAdapter<Ranorex.Table>(true);
                }
            }

            /// <summary>
            /// The DataGrid item info.
            /// </summary>
            [RepositoryItemInfo("81c734a7-260c-4c7c-8349-e6f14aef46a5")]
            public virtual RepoItemInfo DataGridInfo
            {
                get
                {
                    return _datagridInfo;
                }
            }

            /// <summary>
            /// The OK item.
            /// </summary>
            [RepositoryItem("0918c98a-5b78-4740-ae2d-f1e9b13240c6")]
            public virtual Ranorex.Button OK
            {
                get
                {
                    return _okInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The OK item info.
            /// </summary>
            [RepositoryItemInfo("0918c98a-5b78-4740-ae2d-f1e9b13240c6")]
            public virtual RepoItemInfo OKInfo
            {
                get
                {
                    return _okInfo;
                }
            }
        }

        /// <summary>
        /// The DotNetJournalSearchAppFolder folder.
        /// </summary>
        [RepositoryFolder("04f84130-641f-46a3-9f23-9bbfba7731a1")]
        public partial class DotNetJournalSearchAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _startdateInfo;
            RepoItemInfo _finishdateInfo;
            RepoItemInfo _nameInfo;
            RepoItemInfo _amountInfo;
            RepoItemInfo _invoicenumberInfo;
            RepoItemInfo _sourceInfo;
            RepoItemInfo _closeInfo;
            RepoItemInfo _okInfo;
            RepoItemInfo _cancelInfo;
            RepoItemInfo _openstartdateInfo;
            RepoItemInfo _openfinishdateInfo;

            /// <summary>
            /// Creates a new DotNetJournalSearch  folder.
            /// </summary>
            public DotNetJournalSearchAppFolder(RepoGenBaseFolder parentFolder) :
                    base("DotNetJournalSearch", "/form[@controlname='SearchForm']", parentFolder, 3000, null, true, "04f84130-641f-46a3-9f23-9bbfba7731a1", "")
            {
                _startdateInfo = new RepoItemInfo(this, "StartDate", "?/?/tabpage[@controlname='m_basicTabPage']//container[@controlname='m_StartDatePicker']/combobox[@controlname='m_dateCmb']", 3000, null, "95724818-867e-4e78-8cab-e9139f36470f");
                _finishdateInfo = new RepoItemInfo(this, "FinishDate", "?/?/tabpage[@controlname='m_basicTabPage']//container[@controlname='m_endDatePicker']/combobox[@controlname='m_dateCmb']", 3000, null, "9a0cf9c7-3c2e-47cb-8498-70fb7d81987f");
                _nameInfo = new RepoItemInfo(this, "Name", "tabpagelist[@controlname='m_searchTab']/tabpage[@controlname='m_basicTabPage']//combobox[@controlname='m_findNameCombo']", 3000, null, "80a2c12a-3e14-48a4-9b80-d2d7f92bd72b");
                _amountInfo = new RepoItemInfo(this, "Amount", "tabpagelist[@controlname='m_searchTab']/tabpage[@controlname='m_basicTabPage']//text[@controlname='m_amountDec2Bl']", 3000, null, "dc07b852-72f7-4eb9-b7ea-fe01e01c82c3");
                _invoicenumberInfo = new RepoItemInfo(this, "InvoiceNumber", "tabpagelist[@controlname='m_searchTab']/tabpage[@controlname='m_basicTabPage']//text[@controlname='m_sourceChar']", 3000, null, "0e507853-7d88-469b-8026-1c3289711eed");
                _sourceInfo = new RepoItemInfo(this, "Source", "tabpagelist[@controlname='m_searchTab']/tabpage[@controlname='m_basicTabPage']//text[@controlname='m_transNum']", 3000, null, "9387adf6-6411-4502-a477-409c832c7a49");
                _closeInfo = new RepoItemInfo(this, "Close", "?/?/button[@accessiblename='Close']", 3000, null, "4699c545-d372-42b2-9c8c-1d4df60401d0");
                _okInfo = new RepoItemInfo(this, "OK", "button[@controlname='m_OKButton']", 3000, null, "a8685faf-5b93-4388-ad19-e636bc31f4ef");
                _cancelInfo = new RepoItemInfo(this, "Cancel", "button[@controlname='m_cancelButton']", 3000, null, "f8213bbf-a90b-43e7-abe1-6be0c32bff0b");
                _openstartdateInfo = new RepoItemInfo(this, "OpenStartDate", "?/?/tabpage[@controlname='m_basicTabPage']//container[@controlname='m_StartDatePicker']/combobox[@controlname='m_dateCmb']/button[@accessiblename='Open']", 30000, null, "fd0a6a97-d808-49e5-86c1-abf1f076b3dd");
                _openfinishdateInfo = new RepoItemInfo(this, "OpenFinishDate", "?/?/tabpage[@controlname='m_basicTabPage']//container[@controlname='m_endDatePicker']/combobox[@controlname='m_dateCmb']/button[@accessiblename='Open']", 30000, null, "59f9f7cb-ec4b-479d-b920-12abf4b26cbc");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("04f84130-641f-46a3-9f23-9bbfba7731a1")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("04f84130-641f-46a3-9f23-9bbfba7731a1")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The StartDate item.
            /// </summary>
            [RepositoryItem("95724818-867e-4e78-8cab-e9139f36470f")]
            public virtual Ranorex.ComboBox StartDate
            {
                get
                {
                    return _startdateInfo.CreateAdapter<Ranorex.ComboBox>(true);
                }
            }

            /// <summary>
            /// The StartDate item info.
            /// </summary>
            [RepositoryItemInfo("95724818-867e-4e78-8cab-e9139f36470f")]
            public virtual RepoItemInfo StartDateInfo
            {
                get
                {
                    return _startdateInfo;
                }
            }

            /// <summary>
            /// The FinishDate item.
            /// </summary>
            [RepositoryItem("9a0cf9c7-3c2e-47cb-8498-70fb7d81987f")]
            public virtual Ranorex.ComboBox FinishDate
            {
                get
                {
                    return _finishdateInfo.CreateAdapter<Ranorex.ComboBox>(true);
                }
            }

            /// <summary>
            /// The FinishDate item info.
            /// </summary>
            [RepositoryItemInfo("9a0cf9c7-3c2e-47cb-8498-70fb7d81987f")]
            public virtual RepoItemInfo FinishDateInfo
            {
                get
                {
                    return _finishdateInfo;
                }
            }

            /// <summary>
            /// The Name item.
            /// </summary>
            [RepositoryItem("80a2c12a-3e14-48a4-9b80-d2d7f92bd72b")]
            public virtual Ranorex.ComboBox Name
            {
                get
                {
                    return _nameInfo.CreateAdapter<Ranorex.ComboBox>(true);
                }
            }

            /// <summary>
            /// The Name item info.
            /// </summary>
            [RepositoryItemInfo("80a2c12a-3e14-48a4-9b80-d2d7f92bd72b")]
            public virtual RepoItemInfo NameInfo
            {
                get
                {
                    return _nameInfo;
                }
            }

            /// <summary>
            /// The Amount item.
            /// </summary>
            [RepositoryItem("dc07b852-72f7-4eb9-b7ea-fe01e01c82c3")]
            public virtual Ranorex.Text Amount
            {
                get
                {
                    return _amountInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The Amount item info.
            /// </summary>
            [RepositoryItemInfo("dc07b852-72f7-4eb9-b7ea-fe01e01c82c3")]
            public virtual RepoItemInfo AmountInfo
            {
                get
                {
                    return _amountInfo;
                }
            }

            /// <summary>
            /// The InvoiceNumber item.
            /// </summary>
            [RepositoryItem("0e507853-7d88-469b-8026-1c3289711eed")]
            public virtual Ranorex.Text InvoiceNumber
            {
                get
                {
                    return _invoicenumberInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The InvoiceNumber item info.
            /// </summary>
            [RepositoryItemInfo("0e507853-7d88-469b-8026-1c3289711eed")]
            public virtual RepoItemInfo InvoiceNumberInfo
            {
                get
                {
                    return _invoicenumberInfo;
                }
            }

            /// <summary>
            /// The Source item.
            /// </summary>
            [RepositoryItem("9387adf6-6411-4502-a477-409c832c7a49")]
            public virtual Ranorex.Text Source
            {
                get
                {
                    return _sourceInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The Source item info.
            /// </summary>
            [RepositoryItemInfo("9387adf6-6411-4502-a477-409c832c7a49")]
            public virtual RepoItemInfo SourceInfo
            {
                get
                {
                    return _sourceInfo;
                }
            }

            /// <summary>
            /// The Close item.
            /// </summary>
            [RepositoryItem("4699c545-d372-42b2-9c8c-1d4df60401d0")]
            public virtual Ranorex.Button Close
            {
                get
                {
                    return _closeInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The Close item info.
            /// </summary>
            [RepositoryItemInfo("4699c545-d372-42b2-9c8c-1d4df60401d0")]
            public virtual RepoItemInfo CloseInfo
            {
                get
                {
                    return _closeInfo;
                }
            }

            /// <summary>
            /// The OK item.
            /// </summary>
            [RepositoryItem("a8685faf-5b93-4388-ad19-e636bc31f4ef")]
            public virtual Ranorex.Button OK
            {
                get
                {
                    return _okInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The OK item info.
            /// </summary>
            [RepositoryItemInfo("a8685faf-5b93-4388-ad19-e636bc31f4ef")]
            public virtual RepoItemInfo OKInfo
            {
                get
                {
                    return _okInfo;
                }
            }

            /// <summary>
            /// The Cancel item.
            /// </summary>
            [RepositoryItem("f8213bbf-a90b-43e7-abe1-6be0c32bff0b")]
            public virtual Ranorex.Button Cancel
            {
                get
                {
                    return _cancelInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The Cancel item info.
            /// </summary>
            [RepositoryItemInfo("f8213bbf-a90b-43e7-abe1-6be0c32bff0b")]
            public virtual RepoItemInfo CancelInfo
            {
                get
                {
                    return _cancelInfo;
                }
            }

            /// <summary>
            /// The OpenStartDate item.
            /// </summary>
            [RepositoryItem("fd0a6a97-d808-49e5-86c1-abf1f076b3dd")]
            public virtual Ranorex.Button OpenStartDate
            {
                get
                {
                    return _openstartdateInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The OpenStartDate item info.
            /// </summary>
            [RepositoryItemInfo("fd0a6a97-d808-49e5-86c1-abf1f076b3dd")]
            public virtual RepoItemInfo OpenStartDateInfo
            {
                get
                {
                    return _openstartdateInfo;
                }
            }

            /// <summary>
            /// The OpenFinishDate item.
            /// </summary>
            [RepositoryItem("59f9f7cb-ec4b-479d-b920-12abf4b26cbc")]
            public virtual Ranorex.Button OpenFinishDate
            {
                get
                {
                    return _openfinishdateInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The OpenFinishDate item info.
            /// </summary>
            [RepositoryItemInfo("59f9f7cb-ec4b-479d-b920-12abf4b26cbc")]
            public virtual RepoItemInfo OpenFinishDateInfo
            {
                get
                {
                    return _openfinishdateInfo;
                }
            }
        }

    }
#pragma warning restore 0436
}