///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Drawing;
using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace Sage50.Repository
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    /// The class representing the GeneralLedgerRes element repository.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", "8.0")]
    [RepositoryFolder("0eb6de89-3a6e-4c92-bedd-3477f2217c59")]
    public partial class GeneralLedgerRes : RepoGenBaseFolder
    {
        static GeneralLedgerRes instance = new GeneralLedgerRes();
        GeneralLedgerResFolders.GeneralLedgerAppFolder _generalledger;
        GeneralLedgerResFolders.WindowsTaskManagerAppFolder _windowstaskmanager;
        GeneralLedgerResFolders.EnterAccountNameAppFolder _enteraccountname;
        GeneralLedgerResFolders.GeneralIconAppFolder _generalicon;

        /// <summary>
        /// Gets the singleton class instance representing the GeneralLedgerRes element repository.
        /// </summary>
        [RepositoryFolder("0eb6de89-3a6e-4c92-bedd-3477f2217c59")]
        public static GeneralLedgerRes Instance
        {
            get { return instance; }
        }

        /// <summary>
        /// Repository class constructor.
        /// </summary>
        public GeneralLedgerRes() 
            : base("GeneralLedgerRes", "/", null, 0, false, "0eb6de89-3a6e-4c92-bedd-3477f2217c59", ".\\RepositoryImages\\GeneralLedgerRes0eb6de89.rximgres")
        {
            _generalledger = new GeneralLedgerResFolders.GeneralLedgerAppFolder(this);
            _windowstaskmanager = new GeneralLedgerResFolders.WindowsTaskManagerAppFolder(this);
            _enteraccountname = new GeneralLedgerResFolders.EnterAccountNameAppFolder(this);
            _generalicon = new GeneralLedgerResFolders.GeneralIconAppFolder(this);
        }

#region Variables

#endregion

        /// <summary>
        /// The Self item info.
        /// </summary>
        [RepositoryItemInfo("0eb6de89-3a6e-4c92-bedd-3477f2217c59")]
        public virtual RepoItemInfo SelfInfo
        {
            get
            {
                return _selfInfo;
            }
        }

        /// <summary>
        /// The GeneralLedger folder.
        /// </summary>
        [RepositoryFolder("8f680db7-13cf-4193-86c0-11ba4636c96a")]
        public virtual GeneralLedgerResFolders.GeneralLedgerAppFolder GeneralLedger
        {
            get { return _generalledger; }
        }

        /// <summary>
        /// The WindowsTaskManager folder.
        /// </summary>
        [RepositoryFolder("7804c55e-d08f-41df-944a-7ce260c12155")]
        public virtual GeneralLedgerResFolders.WindowsTaskManagerAppFolder WindowsTaskManager
        {
            get { return _windowstaskmanager; }
        }

        /// <summary>
        /// The EnterAccountName folder.
        /// </summary>
        [RepositoryFolder("8a1d7435-ea8d-4b04-a756-835dc86e5972")]
        public virtual GeneralLedgerResFolders.EnterAccountNameAppFolder EnterAccountName
        {
            get { return _enteraccountname; }
        }

        /// <summary>
        /// The GeneralIcon folder.
        /// </summary>
        [RepositoryFolder("575ceeff-b1a1-40ed-8947-76986849ed56")]
        public virtual GeneralLedgerResFolders.GeneralIconAppFolder GeneralIcon
        {
            get { return _generalicon; }
        }
    }

    /// <summary>
    /// Inner folder classes.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", "8.0")]
    public partial class GeneralLedgerResFolders
    {
        /// <summary>
        /// The GeneralLedgerAppFolder folder.
        /// </summary>
        [RepositoryFolder("8f680db7-13cf-4193-86c0-11ba4636c96a")]
        public partial class GeneralLedgerAppFolder : RepoGenBaseFolder
        {
            GeneralLedgerResFolders.AccountFolder _account;
            GeneralLedgerResFolders.ClassOptionsFolder _classoptions;
            GeneralLedgerResFolders.BudgetFolder _budget;
            GeneralLedgerResFolders.AdditionalInfoFolder _additionalinfo;
            RepoItemInfo _accountnumberInfo;
            RepoItemInfo _accountnameInfo;
            RepoItemInfo _saveInfo;
            RepoItemInfo _openbalanceInfo;
            RepoItemInfo _createanewtoolbuttonInfo;
            RepoItemInfo _foreignopenbalanceInfo;
            RepoItemInfo _inactiveaccountInfo;
            RepoItemInfo _selectrecordInfo;
            RepoItemInfo _languagebtnInfo;

            /// <summary>
            /// Creates a new GeneralLedger  folder.
            /// </summary>
            public GeneralLedgerAppFolder(RepoGenBaseFolder parentFolder) :
                    base("GeneralLedger", "/form[@title='General Ledger']", parentFolder, 3000, null, true, "8f680db7-13cf-4193-86c0-11ba4636c96a", "")
            {
                _account = new GeneralLedgerResFolders.AccountFolder(this);
                _classoptions = new GeneralLedgerResFolders.ClassOptionsFolder(this);
                _budget = new GeneralLedgerResFolders.BudgetFolder(this);
                _additionalinfo = new GeneralLedgerResFolders.AdditionalInfoFolder(this);
                _accountnumberInfo = new RepoItemInfo(this, "AccountNumber", "element[@controlid='22']/text", 3000, null, "93448d09-2096-4e04-bbec-8627dec92e55");
                _accountnameInfo = new RepoItemInfo(this, "AccountName", "element[@controlid='26']/text", 3000, null, "e4365cbf-f869-4d00-b8a2-dad17cd49a68");
                _saveInfo = new RepoItemInfo(this, "Save", "?/?/toolbar[@class='ToolbarWindow32' and @instance='0']/button[@text~'^Save\\ the\\ current\\.*']", 3000, null, "1f3c22f5-7ec7-42c5-a38a-5f880f80f48a");
                _openbalanceInfo = new RepoItemInfo(this, "OpenBalance", "element[@controlid='181']/text", 3000, null, "982f3929-abd0-459f-ba1f-9a9108f045db");
                _createanewtoolbuttonInfo = new RepoItemInfo(this, "CreateANewToolButton", "?/?/toolbar[@class='ToolbarWindow32' and @instance='0']/button[@text~'^Create\\ a\\ new\\ account\\ \\(Ct']", 3000, null, "9cfb97be-06f2-4111-befe-dfa354ce0d71");
                _foreignopenbalanceInfo = new RepoItemInfo(this, "ForeignOpenBalance", "element[@controlid='183']/text", 3000, null, "7149e5bd-3ffb-4ad8-9bec-ad367b975f68");
                _inactiveaccountInfo = new RepoItemInfo(this, "InactiveAccount", "checkbox[@controlid='200']", 3000, null, "49f68262-0984-4c77-815d-b08a9cb62741");
                _selectrecordInfo = new RepoItemInfo(this, "SelectRecord", "?/?/toolbar[@class='ToolbarWindow32' and @instance='1']/combobox[@controlid='504']", 3000, null, "61295f49-3e5b-49b2-92dd-a5e83973ef22");
                _languagebtnInfo = new RepoItemInfo(this, "LanguageBtn", "button[@controlid='31']", 3000, null, "0316e5aa-dfb1-4a8f-9682-ac7bf5cc5f06");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("8f680db7-13cf-4193-86c0-11ba4636c96a")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("8f680db7-13cf-4193-86c0-11ba4636c96a")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The AccountNumber item.
            /// </summary>
            [RepositoryItem("93448d09-2096-4e04-bbec-8627dec92e55")]
            public virtual Ranorex.Text AccountNumber
            {
                get
                {
                    return _accountnumberInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The AccountNumber item info.
            /// </summary>
            [RepositoryItemInfo("93448d09-2096-4e04-bbec-8627dec92e55")]
            public virtual RepoItemInfo AccountNumberInfo
            {
                get
                {
                    return _accountnumberInfo;
                }
            }

            /// <summary>
            /// The AccountName item.
            /// </summary>
            [RepositoryItem("e4365cbf-f869-4d00-b8a2-dad17cd49a68")]
            public virtual Ranorex.Text AccountName
            {
                get
                {
                    return _accountnameInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The AccountName item info.
            /// </summary>
            [RepositoryItemInfo("e4365cbf-f869-4d00-b8a2-dad17cd49a68")]
            public virtual RepoItemInfo AccountNameInfo
            {
                get
                {
                    return _accountnameInfo;
                }
            }

            /// <summary>
            /// The Save item.
            /// </summary>
            [RepositoryItem("1f3c22f5-7ec7-42c5-a38a-5f880f80f48a")]
            public virtual Ranorex.Button Save
            {
                get
                {
                    return _saveInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The Save item info.
            /// </summary>
            [RepositoryItemInfo("1f3c22f5-7ec7-42c5-a38a-5f880f80f48a")]
            public virtual RepoItemInfo SaveInfo
            {
                get
                {
                    return _saveInfo;
                }
            }

            /// <summary>
            /// The OpenBalance item.
            /// </summary>
            [RepositoryItem("982f3929-abd0-459f-ba1f-9a9108f045db")]
            public virtual Ranorex.Text OpenBalance
            {
                get
                {
                    return _openbalanceInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The OpenBalance item info.
            /// </summary>
            [RepositoryItemInfo("982f3929-abd0-459f-ba1f-9a9108f045db")]
            public virtual RepoItemInfo OpenBalanceInfo
            {
                get
                {
                    return _openbalanceInfo;
                }
            }

            /// <summary>
            /// The CreateANewToolButton item.
            /// </summary>
            [RepositoryItem("9cfb97be-06f2-4111-befe-dfa354ce0d71")]
            public virtual Ranorex.Button CreateANewToolButton
            {
                get
                {
                    return _createanewtoolbuttonInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The CreateANewToolButton item info.
            /// </summary>
            [RepositoryItemInfo("9cfb97be-06f2-4111-befe-dfa354ce0d71")]
            public virtual RepoItemInfo CreateANewToolButtonInfo
            {
                get
                {
                    return _createanewtoolbuttonInfo;
                }
            }

            /// <summary>
            /// The ForeignOpenBalance item.
            /// </summary>
            [RepositoryItem("7149e5bd-3ffb-4ad8-9bec-ad367b975f68")]
            public virtual Ranorex.Text ForeignOpenBalance
            {
                get
                {
                    return _foreignopenbalanceInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The ForeignOpenBalance item info.
            /// </summary>
            [RepositoryItemInfo("7149e5bd-3ffb-4ad8-9bec-ad367b975f68")]
            public virtual RepoItemInfo ForeignOpenBalanceInfo
            {
                get
                {
                    return _foreignopenbalanceInfo;
                }
            }

            /// <summary>
            /// The InactiveAccount item.
            /// </summary>
            [RepositoryItem("49f68262-0984-4c77-815d-b08a9cb62741")]
            public virtual Ranorex.CheckBox InactiveAccount
            {
                get
                {
                    return _inactiveaccountInfo.CreateAdapter<Ranorex.CheckBox>(true);
                }
            }

            /// <summary>
            /// The InactiveAccount item info.
            /// </summary>
            [RepositoryItemInfo("49f68262-0984-4c77-815d-b08a9cb62741")]
            public virtual RepoItemInfo InactiveAccountInfo
            {
                get
                {
                    return _inactiveaccountInfo;
                }
            }

            /// <summary>
            /// The SelectRecord item.
            /// </summary>
            [RepositoryItem("61295f49-3e5b-49b2-92dd-a5e83973ef22")]
            public virtual Ranorex.ComboBox SelectRecord
            {
                get
                {
                    return _selectrecordInfo.CreateAdapter<Ranorex.ComboBox>(true);
                }
            }

            /// <summary>
            /// The SelectRecord item info.
            /// </summary>
            [RepositoryItemInfo("61295f49-3e5b-49b2-92dd-a5e83973ef22")]
            public virtual RepoItemInfo SelectRecordInfo
            {
                get
                {
                    return _selectrecordInfo;
                }
            }

            /// <summary>
            /// The LanguageBtn item.
            /// </summary>
            [RepositoryItem("0316e5aa-dfb1-4a8f-9682-ac7bf5cc5f06")]
            public virtual Ranorex.Button LanguageBtn
            {
                get
                {
                    return _languagebtnInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The LanguageBtn item info.
            /// </summary>
            [RepositoryItemInfo("0316e5aa-dfb1-4a8f-9682-ac7bf5cc5f06")]
            public virtual RepoItemInfo LanguageBtnInfo
            {
                get
                {
                    return _languagebtnInfo;
                }
            }

            /// <summary>
            /// The Account folder.
            /// </summary>
            [RepositoryFolder("05db51a2-e68b-44b2-b6a0-238fb12647fa")]
            public virtual GeneralLedgerResFolders.AccountFolder Account
            {
                get { return _account; }
            }

            /// <summary>
            /// The ClassOptions folder.
            /// </summary>
            [RepositoryFolder("1b538c7e-23c3-4cf3-af45-90c2467f6db6")]
            public virtual GeneralLedgerResFolders.ClassOptionsFolder ClassOptions
            {
                get { return _classoptions; }
            }

            /// <summary>
            /// The Budget folder.
            /// </summary>
            [RepositoryFolder("ac2aa78f-b329-4447-a803-bbd51775cb24")]
            public virtual GeneralLedgerResFolders.BudgetFolder Budget
            {
                get { return _budget; }
            }

            /// <summary>
            /// The AdditionalInfo folder.
            /// </summary>
            [RepositoryFolder("895aaf07-026f-4df9-9a3c-d1fe16098dd7")]
            public virtual GeneralLedgerResFolders.AdditionalInfoFolder AdditionalInfo
            {
                get { return _additionalinfo; }
            }
        }

        /// <summary>
        /// The AccountFolder folder.
        /// </summary>
        [RepositoryFolder("05db51a2-e68b-44b2-b6a0-238fb12647fa")]
        public partial class AccountFolder : RepoGenBaseFolder
        {
            RepoItemInfo _tabInfo;
            RepoItemInfo _acctgrpheadingInfo;
            RepoItemInfo _subgrpacctInfo;
            RepoItemInfo _subgrptotalInfo;
            RepoItemInfo _grpacctInfo;
            RepoItemInfo _grptotalInfo;
            RepoItemInfo _gificodeInfo;
            RepoItemInfo _omitfromInfo;
            RepoItemInfo _allowprojectallocationInfo;

            /// <summary>
            /// Creates a new Account  folder.
            /// </summary>
            public AccountFolder(RepoGenBaseFolder parentFolder) :
                    base("Account", "", parentFolder, 500, null, false, "05db51a2-e68b-44b2-b6a0-238fb12647fa", "")
            {
                _tabInfo = new RepoItemInfo(this, "Tab", "?/?/tabpage[@title='Account']", 3000, null, "4e52ffd5-23bd-437f-a219-d7e49f885909");
                _acctgrpheadingInfo = new RepoItemInfo(this, "AcctGrpHeading", "?/?/radiobutton[@accessiblename='Group Heading']", 3000, null, "e15457ab-d8a6-4585-adc4-446b0de8805b");
                _subgrpacctInfo = new RepoItemInfo(this, "SubGrpAcct", "?/?/radiobutton[@accessiblename='Subgroup Account']", 3000, null, "042e1ce3-4c8e-40ef-80bd-3167c3c06a53");
                _subgrptotalInfo = new RepoItemInfo(this, "SubGrpTotal", "?/?/radiobutton[@accessiblename='Subgroup Total']", 3000, null, "eb3ec760-e4cf-455d-8cec-f42961e40958");
                _grpacctInfo = new RepoItemInfo(this, "GrpAcct", "?/?/radiobutton[@accessiblename='Group Account']", 3000, null, "ac919210-144e-4d8c-8a13-6206c47d8bd5");
                _grptotalInfo = new RepoItemInfo(this, "GrpTotal", "?/?/radiobutton[@accessiblename='Group Total']", 3000, null, "5951b539-7ecc-4852-a1c1-fe71896f8f9a");
                _gificodeInfo = new RepoItemInfo(this, "GifiCode", "element[@controlid='54']/text", 3000, null, "3312f7e9-be33-4b2e-83e5-532e3ba3dbb4");
                _omitfromInfo = new RepoItemInfo(this, "OmitFrom", "checkbox[@controlid='51']", 3000, null, "9aabf058-73fe-4168-9e56-4018c530f2d7");
                _allowprojectallocationInfo = new RepoItemInfo(this, "AllowProjectAllocation", "checkbox[@controlid='50']", 3000, null, "435ce74f-ee81-461f-b285-5de6ee8e4c4b");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("05db51a2-e68b-44b2-b6a0-238fb12647fa")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("05db51a2-e68b-44b2-b6a0-238fb12647fa")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The Tab item.
            /// </summary>
            [RepositoryItem("4e52ffd5-23bd-437f-a219-d7e49f885909")]
            public virtual Ranorex.TabPage Tab
            {
                get
                {
                    return _tabInfo.CreateAdapter<Ranorex.TabPage>(true);
                }
            }

            /// <summary>
            /// The Tab item info.
            /// </summary>
            [RepositoryItemInfo("4e52ffd5-23bd-437f-a219-d7e49f885909")]
            public virtual RepoItemInfo TabInfo
            {
                get
                {
                    return _tabInfo;
                }
            }

            /// <summary>
            /// The AcctGrpHeading item.
            /// </summary>
            [RepositoryItem("e15457ab-d8a6-4585-adc4-446b0de8805b")]
            public virtual Ranorex.RadioButton AcctGrpHeading
            {
                get
                {
                    return _acctgrpheadingInfo.CreateAdapter<Ranorex.RadioButton>(true);
                }
            }

            /// <summary>
            /// The AcctGrpHeading item info.
            /// </summary>
            [RepositoryItemInfo("e15457ab-d8a6-4585-adc4-446b0de8805b")]
            public virtual RepoItemInfo AcctGrpHeadingInfo
            {
                get
                {
                    return _acctgrpheadingInfo;
                }
            }

            /// <summary>
            /// The SubGrpAcct item.
            /// </summary>
            [RepositoryItem("042e1ce3-4c8e-40ef-80bd-3167c3c06a53")]
            public virtual Ranorex.RadioButton SubGrpAcct
            {
                get
                {
                    return _subgrpacctInfo.CreateAdapter<Ranorex.RadioButton>(true);
                }
            }

            /// <summary>
            /// The SubGrpAcct item info.
            /// </summary>
            [RepositoryItemInfo("042e1ce3-4c8e-40ef-80bd-3167c3c06a53")]
            public virtual RepoItemInfo SubGrpAcctInfo
            {
                get
                {
                    return _subgrpacctInfo;
                }
            }

            /// <summary>
            /// The SubGrpTotal item.
            /// </summary>
            [RepositoryItem("eb3ec760-e4cf-455d-8cec-f42961e40958")]
            public virtual Ranorex.RadioButton SubGrpTotal
            {
                get
                {
                    return _subgrptotalInfo.CreateAdapter<Ranorex.RadioButton>(true);
                }
            }

            /// <summary>
            /// The SubGrpTotal item info.
            /// </summary>
            [RepositoryItemInfo("eb3ec760-e4cf-455d-8cec-f42961e40958")]
            public virtual RepoItemInfo SubGrpTotalInfo
            {
                get
                {
                    return _subgrptotalInfo;
                }
            }

            /// <summary>
            /// The GrpAcct item.
            /// </summary>
            [RepositoryItem("ac919210-144e-4d8c-8a13-6206c47d8bd5")]
            public virtual Ranorex.RadioButton GrpAcct
            {
                get
                {
                    return _grpacctInfo.CreateAdapter<Ranorex.RadioButton>(true);
                }
            }

            /// <summary>
            /// The GrpAcct item info.
            /// </summary>
            [RepositoryItemInfo("ac919210-144e-4d8c-8a13-6206c47d8bd5")]
            public virtual RepoItemInfo GrpAcctInfo
            {
                get
                {
                    return _grpacctInfo;
                }
            }

            /// <summary>
            /// The GrpTotal item.
            /// </summary>
            [RepositoryItem("5951b539-7ecc-4852-a1c1-fe71896f8f9a")]
            public virtual Ranorex.RadioButton GrpTotal
            {
                get
                {
                    return _grptotalInfo.CreateAdapter<Ranorex.RadioButton>(true);
                }
            }

            /// <summary>
            /// The GrpTotal item info.
            /// </summary>
            [RepositoryItemInfo("5951b539-7ecc-4852-a1c1-fe71896f8f9a")]
            public virtual RepoItemInfo GrpTotalInfo
            {
                get
                {
                    return _grptotalInfo;
                }
            }

            /// <summary>
            /// The GifiCode item.
            /// </summary>
            [RepositoryItem("3312f7e9-be33-4b2e-83e5-532e3ba3dbb4")]
            public virtual Ranorex.Text GifiCode
            {
                get
                {
                    return _gificodeInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The GifiCode item info.
            /// </summary>
            [RepositoryItemInfo("3312f7e9-be33-4b2e-83e5-532e3ba3dbb4")]
            public virtual RepoItemInfo GifiCodeInfo
            {
                get
                {
                    return _gificodeInfo;
                }
            }

            /// <summary>
            /// The OmitFrom item.
            /// </summary>
            [RepositoryItem("9aabf058-73fe-4168-9e56-4018c530f2d7")]
            public virtual Ranorex.CheckBox OmitFrom
            {
                get
                {
                    return _omitfromInfo.CreateAdapter<Ranorex.CheckBox>(true);
                }
            }

            /// <summary>
            /// The OmitFrom item info.
            /// </summary>
            [RepositoryItemInfo("9aabf058-73fe-4168-9e56-4018c530f2d7")]
            public virtual RepoItemInfo OmitFromInfo
            {
                get
                {
                    return _omitfromInfo;
                }
            }

            /// <summary>
            /// The AllowProjectAllocation item.
            /// </summary>
            [RepositoryItem("435ce74f-ee81-461f-b285-5de6ee8e4c4b")]
            public virtual Ranorex.CheckBox AllowProjectAllocation
            {
                get
                {
                    return _allowprojectallocationInfo.CreateAdapter<Ranorex.CheckBox>(true);
                }
            }

            /// <summary>
            /// The AllowProjectAllocation item info.
            /// </summary>
            [RepositoryItemInfo("435ce74f-ee81-461f-b285-5de6ee8e4c4b")]
            public virtual RepoItemInfo AllowProjectAllocationInfo
            {
                get
                {
                    return _allowprojectallocationInfo;
                }
            }
        }

        /// <summary>
        /// The ClassOptionsFolder folder.
        /// </summary>
        [RepositoryFolder("1b538c7e-23c3-4cf3-af45-90c2467f6db6")]
        public partial class ClassOptionsFolder : RepoGenBaseFolder
        {
            RepoItemInfo _tabInfo;
            RepoItemInfo _accountclassInfo;
            RepoItemInfo _currencycodeInfo;
            RepoItemInfo _nextdepositnumberInfo;
            RepoItemInfo _institutionInfo;
            RepoItemInfo _branchnameInfo;
            RepoItemInfo _transitnumberInfo;
            RepoItemInfo _bankaccountnumberInfo;
            RepoItemInfo _bankaccounttypeInfo;
            RepoItemInfo _useforonlineInfo;
            RepoItemInfo _homepageInfo;
            RepoItemInfo _onlineloginInfo;

            /// <summary>
            /// Creates a new ClassOptions  folder.
            /// </summary>
            public ClassOptionsFolder(RepoGenBaseFolder parentFolder) :
                    base("ClassOptions", "", parentFolder, 500, null, false, "1b538c7e-23c3-4cf3-af45-90c2467f6db6", "")
            {
                _tabInfo = new RepoItemInfo(this, "Tab", "?/?/tabpage[@title='Class Options']", 3000, null, "e8adf47a-ac20-4afb-bc71-9ee98d76675e");
                _accountclassInfo = new RepoItemInfo(this, "AccountClass", "combobox[@controlid='146']", 3000, null, "4ba7a483-cb6f-45f5-a5e7-4ea26cb304d1");
                _currencycodeInfo = new RepoItemInfo(this, "CurrencyCode", "combobox[@controlid='158']", 3000, null, "2ed88acb-b0c8-4a24-9332-0606358f2c72");
                _nextdepositnumberInfo = new RepoItemInfo(this, "NextDepositNumber", "element[@controlid='225']/text", 3000, null, "018e7365-32a1-4cd7-85d9-14edfca88981");
                _institutionInfo = new RepoItemInfo(this, "Institution", "combobox[@controlid='144']", 3000, null, "7b8df25f-07d3-4245-b3cb-179ede2ca17d");
                _branchnameInfo = new RepoItemInfo(this, "BranchName", "element[@controlid='150']/text", 3000, null, "4f832460-e0c5-44f6-8303-4148918037dc");
                _transitnumberInfo = new RepoItemInfo(this, "TransitNumber", "element[@controlid='154']/text", 3000, null, "4ec4f454-4186-4d44-95f5-6696ad6ce916");
                _bankaccountnumberInfo = new RepoItemInfo(this, "BankAccountNumber", "element[@controlid='156']/text", 3000, null, "9be77f97-05e7-4ce1-a9b6-af7e9d288c42");
                _bankaccounttypeInfo = new RepoItemInfo(this, "BankAccountType", "combobox[@controlid='152']", 3000, null, "457982e1-8eec-449c-aaa6-98b4ab6fcc11");
                _useforonlineInfo = new RepoItemInfo(this, "UseForOnline", "checkbox[@controlid='173']", 3000, null, "7c360b89-4d7b-416b-834c-1c80cda7bbaf");
                _homepageInfo = new RepoItemInfo(this, "HomePage", "element[@controlid='168']/text", 3000, null, "c24c44c5-d31a-451e-a177-f5683a2a34cd");
                _onlineloginInfo = new RepoItemInfo(this, "OnlineLogin", "element[@controlid='170']/text", 3000, null, "4110c678-1395-4b9e-8b5b-8ddc1f2c259f");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("1b538c7e-23c3-4cf3-af45-90c2467f6db6")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("1b538c7e-23c3-4cf3-af45-90c2467f6db6")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The Tab item.
            /// </summary>
            [RepositoryItem("e8adf47a-ac20-4afb-bc71-9ee98d76675e")]
            public virtual Ranorex.TabPage Tab
            {
                get
                {
                    return _tabInfo.CreateAdapter<Ranorex.TabPage>(true);
                }
            }

            /// <summary>
            /// The Tab item info.
            /// </summary>
            [RepositoryItemInfo("e8adf47a-ac20-4afb-bc71-9ee98d76675e")]
            public virtual RepoItemInfo TabInfo
            {
                get
                {
                    return _tabInfo;
                }
            }

            /// <summary>
            /// The AccountClass item.
            /// </summary>
            [RepositoryItem("4ba7a483-cb6f-45f5-a5e7-4ea26cb304d1")]
            public virtual Ranorex.ComboBox AccountClass
            {
                get
                {
                    return _accountclassInfo.CreateAdapter<Ranorex.ComboBox>(true);
                }
            }

            /// <summary>
            /// The AccountClass item info.
            /// </summary>
            [RepositoryItemInfo("4ba7a483-cb6f-45f5-a5e7-4ea26cb304d1")]
            public virtual RepoItemInfo AccountClassInfo
            {
                get
                {
                    return _accountclassInfo;
                }
            }

            /// <summary>
            /// The CurrencyCode item.
            /// </summary>
            [RepositoryItem("2ed88acb-b0c8-4a24-9332-0606358f2c72")]
            public virtual Ranorex.ComboBox CurrencyCode
            {
                get
                {
                    return _currencycodeInfo.CreateAdapter<Ranorex.ComboBox>(true);
                }
            }

            /// <summary>
            /// The CurrencyCode item info.
            /// </summary>
            [RepositoryItemInfo("2ed88acb-b0c8-4a24-9332-0606358f2c72")]
            public virtual RepoItemInfo CurrencyCodeInfo
            {
                get
                {
                    return _currencycodeInfo;
                }
            }

            /// <summary>
            /// The NextDepositNumber item.
            /// </summary>
            [RepositoryItem("018e7365-32a1-4cd7-85d9-14edfca88981")]
            public virtual Ranorex.Text NextDepositNumber
            {
                get
                {
                    return _nextdepositnumberInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The NextDepositNumber item info.
            /// </summary>
            [RepositoryItemInfo("018e7365-32a1-4cd7-85d9-14edfca88981")]
            public virtual RepoItemInfo NextDepositNumberInfo
            {
                get
                {
                    return _nextdepositnumberInfo;
                }
            }

            /// <summary>
            /// The Institution item.
            /// </summary>
            [RepositoryItem("7b8df25f-07d3-4245-b3cb-179ede2ca17d")]
            public virtual Ranorex.ComboBox Institution
            {
                get
                {
                    return _institutionInfo.CreateAdapter<Ranorex.ComboBox>(true);
                }
            }

            /// <summary>
            /// The Institution item info.
            /// </summary>
            [RepositoryItemInfo("7b8df25f-07d3-4245-b3cb-179ede2ca17d")]
            public virtual RepoItemInfo InstitutionInfo
            {
                get
                {
                    return _institutionInfo;
                }
            }

            /// <summary>
            /// The BranchName item.
            /// </summary>
            [RepositoryItem("4f832460-e0c5-44f6-8303-4148918037dc")]
            public virtual Ranorex.Text BranchName
            {
                get
                {
                    return _branchnameInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The BranchName item info.
            /// </summary>
            [RepositoryItemInfo("4f832460-e0c5-44f6-8303-4148918037dc")]
            public virtual RepoItemInfo BranchNameInfo
            {
                get
                {
                    return _branchnameInfo;
                }
            }

            /// <summary>
            /// The TransitNumber item.
            /// </summary>
            [RepositoryItem("4ec4f454-4186-4d44-95f5-6696ad6ce916")]
            public virtual Ranorex.Text TransitNumber
            {
                get
                {
                    return _transitnumberInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The TransitNumber item info.
            /// </summary>
            [RepositoryItemInfo("4ec4f454-4186-4d44-95f5-6696ad6ce916")]
            public virtual RepoItemInfo TransitNumberInfo
            {
                get
                {
                    return _transitnumberInfo;
                }
            }

            /// <summary>
            /// The BankAccountNumber item.
            /// </summary>
            [RepositoryItem("9be77f97-05e7-4ce1-a9b6-af7e9d288c42")]
            public virtual Ranorex.Text BankAccountNumber
            {
                get
                {
                    return _bankaccountnumberInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The BankAccountNumber item info.
            /// </summary>
            [RepositoryItemInfo("9be77f97-05e7-4ce1-a9b6-af7e9d288c42")]
            public virtual RepoItemInfo BankAccountNumberInfo
            {
                get
                {
                    return _bankaccountnumberInfo;
                }
            }

            /// <summary>
            /// The BankAccountType item.
            /// </summary>
            [RepositoryItem("457982e1-8eec-449c-aaa6-98b4ab6fcc11")]
            public virtual Ranorex.ComboBox BankAccountType
            {
                get
                {
                    return _bankaccounttypeInfo.CreateAdapter<Ranorex.ComboBox>(true);
                }
            }

            /// <summary>
            /// The BankAccountType item info.
            /// </summary>
            [RepositoryItemInfo("457982e1-8eec-449c-aaa6-98b4ab6fcc11")]
            public virtual RepoItemInfo BankAccountTypeInfo
            {
                get
                {
                    return _bankaccounttypeInfo;
                }
            }

            /// <summary>
            /// The UseForOnline item.
            /// </summary>
            [RepositoryItem("7c360b89-4d7b-416b-834c-1c80cda7bbaf")]
            public virtual Ranorex.CheckBox UseForOnline
            {
                get
                {
                    return _useforonlineInfo.CreateAdapter<Ranorex.CheckBox>(true);
                }
            }

            /// <summary>
            /// The UseForOnline item info.
            /// </summary>
            [RepositoryItemInfo("7c360b89-4d7b-416b-834c-1c80cda7bbaf")]
            public virtual RepoItemInfo UseForOnlineInfo
            {
                get
                {
                    return _useforonlineInfo;
                }
            }

            /// <summary>
            /// The HomePage item.
            /// </summary>
            [RepositoryItem("c24c44c5-d31a-451e-a177-f5683a2a34cd")]
            public virtual Ranorex.Text HomePage
            {
                get
                {
                    return _homepageInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The HomePage item info.
            /// </summary>
            [RepositoryItemInfo("c24c44c5-d31a-451e-a177-f5683a2a34cd")]
            public virtual RepoItemInfo HomePageInfo
            {
                get
                {
                    return _homepageInfo;
                }
            }

            /// <summary>
            /// The OnlineLogin item.
            /// </summary>
            [RepositoryItem("4110c678-1395-4b9e-8b5b-8ddc1f2c259f")]
            public virtual Ranorex.Text OnlineLogin
            {
                get
                {
                    return _onlineloginInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The OnlineLogin item info.
            /// </summary>
            [RepositoryItemInfo("4110c678-1395-4b9e-8b5b-8ddc1f2c259f")]
            public virtual RepoItemInfo OnlineLoginInfo
            {
                get
                {
                    return _onlineloginInfo;
                }
            }
        }

        /// <summary>
        /// The BudgetFolder folder.
        /// </summary>
        [RepositoryFolder("ac2aa78f-b329-4447-a803-bbd51775cb24")]
        public partial class BudgetFolder : RepoGenBaseFolder
        {
            RepoItemInfo _tabInfo;
            RepoItemInfo _budgetthisaccountInfo;

            /// <summary>
            /// Creates a new Budget  folder.
            /// </summary>
            public BudgetFolder(RepoGenBaseFolder parentFolder) :
                    base("Budget", "", parentFolder, 500, null, false, "ac2aa78f-b329-4447-a803-bbd51775cb24", "")
            {
                _tabInfo = new RepoItemInfo(this, "Tab", "?/?/tabpage[@title='Budget']", 3000, null, "0556dbce-d752-4e03-be5b-8b68bdc0af97");
                _budgetthisaccountInfo = new RepoItemInfo(this, "BudgetThisAccount", "checkbox[@controlid='70']", 3000, null, "544fed2d-e07f-4550-a546-99587f928c18");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("ac2aa78f-b329-4447-a803-bbd51775cb24")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("ac2aa78f-b329-4447-a803-bbd51775cb24")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The Tab item.
            /// </summary>
            [RepositoryItem("0556dbce-d752-4e03-be5b-8b68bdc0af97")]
            public virtual Ranorex.TabPage Tab
            {
                get
                {
                    return _tabInfo.CreateAdapter<Ranorex.TabPage>(true);
                }
            }

            /// <summary>
            /// The Tab item info.
            /// </summary>
            [RepositoryItemInfo("0556dbce-d752-4e03-be5b-8b68bdc0af97")]
            public virtual RepoItemInfo TabInfo
            {
                get
                {
                    return _tabInfo;
                }
            }

            /// <summary>
            /// The BudgetThisAccount item.
            /// </summary>
            [RepositoryItem("544fed2d-e07f-4550-a546-99587f928c18")]
            public virtual Ranorex.CheckBox BudgetThisAccount
            {
                get
                {
                    return _budgetthisaccountInfo.CreateAdapter<Ranorex.CheckBox>(true);
                }
            }

            /// <summary>
            /// The BudgetThisAccount item info.
            /// </summary>
            [RepositoryItemInfo("544fed2d-e07f-4550-a546-99587f928c18")]
            public virtual RepoItemInfo BudgetThisAccountInfo
            {
                get
                {
                    return _budgetthisaccountInfo;
                }
            }
        }

        /// <summary>
        /// The AdditionalInfoFolder folder.
        /// </summary>
        [RepositoryFolder("895aaf07-026f-4df9-9a3c-d1fe16098dd7")]
        public partial class AdditionalInfoFolder : RepoGenBaseFolder
        {
            RepoItemInfo _tabInfo;
            RepoItemInfo _additional1Info;
            RepoItemInfo _additional2Info;
            RepoItemInfo _additional3Info;
            RepoItemInfo _additional4Info;
            RepoItemInfo _additional5Info;

            /// <summary>
            /// Creates a new AdditionalInfo  folder.
            /// </summary>
            public AdditionalInfoFolder(RepoGenBaseFolder parentFolder) :
                    base("AdditionalInfo", "", parentFolder, 500, null, false, "895aaf07-026f-4df9-9a3c-d1fe16098dd7", "")
            {
                _tabInfo = new RepoItemInfo(this, "Tab", "?/?/tabpage[@title='Additional Info']", 3000, null, "0d582956-c52a-4f85-a4a5-c5bbabdea8d1");
                _additional1Info = new RepoItemInfo(this, "Additional1", "element[@controlid='805']/text", 3000, null, "44ba1b91-75dd-4f6d-a995-c15ffd2e7ade");
                _additional2Info = new RepoItemInfo(this, "Additional2", "element[@controlid='806']/text", 3000, null, "055a0c4f-7a0a-4287-a901-ea239a4a485c");
                _additional3Info = new RepoItemInfo(this, "Additional3", "element[@controlid='807']/text", 3000, null, "34b6407e-7dc3-4602-899c-d5d9a274c203");
                _additional4Info = new RepoItemInfo(this, "Additional4", "element[@controlid='808']/text", 3000, null, "f2eacc0c-aceb-4c8a-a1f7-4f38462143f0");
                _additional5Info = new RepoItemInfo(this, "Additional5", "element[@controlid='809']/text", 3000, null, "5f6f4b20-070a-4fde-bf45-823a91787f3a");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("895aaf07-026f-4df9-9a3c-d1fe16098dd7")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("895aaf07-026f-4df9-9a3c-d1fe16098dd7")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The Tab item.
            /// </summary>
            [RepositoryItem("0d582956-c52a-4f85-a4a5-c5bbabdea8d1")]
            public virtual Ranorex.TabPage Tab
            {
                get
                {
                    return _tabInfo.CreateAdapter<Ranorex.TabPage>(true);
                }
            }

            /// <summary>
            /// The Tab item info.
            /// </summary>
            [RepositoryItemInfo("0d582956-c52a-4f85-a4a5-c5bbabdea8d1")]
            public virtual RepoItemInfo TabInfo
            {
                get
                {
                    return _tabInfo;
                }
            }

            /// <summary>
            /// The Additional1 item.
            /// </summary>
            [RepositoryItem("44ba1b91-75dd-4f6d-a995-c15ffd2e7ade")]
            public virtual Ranorex.Text Additional1
            {
                get
                {
                    return _additional1Info.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The Additional1 item info.
            /// </summary>
            [RepositoryItemInfo("44ba1b91-75dd-4f6d-a995-c15ffd2e7ade")]
            public virtual RepoItemInfo Additional1Info
            {
                get
                {
                    return _additional1Info;
                }
            }

            /// <summary>
            /// The Additional2 item.
            /// </summary>
            [RepositoryItem("055a0c4f-7a0a-4287-a901-ea239a4a485c")]
            public virtual Ranorex.Text Additional2
            {
                get
                {
                    return _additional2Info.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The Additional2 item info.
            /// </summary>
            [RepositoryItemInfo("055a0c4f-7a0a-4287-a901-ea239a4a485c")]
            public virtual RepoItemInfo Additional2Info
            {
                get
                {
                    return _additional2Info;
                }
            }

            /// <summary>
            /// The Additional3 item.
            /// </summary>
            [RepositoryItem("34b6407e-7dc3-4602-899c-d5d9a274c203")]
            public virtual Ranorex.Text Additional3
            {
                get
                {
                    return _additional3Info.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The Additional3 item info.
            /// </summary>
            [RepositoryItemInfo("34b6407e-7dc3-4602-899c-d5d9a274c203")]
            public virtual RepoItemInfo Additional3Info
            {
                get
                {
                    return _additional3Info;
                }
            }

            /// <summary>
            /// The Additional4 item.
            /// </summary>
            [RepositoryItem("f2eacc0c-aceb-4c8a-a1f7-4f38462143f0")]
            public virtual Ranorex.Text Additional4
            {
                get
                {
                    return _additional4Info.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The Additional4 item info.
            /// </summary>
            [RepositoryItemInfo("f2eacc0c-aceb-4c8a-a1f7-4f38462143f0")]
            public virtual RepoItemInfo Additional4Info
            {
                get
                {
                    return _additional4Info;
                }
            }

            /// <summary>
            /// The Additional5 item.
            /// </summary>
            [RepositoryItem("5f6f4b20-070a-4fde-bf45-823a91787f3a")]
            public virtual Ranorex.Text Additional5
            {
                get
                {
                    return _additional5Info.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The Additional5 item info.
            /// </summary>
            [RepositoryItemInfo("5f6f4b20-070a-4fde-bf45-823a91787f3a")]
            public virtual RepoItemInfo Additional5Info
            {
                get
                {
                    return _additional5Info;
                }
            }
        }

        /// <summary>
        /// The WindowsTaskManagerAppFolder folder.
        /// </summary>
        [RepositoryFolder("7804c55e-d08f-41df-944a-7ce260c12155")]
        public partial class WindowsTaskManagerAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _closeInfo;

            /// <summary>
            /// Creates a new WindowsTaskManager  folder.
            /// </summary>
            public WindowsTaskManagerAppFolder(RepoGenBaseFolder parentFolder) :
                    base("WindowsTaskManager", "/form[@title='Windows Task Manager']", parentFolder, 3000, null, true, "7804c55e-d08f-41df-944a-7ce260c12155", "")
            {
                _closeInfo = new RepoItemInfo(this, "Close", "?/?/button[@accessiblename='Close']", 3000, null, "a11ce448-2821-4eb4-aa95-4fb8fe2eef1b");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("7804c55e-d08f-41df-944a-7ce260c12155")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("7804c55e-d08f-41df-944a-7ce260c12155")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The Close item.
            /// </summary>
            [RepositoryItem("a11ce448-2821-4eb4-aa95-4fb8fe2eef1b")]
            public virtual Ranorex.Button Close
            {
                get
                {
                    return _closeInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The Close item info.
            /// </summary>
            [RepositoryItemInfo("a11ce448-2821-4eb4-aa95-4fb8fe2eef1b")]
            public virtual RepoItemInfo CloseInfo
            {
                get
                {
                    return _closeInfo;
                }
            }
        }

        /// <summary>
        /// The EnterAccountNameAppFolder folder.
        /// </summary>
        [RepositoryFolder("8a1d7435-ea8d-4b04-a756-835dc86e5972")]
        public partial class EnterAccountNameAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _english1Info;
            RepoItemInfo _english2Info;
            RepoItemInfo _okInfo;
            RepoItemInfo _cancelInfo;

            /// <summary>
            /// Creates a new EnterAccountName  folder.
            /// </summary>
            public EnterAccountNameAppFolder(RepoGenBaseFolder parentFolder) :
                    base("EnterAccountName", "/form[@title='Enter Account Name']", parentFolder, 3000, null, true, "8a1d7435-ea8d-4b04-a756-835dc86e5972", "")
            {
                _english1Info = new RepoItemInfo(this, "English1", "element[@controlid='101']/text", 3000, null, "ae8e2a77-b1d2-401b-b85c-f999f61bda68");
                _english2Info = new RepoItemInfo(this, "English2", "element[@controlid='103']/text", 3000, null, "8d16e9cc-48f6-4dde-8b35-2fd1a8e45329");
                _okInfo = new RepoItemInfo(this, "OK", "button[@text='&OK']", 3000, null, "ac7c7934-16ca-4985-8ea5-2c90a9fd8081");
                _cancelInfo = new RepoItemInfo(this, "Cancel", "button[@text='&Cancel']", 3000, null, "b4a1882e-976a-4d4b-887e-2315db6fe58c");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("8a1d7435-ea8d-4b04-a756-835dc86e5972")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("8a1d7435-ea8d-4b04-a756-835dc86e5972")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The English1 item.
            /// </summary>
            [RepositoryItem("ae8e2a77-b1d2-401b-b85c-f999f61bda68")]
            public virtual Ranorex.Text English1
            {
                get
                {
                    return _english1Info.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The English1 item info.
            /// </summary>
            [RepositoryItemInfo("ae8e2a77-b1d2-401b-b85c-f999f61bda68")]
            public virtual RepoItemInfo English1Info
            {
                get
                {
                    return _english1Info;
                }
            }

            /// <summary>
            /// The English2 item.
            /// </summary>
            [RepositoryItem("8d16e9cc-48f6-4dde-8b35-2fd1a8e45329")]
            public virtual Ranorex.Text English2
            {
                get
                {
                    return _english2Info.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The English2 item info.
            /// </summary>
            [RepositoryItemInfo("8d16e9cc-48f6-4dde-8b35-2fd1a8e45329")]
            public virtual RepoItemInfo English2Info
            {
                get
                {
                    return _english2Info;
                }
            }

            /// <summary>
            /// The OK item.
            /// </summary>
            [RepositoryItem("ac7c7934-16ca-4985-8ea5-2c90a9fd8081")]
            public virtual Ranorex.Button OK
            {
                get
                {
                    return _okInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The OK item info.
            /// </summary>
            [RepositoryItemInfo("ac7c7934-16ca-4985-8ea5-2c90a9fd8081")]
            public virtual RepoItemInfo OKInfo
            {
                get
                {
                    return _okInfo;
                }
            }

            /// <summary>
            /// The Cancel item.
            /// </summary>
            [RepositoryItem("b4a1882e-976a-4d4b-887e-2315db6fe58c")]
            public virtual Ranorex.Button Cancel
            {
                get
                {
                    return _cancelInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The Cancel item info.
            /// </summary>
            [RepositoryItemInfo("b4a1882e-976a-4d4b-887e-2315db6fe58c")]
            public virtual RepoItemInfo CancelInfo
            {
                get
                {
                    return _cancelInfo;
                }
            }
        }

        /// <summary>
        /// The GeneralIconAppFolder folder.
        /// </summary>
        [RepositoryFolder("575ceeff-b1a1-40ed-8947-76986849ed56")]
        public partial class GeneralIconAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _createnewInfo;

            /// <summary>
            /// Creates a new GeneralIcon  folder.
            /// </summary>
            public GeneralIconAppFolder(RepoGenBaseFolder parentFolder) :
                    base("GeneralIcon", "/form[@title='Accounts']", parentFolder, 3000, null, true, "575ceeff-b1a1-40ed-8947-76986849ed56", "")
            {
                _createnewInfo = new RepoItemInfo(this, "CreateNew", "?/?/toolbar[@class='ToolbarWindow32' and @instance='0']/button[@text='Create (Ctrl+N)']", 3000, null, "96f63a40-4942-40bf-ae69-63634dc7ff20");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("575ceeff-b1a1-40ed-8947-76986849ed56")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("575ceeff-b1a1-40ed-8947-76986849ed56")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The CreateNew item.
            /// </summary>
            [RepositoryItem("96f63a40-4942-40bf-ae69-63634dc7ff20")]
            public virtual Ranorex.Button CreateNew
            {
                get
                {
                    return _createnewInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The CreateNew item info.
            /// </summary>
            [RepositoryItemInfo("96f63a40-4942-40bf-ae69-63634dc7ff20")]
            public virtual RepoItemInfo CreateNewInfo
            {
                get
                {
                    return _createnewInfo;
                }
            }
        }

    }
#pragma warning restore 0436
}