///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Drawing;
using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace Sage50.Repository
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    /// The class representing the OpenCompanyRes element repository.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", "8.0")]
    [RepositoryFolder("4ed6691c-f40c-4b48-800c-5ebe4a320578")]
    public partial class OpenCompanyRes : RepoGenBaseFolder
    {
        static OpenCompanyRes instance = new OpenCompanyRes();
        OpenCompanyResFolders.OpenCompanyAppFolder _opencompany;

        /// <summary>
        /// Gets the singleton class instance representing the OpenCompanyRes element repository.
        /// </summary>
        [RepositoryFolder("4ed6691c-f40c-4b48-800c-5ebe4a320578")]
        public static OpenCompanyRes Instance
        {
            get { return instance; }
        }

        /// <summary>
        /// Repository class constructor.
        /// </summary>
        public OpenCompanyRes() 
            : base("OpenCompanyRes", "/", null, 0, false, "4ed6691c-f40c-4b48-800c-5ebe4a320578", ".\\RepositoryImages\\OpenCompanyRes4ed6691c.rximgres")
        {
            _opencompany = new OpenCompanyResFolders.OpenCompanyAppFolder(this);
        }

#region Variables

#endregion

        /// <summary>
        /// The Self item info.
        /// </summary>
        [RepositoryItemInfo("4ed6691c-f40c-4b48-800c-5ebe4a320578")]
        public virtual RepoItemInfo SelfInfo
        {
            get
            {
                return _selfInfo;
            }
        }

        /// <summary>
        /// The OpenCompany folder.
        /// </summary>
        [RepositoryFolder("320e6889-482c-47dd-9b6a-61b526440138")]
        public virtual OpenCompanyResFolders.OpenCompanyAppFolder OpenCompany
        {
            get { return _opencompany; }
        }
    }

    /// <summary>
    /// Inner folder classes.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", "8.0")]
    public partial class OpenCompanyResFolders
    {
        /// <summary>
        /// The OpenCompanyAppFolder folder.
        /// </summary>
        [RepositoryFolder("320e6889-482c-47dd-9b6a-61b526440138")]
        public partial class OpenCompanyAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _filenameInfo;
            RepoItemInfo _openInfo;

            /// <summary>
            /// Creates a new OpenCompany  folder.
            /// </summary>
            public OpenCompanyAppFolder(RepoGenBaseFolder parentFolder) :
                    base("OpenCompany", "/form[@title='Sage 50 - Open Company']", parentFolder, 3000, null, true, "320e6889-482c-47dd-9b6a-61b526440138", "")
            {
                _filenameInfo = new RepoItemInfo(this, "FileName", "?/?/text[@controlid='1148']", 3000, null, "97f00cb2-f1b8-4988-8009-edb6debfb78a");
                _openInfo = new RepoItemInfo(this, "Open", "button[@text='&Open']", 3000, null, "bac65eed-d4f7-4b80-8da6-5fe4fde0aeb4");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("320e6889-482c-47dd-9b6a-61b526440138")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("320e6889-482c-47dd-9b6a-61b526440138")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The FileName item.
            /// </summary>
            [RepositoryItem("97f00cb2-f1b8-4988-8009-edb6debfb78a")]
            public virtual Ranorex.Text FileName
            {
                get
                {
                    return _filenameInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The FileName item info.
            /// </summary>
            [RepositoryItemInfo("97f00cb2-f1b8-4988-8009-edb6debfb78a")]
            public virtual RepoItemInfo FileNameInfo
            {
                get
                {
                    return _filenameInfo;
                }
            }

            /// <summary>
            /// The Open item.
            /// </summary>
            [RepositoryItem("bac65eed-d4f7-4b80-8da6-5fe4fde0aeb4")]
            public virtual Ranorex.Button Open
            {
                get
                {
                    return _openInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The Open item info.
            /// </summary>
            [RepositoryItemInfo("bac65eed-d4f7-4b80-8da6-5fe4fde0aeb4")]
            public virtual RepoItemInfo OpenInfo
            {
                get
                {
                    return _openInfo;
                }
            }
        }

    }
#pragma warning restore 0436
}