///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Drawing;
using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace Sage50.Repository
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    /// The class representing the PaymentsJournalRes element repository.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", "8.0")]
    [RepositoryFolder("bf1ec14a-02a8-4f62-8da3-5aa29ce0b5fe")]
    public partial class PaymentsJournalRes : RepoGenBaseFolder
    {
        static PaymentsJournalRes instance = new PaymentsJournalRes();
        PaymentsJournalResFolders.PaymentsJournalAppFolder _paymentsjournal;
        PaymentsJournalResFolders.AddOnTheFlyAppFolder _addonthefly;
        PaymentsJournalResFolders.SelectRemittingFrequencyAppFolder _selectremittingfrequency;

        /// <summary>
        /// Gets the singleton class instance representing the PaymentsJournalRes element repository.
        /// </summary>
        [RepositoryFolder("bf1ec14a-02a8-4f62-8da3-5aa29ce0b5fe")]
        public static PaymentsJournalRes Instance
        {
            get { return instance; }
        }

        /// <summary>
        /// Repository class constructor.
        /// </summary>
        public PaymentsJournalRes() 
            : base("PaymentsJournalRes", "/", null, 0, false, "bf1ec14a-02a8-4f62-8da3-5aa29ce0b5fe", ".\\RepositoryImages\\PaymentsJournalResbf1ec14a.rximgres")
        {
            _paymentsjournal = new PaymentsJournalResFolders.PaymentsJournalAppFolder(this);
            _addonthefly = new PaymentsJournalResFolders.AddOnTheFlyAppFolder(this);
            _selectremittingfrequency = new PaymentsJournalResFolders.SelectRemittingFrequencyAppFolder(this);
        }

#region Variables

#endregion

        /// <summary>
        /// The Self item info.
        /// </summary>
        [RepositoryItemInfo("bf1ec14a-02a8-4f62-8da3-5aa29ce0b5fe")]
        public virtual RepoItemInfo SelfInfo
        {
            get
            {
                return _selfInfo;
            }
        }

        /// <summary>
        /// The PaymentsJournal folder.
        /// </summary>
        [RepositoryFolder("590674e5-1cf4-4ea3-96ec-ee763a1ef9cc")]
        public virtual PaymentsJournalResFolders.PaymentsJournalAppFolder PaymentsJournal
        {
            get { return _paymentsjournal; }
        }

        /// <summary>
        /// The AddOnTheFly folder.
        /// </summary>
        [RepositoryFolder("d8ed9446-fde2-48d0-b6e4-ca87d3a85ff1")]
        public virtual PaymentsJournalResFolders.AddOnTheFlyAppFolder AddOnTheFly
        {
            get { return _addonthefly; }
        }

        /// <summary>
        /// The SelectRemittingFrequency folder.
        /// </summary>
        [RepositoryFolder("8d8f0135-676a-4d6e-b64e-c49f78e28e90")]
        public virtual PaymentsJournalResFolders.SelectRemittingFrequencyAppFolder SelectRemittingFrequency
        {
            get { return _selectremittingfrequency; }
        }
    }

    /// <summary>
    /// Inner folder classes.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", "8.0")]
    public partial class PaymentsJournalResFolders
    {
        /// <summary>
        /// The PaymentsJournalAppFolder folder.
        /// </summary>
        [RepositoryFolder("590674e5-1cf4-4ea3-96ec-ee763a1ef9cc")]
        public partial class PaymentsJournalAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _chequenoInfo;
            RepoItemInfo _paymentdateInfo;
            RepoItemInfo _enddateInfo;
            RepoItemInfo _transactionInfo;
            RepoItemInfo _prepaymentreferencenoInfo;
            RepoItemInfo _prepaymentamountInfo;
            RepoItemInfo _enterprepaymentsInfo;
            RepoItemInfo _searchdialogInfo;
            RepoItemInfo _vendorname2Info;
            RepoItemInfo _vendornameInfo;
            RepoItemInfo _paidbyInfo;
            RepoItemInfo _paidfromInfo;
            RepoItemInfo _commentInfo;
            RepoItemInfo _directdepositnoInfo;
            RepoItemInfo _sourceInfo;
            RepoItemInfo _exchangerateInfo;
            RepoItemInfo _transcontainer_existingInfo;
            RepoItemInfo _postInfo;
            RepoItemInfo _additionalfeesandinterestInfo;
            RepoItemInfo _paymentamountInfo;
            RepoItemInfo _referenceInfo;
            RepoItemInfo _undocurrenttransactionInfo;
            RepoItemInfo _frequencybuttonInfo;
            RepoItemInfo _reverseInfo;
            RepoItemInfo _printInfo;
            RepoItemInfo _transcontainerInfo;
            RepoItemInfo _allocatetoprojectsInfo;

            /// <summary>
            /// Creates a new PaymentsJournal  folder.
            /// </summary>
            public PaymentsJournalAppFolder(RepoGenBaseFolder parentFolder) :
                    base("PaymentsJournal", "/form[@title='Payments Journal']", parentFolder, 3000, null, true, "590674e5-1cf4-4ea3-96ec-ee763a1ef9cc", "")
            {
                _chequenoInfo = new RepoItemInfo(this, "ChequeNo", "text[@controlid='22']", 3000, null, "333b8a2e-c69d-4fd6-bc92-44edc9cf33f6");
                _paymentdateInfo = new RepoItemInfo(this, "PaymentDate", "element[@controlid='31']/text[@accessiblerole='Text']", 3000, null, "fb19c819-77a4-46fb-aafa-9a2284bf93ef");
                _enddateInfo = new RepoItemInfo(this, "EndDate", "element[@controlid='118']/text[@accessiblerole='Text']", 3000, null, "0af7e876-c6e1-434d-9ca8-66ad177bbcae");
                _transactionInfo = new RepoItemInfo(this, "Transaction", "combobox[@controlid='39']", 3000, null, "7e7c186d-265a-443f-87c6-038b01606937");
                _prepaymentreferencenoInfo = new RepoItemInfo(this, "PrepaymentReferenceNo", "text[@controlid='54']", 3000, null, "3ac81979-14ac-4c48-b4f1-27cc7795602f");
                _prepaymentamountInfo = new RepoItemInfo(this, "PrepaymentAmount", "element[@controlid='56']/text[@accessiblerole='Text']", 3000, null, "0c7e6c44-c4c8-437c-90a6-0ebafe1b2953");
                _enterprepaymentsInfo = new RepoItemInfo(this, "EnterPrepayments", "?/?/toolbar[@class='ToolbarWindow32' and @instance='0']/button[@text='Enter vendor prepayments']", 3000, null, "c533c95c-0314-41c8-adf8-a9495b853860");
                _searchdialogInfo = new RepoItemInfo(this, "SearchDialog", "?/?/toolbar[@class='ToolbarWindow32' and @instance='0']/button[@text='Adjust payment (Ctrl+A)']", 3000, null, "b5769298-9f95-41ce-a752-6b316a4622f9");
                _vendorname2Info = new RepoItemInfo(this, "VendorName2", "combobox[@controlid='52']", 3000, null, "5a64919b-6f31-44f5-861d-4937ca6847e6");
                _vendornameInfo = new RepoItemInfo(this, "VendorName", "?/?/text[@controlid='1001']", 3000, null, "11f810eb-0b3b-4594-979e-c9c4ea7ec3aa");
                _paidbyInfo = new RepoItemInfo(this, "PaidBy", "combobox[@controlid='49']", 3000, null, "2eac8b41-adf5-45c1-b157-e719d88c38b2");
                _paidfromInfo = new RepoItemInfo(this, "PaidFrom", "combobox[@controlid='51']", 3000, null, "d4cf96f3-f5ee-4ecd-96f8-bd4d659d86b7");
                _commentInfo = new RepoItemInfo(this, "Comment", "text[@controlid='62']", 3000, null, "bf9ec955-6ce7-4a95-9be8-2f54afa8ece9");
                _directdepositnoInfo = new RepoItemInfo(this, "DirectDepositNo", "text[@controlid='136']", 3000, null, "e11cf304-6ad9-48ea-b6a1-b0d48a9b47a9");
                _sourceInfo = new RepoItemInfo(this, "Source", "text[@controlid='23']", 3000, null, "caa72be6-7e42-48f2-9f69-9ac019ad1d4b");
                _exchangerateInfo = new RepoItemInfo(this, "ExchangeRate", "?/?/text[@accessiblename='Exchange Rate' and @accessiblerole='Text']", 3000, null, "c891d2c8-844f-44fc-9c87-135e44bfb691");
                _transcontainer_existingInfo = new RepoItemInfo(this, "TransContainer_existing", "element[@controlid='5012']/element[@class='CA_ContainerChild32']", 3000, null, "fda972a5-1213-4c7a-9ca6-116e02844c6a");
                _postInfo = new RepoItemInfo(this, "Post", "button[@controlid='106']", 3000, null, "3a319041-7fe0-477b-8549-07ee629cc4fc");
                _additionalfeesandinterestInfo = new RepoItemInfo(this, "AdditionalFeesAndInterest", "element[@controlid='46']/text[@accessiblerole='Text']", 3000, null, "ec089ab1-314c-4702-8586-b2062fbc9f7d");
                _paymentamountInfo = new RepoItemInfo(this, "PaymentAmount", "element[@controlid='44']/text[@accessiblerole='Text']", 3000, null, "354caf94-5c39-4451-b418-412052c3d831");
                _referenceInfo = new RepoItemInfo(this, "Reference", "text[@controlid='65']", 3000, null, "42e406b8-5c03-4c33-8979-bc912c1c235b");
                _undocurrenttransactionInfo = new RepoItemInfo(this, "UndoCurrentTransaction", "?/?/toolbar[@class='ToolbarWindow32' and @instance='0']/button[@text~'^Undo\\ current\\ transaction\\ ']", 3000, null, "640d57a1-c883-4e4a-b849-83d4d664a702");
                _frequencybuttonInfo = new RepoItemInfo(this, "FrequencyButton", "button[@controlid='139']", 3000, null, "f818073c-d670-4696-8875-41aae0ed66c6");
                _reverseInfo = new RepoItemInfo(this, "Reverse", "?/?/toolbar[@class='ToolbarWindow32' and @instance='0']/button[@text='Reverse payment']", 3000, null, "4ea74f9c-ad8b-452d-8b37-8f6f0fff34ed");
                _printInfo = new RepoItemInfo(this, "Print", "?/?/toolbar[@class='ToolbarWindow32' and @instance='1']/button[@text='Print (Ctrl+P)']", 3000, null, "0272bd83-f351-486f-94d6-ff78f31800b1");
                _transcontainerInfo = new RepoItemInfo(this, "TransContainer", "element[@controlid='5012']", 30000, null, "babe67a5-9bb4-4221-91f4-abd8095bd21d");
                _allocatetoprojectsInfo = new RepoItemInfo(this, "AllocateToProjects", "?/?/toolbar[@class='ToolbarWindow32' and @instance='1']/button[@text~'^Allocate\\ revenues\\ and\\ exp']", 30000, null, "38180edb-f84e-4c12-b27e-04f78beb5428");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("590674e5-1cf4-4ea3-96ec-ee763a1ef9cc")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("590674e5-1cf4-4ea3-96ec-ee763a1ef9cc")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The ChequeNo item.
            /// </summary>
            [RepositoryItem("333b8a2e-c69d-4fd6-bc92-44edc9cf33f6")]
            public virtual Ranorex.Text ChequeNo
            {
                get
                {
                    return _chequenoInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The ChequeNo item info.
            /// </summary>
            [RepositoryItemInfo("333b8a2e-c69d-4fd6-bc92-44edc9cf33f6")]
            public virtual RepoItemInfo ChequeNoInfo
            {
                get
                {
                    return _chequenoInfo;
                }
            }

            /// <summary>
            /// The PaymentDate item.
            /// </summary>
            [RepositoryItem("fb19c819-77a4-46fb-aafa-9a2284bf93ef")]
            public virtual Ranorex.Text PaymentDate
            {
                get
                {
                    return _paymentdateInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The PaymentDate item info.
            /// </summary>
            [RepositoryItemInfo("fb19c819-77a4-46fb-aafa-9a2284bf93ef")]
            public virtual RepoItemInfo PaymentDateInfo
            {
                get
                {
                    return _paymentdateInfo;
                }
            }

            /// <summary>
            /// The EndDate item.
            /// </summary>
            [RepositoryItem("0af7e876-c6e1-434d-9ca8-66ad177bbcae")]
            public virtual Ranorex.Text EndDate
            {
                get
                {
                    return _enddateInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The EndDate item info.
            /// </summary>
            [RepositoryItemInfo("0af7e876-c6e1-434d-9ca8-66ad177bbcae")]
            public virtual RepoItemInfo EndDateInfo
            {
                get
                {
                    return _enddateInfo;
                }
            }

            /// <summary>
            /// The Transaction item.
            /// </summary>
            [RepositoryItem("7e7c186d-265a-443f-87c6-038b01606937")]
            public virtual Ranorex.ComboBox Transaction
            {
                get
                {
                    return _transactionInfo.CreateAdapter<Ranorex.ComboBox>(true);
                }
            }

            /// <summary>
            /// The Transaction item info.
            /// </summary>
            [RepositoryItemInfo("7e7c186d-265a-443f-87c6-038b01606937")]
            public virtual RepoItemInfo TransactionInfo
            {
                get
                {
                    return _transactionInfo;
                }
            }

            /// <summary>
            /// The PrepaymentReferenceNo item.
            /// </summary>
            [RepositoryItem("3ac81979-14ac-4c48-b4f1-27cc7795602f")]
            public virtual Ranorex.Text PrepaymentReferenceNo
            {
                get
                {
                    return _prepaymentreferencenoInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The PrepaymentReferenceNo item info.
            /// </summary>
            [RepositoryItemInfo("3ac81979-14ac-4c48-b4f1-27cc7795602f")]
            public virtual RepoItemInfo PrepaymentReferenceNoInfo
            {
                get
                {
                    return _prepaymentreferencenoInfo;
                }
            }

            /// <summary>
            /// The PrepaymentAmount item.
            /// </summary>
            [RepositoryItem("0c7e6c44-c4c8-437c-90a6-0ebafe1b2953")]
            public virtual Ranorex.Text PrepaymentAmount
            {
                get
                {
                    return _prepaymentamountInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The PrepaymentAmount item info.
            /// </summary>
            [RepositoryItemInfo("0c7e6c44-c4c8-437c-90a6-0ebafe1b2953")]
            public virtual RepoItemInfo PrepaymentAmountInfo
            {
                get
                {
                    return _prepaymentamountInfo;
                }
            }

            /// <summary>
            /// The EnterPrepayments item.
            /// </summary>
            [RepositoryItem("c533c95c-0314-41c8-adf8-a9495b853860")]
            public virtual Ranorex.Button EnterPrepayments
            {
                get
                {
                    return _enterprepaymentsInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The EnterPrepayments item info.
            /// </summary>
            [RepositoryItemInfo("c533c95c-0314-41c8-adf8-a9495b853860")]
            public virtual RepoItemInfo EnterPrepaymentsInfo
            {
                get
                {
                    return _enterprepaymentsInfo;
                }
            }

            /// <summary>
            /// The SearchDialog item.
            /// </summary>
            [RepositoryItem("b5769298-9f95-41ce-a752-6b316a4622f9")]
            public virtual Ranorex.Button SearchDialog
            {
                get
                {
                    return _searchdialogInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The SearchDialog item info.
            /// </summary>
            [RepositoryItemInfo("b5769298-9f95-41ce-a752-6b316a4622f9")]
            public virtual RepoItemInfo SearchDialogInfo
            {
                get
                {
                    return _searchdialogInfo;
                }
            }

            /// <summary>
            /// The VendorName2 item.
            /// </summary>
            [RepositoryItem("5a64919b-6f31-44f5-861d-4937ca6847e6")]
            public virtual Ranorex.ComboBox VendorName2
            {
                get
                {
                    return _vendorname2Info.CreateAdapter<Ranorex.ComboBox>(true);
                }
            }

            /// <summary>
            /// The VendorName2 item info.
            /// </summary>
            [RepositoryItemInfo("5a64919b-6f31-44f5-861d-4937ca6847e6")]
            public virtual RepoItemInfo VendorName2Info
            {
                get
                {
                    return _vendorname2Info;
                }
            }

            /// <summary>
            /// The VendorName item.
            /// </summary>
            [RepositoryItem("11f810eb-0b3b-4594-979e-c9c4ea7ec3aa")]
            public virtual Ranorex.Text VendorName
            {
                get
                {
                    return _vendornameInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The VendorName item info.
            /// </summary>
            [RepositoryItemInfo("11f810eb-0b3b-4594-979e-c9c4ea7ec3aa")]
            public virtual RepoItemInfo VendorNameInfo
            {
                get
                {
                    return _vendornameInfo;
                }
            }

            /// <summary>
            /// The PaidBy item.
            /// </summary>
            [RepositoryItem("2eac8b41-adf5-45c1-b157-e719d88c38b2")]
            public virtual Ranorex.ComboBox PaidBy
            {
                get
                {
                    return _paidbyInfo.CreateAdapter<Ranorex.ComboBox>(true);
                }
            }

            /// <summary>
            /// The PaidBy item info.
            /// </summary>
            [RepositoryItemInfo("2eac8b41-adf5-45c1-b157-e719d88c38b2")]
            public virtual RepoItemInfo PaidByInfo
            {
                get
                {
                    return _paidbyInfo;
                }
            }

            /// <summary>
            /// The PaidFrom item.
            /// </summary>
            [RepositoryItem("d4cf96f3-f5ee-4ecd-96f8-bd4d659d86b7")]
            public virtual Ranorex.ComboBox PaidFrom
            {
                get
                {
                    return _paidfromInfo.CreateAdapter<Ranorex.ComboBox>(true);
                }
            }

            /// <summary>
            /// The PaidFrom item info.
            /// </summary>
            [RepositoryItemInfo("d4cf96f3-f5ee-4ecd-96f8-bd4d659d86b7")]
            public virtual RepoItemInfo PaidFromInfo
            {
                get
                {
                    return _paidfromInfo;
                }
            }

            /// <summary>
            /// The Comment item.
            /// </summary>
            [RepositoryItem("bf9ec955-6ce7-4a95-9be8-2f54afa8ece9")]
            public virtual Ranorex.Text Comment
            {
                get
                {
                    return _commentInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The Comment item info.
            /// </summary>
            [RepositoryItemInfo("bf9ec955-6ce7-4a95-9be8-2f54afa8ece9")]
            public virtual RepoItemInfo CommentInfo
            {
                get
                {
                    return _commentInfo;
                }
            }

            /// <summary>
            /// The DirectDepositNo item.
            /// </summary>
            [RepositoryItem("e11cf304-6ad9-48ea-b6a1-b0d48a9b47a9")]
            public virtual Ranorex.Text DirectDepositNo
            {
                get
                {
                    return _directdepositnoInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The DirectDepositNo item info.
            /// </summary>
            [RepositoryItemInfo("e11cf304-6ad9-48ea-b6a1-b0d48a9b47a9")]
            public virtual RepoItemInfo DirectDepositNoInfo
            {
                get
                {
                    return _directdepositnoInfo;
                }
            }

            /// <summary>
            /// The Source item.
            /// </summary>
            [RepositoryItem("caa72be6-7e42-48f2-9f69-9ac019ad1d4b")]
            public virtual Ranorex.Text Source
            {
                get
                {
                    return _sourceInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The Source item info.
            /// </summary>
            [RepositoryItemInfo("caa72be6-7e42-48f2-9f69-9ac019ad1d4b")]
            public virtual RepoItemInfo SourceInfo
            {
                get
                {
                    return _sourceInfo;
                }
            }

            /// <summary>
            /// The ExchangeRate item.
            /// </summary>
            [RepositoryItem("c891d2c8-844f-44fc-9c87-135e44bfb691")]
            public virtual Ranorex.Text ExchangeRate
            {
                get
                {
                    return _exchangerateInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The ExchangeRate item info.
            /// </summary>
            [RepositoryItemInfo("c891d2c8-844f-44fc-9c87-135e44bfb691")]
            public virtual RepoItemInfo ExchangeRateInfo
            {
                get
                {
                    return _exchangerateInfo;
                }
            }

            /// <summary>
            /// The TransContainer_existing item.
            /// </summary>
            [RepositoryItem("fda972a5-1213-4c7a-9ca6-116e02844c6a")]
            public virtual Ranorex.Unknown TransContainer_existing
            {
                get
                {
                    return _transcontainer_existingInfo.CreateAdapter<Ranorex.Unknown>(true);
                }
            }

            /// <summary>
            /// The TransContainer_existing item info.
            /// </summary>
            [RepositoryItemInfo("fda972a5-1213-4c7a-9ca6-116e02844c6a")]
            public virtual RepoItemInfo TransContainer_existingInfo
            {
                get
                {
                    return _transcontainer_existingInfo;
                }
            }

            /// <summary>
            /// The Post item.
            /// </summary>
            [RepositoryItem("3a319041-7fe0-477b-8549-07ee629cc4fc")]
            public virtual Ranorex.Button Post
            {
                get
                {
                    return _postInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The Post item info.
            /// </summary>
            [RepositoryItemInfo("3a319041-7fe0-477b-8549-07ee629cc4fc")]
            public virtual RepoItemInfo PostInfo
            {
                get
                {
                    return _postInfo;
                }
            }

            /// <summary>
            /// The AdditionalFeesAndInterest item.
            /// </summary>
            [RepositoryItem("ec089ab1-314c-4702-8586-b2062fbc9f7d")]
            public virtual Ranorex.Text AdditionalFeesAndInterest
            {
                get
                {
                    return _additionalfeesandinterestInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The AdditionalFeesAndInterest item info.
            /// </summary>
            [RepositoryItemInfo("ec089ab1-314c-4702-8586-b2062fbc9f7d")]
            public virtual RepoItemInfo AdditionalFeesAndInterestInfo
            {
                get
                {
                    return _additionalfeesandinterestInfo;
                }
            }

            /// <summary>
            /// The PaymentAmount item.
            /// </summary>
            [RepositoryItem("354caf94-5c39-4451-b418-412052c3d831")]
            public virtual Ranorex.Text PaymentAmount
            {
                get
                {
                    return _paymentamountInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The PaymentAmount item info.
            /// </summary>
            [RepositoryItemInfo("354caf94-5c39-4451-b418-412052c3d831")]
            public virtual RepoItemInfo PaymentAmountInfo
            {
                get
                {
                    return _paymentamountInfo;
                }
            }

            /// <summary>
            /// The Reference item.
            /// </summary>
            [RepositoryItem("42e406b8-5c03-4c33-8979-bc912c1c235b")]
            public virtual Ranorex.Text Reference
            {
                get
                {
                    return _referenceInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The Reference item info.
            /// </summary>
            [RepositoryItemInfo("42e406b8-5c03-4c33-8979-bc912c1c235b")]
            public virtual RepoItemInfo ReferenceInfo
            {
                get
                {
                    return _referenceInfo;
                }
            }

            /// <summary>
            /// The UndoCurrentTransaction item.
            /// </summary>
            [RepositoryItem("640d57a1-c883-4e4a-b849-83d4d664a702")]
            public virtual Ranorex.Button UndoCurrentTransaction
            {
                get
                {
                    return _undocurrenttransactionInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The UndoCurrentTransaction item info.
            /// </summary>
            [RepositoryItemInfo("640d57a1-c883-4e4a-b849-83d4d664a702")]
            public virtual RepoItemInfo UndoCurrentTransactionInfo
            {
                get
                {
                    return _undocurrenttransactionInfo;
                }
            }

            /// <summary>
            /// The FrequencyButton item.
            /// </summary>
            [RepositoryItem("f818073c-d670-4696-8875-41aae0ed66c6")]
            public virtual Ranorex.Button FrequencyButton
            {
                get
                {
                    return _frequencybuttonInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The FrequencyButton item info.
            /// </summary>
            [RepositoryItemInfo("f818073c-d670-4696-8875-41aae0ed66c6")]
            public virtual RepoItemInfo FrequencyButtonInfo
            {
                get
                {
                    return _frequencybuttonInfo;
                }
            }

            /// <summary>
            /// The Reverse item.
            /// </summary>
            [RepositoryItem("4ea74f9c-ad8b-452d-8b37-8f6f0fff34ed")]
            public virtual Ranorex.Button Reverse
            {
                get
                {
                    return _reverseInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The Reverse item info.
            /// </summary>
            [RepositoryItemInfo("4ea74f9c-ad8b-452d-8b37-8f6f0fff34ed")]
            public virtual RepoItemInfo ReverseInfo
            {
                get
                {
                    return _reverseInfo;
                }
            }

            /// <summary>
            /// The Print item.
            /// </summary>
            [RepositoryItem("0272bd83-f351-486f-94d6-ff78f31800b1")]
            public virtual Ranorex.Button Print
            {
                get
                {
                    return _printInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The Print item info.
            /// </summary>
            [RepositoryItemInfo("0272bd83-f351-486f-94d6-ff78f31800b1")]
            public virtual RepoItemInfo PrintInfo
            {
                get
                {
                    return _printInfo;
                }
            }

            /// <summary>
            /// The TransContainer item.
            /// </summary>
            [RepositoryItem("babe67a5-9bb4-4221-91f4-abd8095bd21d")]
            public virtual Ranorex.Unknown TransContainer
            {
                get
                {
                    return _transcontainerInfo.CreateAdapter<Ranorex.Unknown>(true);
                }
            }

            /// <summary>
            /// The TransContainer item info.
            /// </summary>
            [RepositoryItemInfo("babe67a5-9bb4-4221-91f4-abd8095bd21d")]
            public virtual RepoItemInfo TransContainerInfo
            {
                get
                {
                    return _transcontainerInfo;
                }
            }

            /// <summary>
            /// The AllocateToProjects item.
            /// </summary>
            [RepositoryItem("38180edb-f84e-4c12-b27e-04f78beb5428")]
            public virtual Ranorex.Button AllocateToProjects
            {
                get
                {
                    return _allocatetoprojectsInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The AllocateToProjects item info.
            /// </summary>
            [RepositoryItemInfo("38180edb-f84e-4c12-b27e-04f78beb5428")]
            public virtual RepoItemInfo AllocateToProjectsInfo
            {
                get
                {
                    return _allocatetoprojectsInfo;
                }
            }
        }

        /// <summary>
        /// The AddOnTheFlyAppFolder folder.
        /// </summary>
        [RepositoryFolder("d8ed9446-fde2-48d0-b6e4-ca87d3a85ff1")]
        public partial class AddOnTheFlyAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _quickaddInfo;

            /// <summary>
            /// Creates a new AddOnTheFly  folder.
            /// </summary>
            public AddOnTheFlyAppFolder(RepoGenBaseFolder parentFolder) :
                    base("AddOnTheFly", "/form[@title='Sage 50']", parentFolder, 3000, null, true, "d8ed9446-fde2-48d0-b6e4-ca87d3a85ff1", "")
            {
                _quickaddInfo = new RepoItemInfo(this, "QuickAdd", "button[@text='&Quick Add']", 3000, null, "5df6466e-8c1a-4843-8eb5-0ecbfac21820");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("d8ed9446-fde2-48d0-b6e4-ca87d3a85ff1")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("d8ed9446-fde2-48d0-b6e4-ca87d3a85ff1")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The QuickAdd item.
            /// </summary>
            [RepositoryItem("5df6466e-8c1a-4843-8eb5-0ecbfac21820")]
            public virtual Ranorex.Button QuickAdd
            {
                get
                {
                    return _quickaddInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The QuickAdd item info.
            /// </summary>
            [RepositoryItemInfo("5df6466e-8c1a-4843-8eb5-0ecbfac21820")]
            public virtual RepoItemInfo QuickAddInfo
            {
                get
                {
                    return _quickaddInfo;
                }
            }
        }

        /// <summary>
        /// The SelectRemittingFrequencyAppFolder folder.
        /// </summary>
        [RepositoryFolder("8d8f0135-676a-4d6e-b64e-c49f78e28e90")]
        public partial class SelectRemittingFrequencyAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _frequencyInfo;
            RepoItemInfo _selectInfo;
            RepoItemInfo _cancelInfo;

            /// <summary>
            /// Creates a new SelectRemittingFrequency  folder.
            /// </summary>
            public SelectRemittingFrequencyAppFolder(RepoGenBaseFolder parentFolder) :
                    base("SelectRemittingFrequency", "/form[@title~'^Select\\ Remitting\\ Frequenc']", parentFolder, 3000, null, true, "8d8f0135-676a-4d6e-b64e-c49f78e28e90", "")
            {
                _frequencyInfo = new RepoItemInfo(this, "Frequency", "list[@controlid='20']", 3000, null, "9cfb6405-0df9-4bcb-a624-5ae89b8dcf36");
                _selectInfo = new RepoItemInfo(this, "Select", "button[@text='&Select']", 3000, null, "8f1b1081-ea7e-41f0-b281-57c515e07f77");
                _cancelInfo = new RepoItemInfo(this, "Cancel", "button[@text='&Cancel']", 3000, null, "e695a7d7-436a-4e61-a4e7-9cde64fb8935");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("8d8f0135-676a-4d6e-b64e-c49f78e28e90")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("8d8f0135-676a-4d6e-b64e-c49f78e28e90")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The Frequency item.
            /// </summary>
            [RepositoryItem("9cfb6405-0df9-4bcb-a624-5ae89b8dcf36")]
            public virtual Ranorex.List Frequency
            {
                get
                {
                    return _frequencyInfo.CreateAdapter<Ranorex.List>(true);
                }
            }

            /// <summary>
            /// The Frequency item info.
            /// </summary>
            [RepositoryItemInfo("9cfb6405-0df9-4bcb-a624-5ae89b8dcf36")]
            public virtual RepoItemInfo FrequencyInfo
            {
                get
                {
                    return _frequencyInfo;
                }
            }

            /// <summary>
            /// The Select item.
            /// </summary>
            [RepositoryItem("8f1b1081-ea7e-41f0-b281-57c515e07f77")]
            public virtual Ranorex.Button Select
            {
                get
                {
                    return _selectInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The Select item info.
            /// </summary>
            [RepositoryItemInfo("8f1b1081-ea7e-41f0-b281-57c515e07f77")]
            public virtual RepoItemInfo SelectInfo
            {
                get
                {
                    return _selectInfo;
                }
            }

            /// <summary>
            /// The Cancel item.
            /// </summary>
            [RepositoryItem("e695a7d7-436a-4e61-a4e7-9cde64fb8935")]
            public virtual Ranorex.Button Cancel
            {
                get
                {
                    return _cancelInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The Cancel item info.
            /// </summary>
            [RepositoryItemInfo("e695a7d7-436a-4e61-a4e7-9cde64fb8935")]
            public virtual RepoItemInfo CancelInfo
            {
                get
                {
                    return _cancelInfo;
                }
            }
        }

    }
#pragma warning restore 0436
}