///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Drawing;
using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace Sage50.Repository
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    /// The class representing the PayrollLedgerRes element repository.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", "8.0")]
    [RepositoryFolder("84a541e8-fb23-4eca-8e02-73008df3a3b0")]
    public partial class PayrollLedgerRes : RepoGenBaseFolder
    {
        static PayrollLedgerRes instance = new PayrollLedgerRes();
        PayrollLedgerResFolders.PayrollLedgerAppFolder _payrollledger;
        PayrollLedgerResFolders.EmployeeIconAppFolder _employeeicon;

        /// <summary>
        /// Gets the singleton class instance representing the PayrollLedgerRes element repository.
        /// </summary>
        [RepositoryFolder("84a541e8-fb23-4eca-8e02-73008df3a3b0")]
        public static PayrollLedgerRes Instance
        {
            get { return instance; }
        }

        /// <summary>
        /// Repository class constructor.
        /// </summary>
        public PayrollLedgerRes() 
            : base("PayrollLedgerRes", "/", null, 0, false, "84a541e8-fb23-4eca-8e02-73008df3a3b0", ".\\RepositoryImages\\PayrollLedgerRes84a541e8.rximgres")
        {
            _payrollledger = new PayrollLedgerResFolders.PayrollLedgerAppFolder(this);
            _employeeicon = new PayrollLedgerResFolders.EmployeeIconAppFolder(this);
        }

#region Variables

#endregion

        /// <summary>
        /// The Self item info.
        /// </summary>
        [RepositoryItemInfo("84a541e8-fb23-4eca-8e02-73008df3a3b0")]
        public virtual RepoItemInfo SelfInfo
        {
            get
            {
                return _selfInfo;
            }
        }

        /// <summary>
        /// The PayrollLedger folder.
        /// </summary>
        [RepositoryFolder("5505a981-65e8-43a0-948f-09d7edf401e5")]
        public virtual PayrollLedgerResFolders.PayrollLedgerAppFolder PayrollLedger
        {
            get { return _payrollledger; }
        }

        /// <summary>
        /// The EmployeeIcon folder.
        /// </summary>
        [RepositoryFolder("8a5ba7ff-d262-47dd-8a87-839e0b10025b")]
        public virtual PayrollLedgerResFolders.EmployeeIconAppFolder EmployeeIcon
        {
            get { return _employeeicon; }
        }
    }

    /// <summary>
    /// Inner folder classes.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", "8.0")]
    public partial class PayrollLedgerResFolders
    {
        /// <summary>
        /// The PayrollLedgerAppFolder folder.
        /// </summary>
        [RepositoryFolder("5505a981-65e8-43a0-948f-09d7edf401e5")]
        public partial class PayrollLedgerAppFolder : RepoGenBaseFolder
        {
            PayrollLedgerResFolders.PersonalFolder _personal;
            PayrollLedgerResFolders.TaxesFolder _taxes;
            PayrollLedgerResFolders.IncomeFolder _income;
            PayrollLedgerResFolders.DeductionsFolder _deductions;
            PayrollLedgerResFolders.WCBOtherExpFolder _wcbotherexp;
            PayrollLedgerResFolders.EntitlementsFolder _entitlements;
            PayrollLedgerResFolders.DirectDepositFolder _directdeposit;
            PayrollLedgerResFolders.MemoFolder _memo;
            PayrollLedgerResFolders.AdditionalInfoFolder _additionalinfo;
            PayrollLedgerResFolders.T4RL1Folder _t4rl1;
            RepoItemInfo _selectrecordInfo;
            RepoItemInfo _employeenameInfo;
            RepoItemInfo _createanewtoolbuttonInfo;
            RepoItemInfo _inactiveemployeeInfo;
            RepoItemInfo _removeInfo;
            RepoItemInfo _saveInfo;

            /// <summary>
            /// Creates a new PayrollLedger  folder.
            /// </summary>
            public PayrollLedgerAppFolder(RepoGenBaseFolder parentFolder) :
                    base("PayrollLedger", "/form[@title='Payroll Ledger']", parentFolder, 3000, null, true, "5505a981-65e8-43a0-948f-09d7edf401e5", "")
            {
                _personal = new PayrollLedgerResFolders.PersonalFolder(this);
                _taxes = new PayrollLedgerResFolders.TaxesFolder(this);
                _income = new PayrollLedgerResFolders.IncomeFolder(this);
                _deductions = new PayrollLedgerResFolders.DeductionsFolder(this);
                _wcbotherexp = new PayrollLedgerResFolders.WCBOtherExpFolder(this);
                _entitlements = new PayrollLedgerResFolders.EntitlementsFolder(this);
                _directdeposit = new PayrollLedgerResFolders.DirectDepositFolder(this);
                _memo = new PayrollLedgerResFolders.MemoFolder(this);
                _additionalinfo = new PayrollLedgerResFolders.AdditionalInfoFolder(this);
                _t4rl1 = new PayrollLedgerResFolders.T4RL1Folder(this);
                _selectrecordInfo = new RepoItemInfo(this, "SelectRecord", "?/?/toolbar[@class='ToolbarWindow32' and @instance='1']/combobox[@controlid='504']", 3000, null, "23e56fa8-6f3f-4424-ab5a-2602b17deee4");
                _employeenameInfo = new RepoItemInfo(this, "EmployeeName", "element[@controlid='22']/text", 3000, null, "f7641b5c-effe-4235-b451-7381fb9f704e");
                _createanewtoolbuttonInfo = new RepoItemInfo(this, "CreateANewToolButton", "?/?/toolbar[@class='ToolbarWindow32' and @instance='0']/button[@text~'^Create\\ a\\ new\\ employee\\ \\(Ct']", 3000, null, "42e1f49b-1765-480f-9a85-d8bc8032716f");
                _inactiveemployeeInfo = new RepoItemInfo(this, "InactiveEmployee", "checkbox[@text='&Inactive Employee']", 3000, null, "641217e7-b347-44f4-8b09-2927f8cd53e1");
                _removeInfo = new RepoItemInfo(this, "Remove", "?/?/toolbar[@class='ToolbarWindow32' and @instance='0']/button[@text~'^Remove\\ the\\ current\\ employ']", 3000, null, "629db734-eaac-442a-8475-60e78db1a7a9");
                _saveInfo = new RepoItemInfo(this, "Save", "?/?/toolbar[@class='ToolbarWindow32' and @instance='0']/button[@text~'^Save\\ the\\ current\\ employee']", 3000, null, "7f53168e-058f-410f-89e1-9cba21b8a8b3");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("5505a981-65e8-43a0-948f-09d7edf401e5")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("5505a981-65e8-43a0-948f-09d7edf401e5")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The SelectRecord item.
            /// </summary>
            [RepositoryItem("23e56fa8-6f3f-4424-ab5a-2602b17deee4")]
            public virtual Ranorex.ComboBox SelectRecord
            {
                get
                {
                    return _selectrecordInfo.CreateAdapter<Ranorex.ComboBox>(true);
                }
            }

            /// <summary>
            /// The SelectRecord item info.
            /// </summary>
            [RepositoryItemInfo("23e56fa8-6f3f-4424-ab5a-2602b17deee4")]
            public virtual RepoItemInfo SelectRecordInfo
            {
                get
                {
                    return _selectrecordInfo;
                }
            }

            /// <summary>
            /// The EmployeeName item.
            /// </summary>
            [RepositoryItem("f7641b5c-effe-4235-b451-7381fb9f704e")]
            public virtual Ranorex.Text EmployeeName
            {
                get
                {
                    return _employeenameInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The EmployeeName item info.
            /// </summary>
            [RepositoryItemInfo("f7641b5c-effe-4235-b451-7381fb9f704e")]
            public virtual RepoItemInfo EmployeeNameInfo
            {
                get
                {
                    return _employeenameInfo;
                }
            }

            /// <summary>
            /// The CreateANewToolButton item.
            /// </summary>
            [RepositoryItem("42e1f49b-1765-480f-9a85-d8bc8032716f")]
            public virtual Ranorex.Button CreateANewToolButton
            {
                get
                {
                    return _createanewtoolbuttonInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The CreateANewToolButton item info.
            /// </summary>
            [RepositoryItemInfo("42e1f49b-1765-480f-9a85-d8bc8032716f")]
            public virtual RepoItemInfo CreateANewToolButtonInfo
            {
                get
                {
                    return _createanewtoolbuttonInfo;
                }
            }

            /// <summary>
            /// The InactiveEmployee item.
            /// </summary>
            [RepositoryItem("641217e7-b347-44f4-8b09-2927f8cd53e1")]
            public virtual Ranorex.CheckBox InactiveEmployee
            {
                get
                {
                    return _inactiveemployeeInfo.CreateAdapter<Ranorex.CheckBox>(true);
                }
            }

            /// <summary>
            /// The InactiveEmployee item info.
            /// </summary>
            [RepositoryItemInfo("641217e7-b347-44f4-8b09-2927f8cd53e1")]
            public virtual RepoItemInfo InactiveEmployeeInfo
            {
                get
                {
                    return _inactiveemployeeInfo;
                }
            }

            /// <summary>
            /// The Remove item.
            /// </summary>
            [RepositoryItem("629db734-eaac-442a-8475-60e78db1a7a9")]
            public virtual Ranorex.Button Remove
            {
                get
                {
                    return _removeInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The Remove item info.
            /// </summary>
            [RepositoryItemInfo("629db734-eaac-442a-8475-60e78db1a7a9")]
            public virtual RepoItemInfo RemoveInfo
            {
                get
                {
                    return _removeInfo;
                }
            }

            /// <summary>
            /// The Save item.
            /// </summary>
            [RepositoryItem("7f53168e-058f-410f-89e1-9cba21b8a8b3")]
            public virtual Ranorex.Button Save
            {
                get
                {
                    return _saveInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The Save item info.
            /// </summary>
            [RepositoryItemInfo("7f53168e-058f-410f-89e1-9cba21b8a8b3")]
            public virtual RepoItemInfo SaveInfo
            {
                get
                {
                    return _saveInfo;
                }
            }

            /// <summary>
            /// The Personal folder.
            /// </summary>
            [RepositoryFolder("f4667627-40dd-411d-a3f2-21c4af3b62ee")]
            public virtual PayrollLedgerResFolders.PersonalFolder Personal
            {
                get { return _personal; }
            }

            /// <summary>
            /// The Taxes folder.
            /// </summary>
            [RepositoryFolder("7ea18317-1b0a-4237-b223-ae875f6ce9f7")]
            public virtual PayrollLedgerResFolders.TaxesFolder Taxes
            {
                get { return _taxes; }
            }

            /// <summary>
            /// The Income folder.
            /// </summary>
            [RepositoryFolder("21779d3e-ec47-4ea9-a778-8037db5dd7da")]
            public virtual PayrollLedgerResFolders.IncomeFolder Income
            {
                get { return _income; }
            }

            /// <summary>
            /// The Deductions folder.
            /// </summary>
            [RepositoryFolder("d33ade79-2ee2-493d-a75d-61d18c6d49e9")]
            public virtual PayrollLedgerResFolders.DeductionsFolder Deductions
            {
                get { return _deductions; }
            }

            /// <summary>
            /// The WCBOtherExp folder.
            /// </summary>
            [RepositoryFolder("78c4e4a8-0468-49de-a4d3-64df412d10cb")]
            public virtual PayrollLedgerResFolders.WCBOtherExpFolder WCBOtherExp
            {
                get { return _wcbotherexp; }
            }

            /// <summary>
            /// The Entitlements folder.
            /// </summary>
            [RepositoryFolder("e31890a3-9716-434d-ae84-7a15e35263c0")]
            public virtual PayrollLedgerResFolders.EntitlementsFolder Entitlements
            {
                get { return _entitlements; }
            }

            /// <summary>
            /// The DirectDeposit folder.
            /// </summary>
            [RepositoryFolder("dd0c479a-ab5b-4164-a385-f564f3d72d7f")]
            public virtual PayrollLedgerResFolders.DirectDepositFolder DirectDeposit
            {
                get { return _directdeposit; }
            }

            /// <summary>
            /// The Memo folder.
            /// </summary>
            [RepositoryFolder("44fad97c-c07c-432d-bb88-45dec1656c1d")]
            public virtual PayrollLedgerResFolders.MemoFolder Memo
            {
                get { return _memo; }
            }

            /// <summary>
            /// The AdditionalInfo folder.
            /// </summary>
            [RepositoryFolder("fe05f852-66a3-4533-a4ad-a2a7e9470256")]
            public virtual PayrollLedgerResFolders.AdditionalInfoFolder AdditionalInfo
            {
                get { return _additionalinfo; }
            }

            /// <summary>
            /// The T4RL1 folder.
            /// </summary>
            [RepositoryFolder("727f61b1-8179-4819-a8ed-d0b625612f18")]
            public virtual PayrollLedgerResFolders.T4RL1Folder T4RL1
            {
                get { return _t4rl1; }
            }
        }

        /// <summary>
        /// The PersonalFolder folder.
        /// </summary>
        [RepositoryFolder("f4667627-40dd-411d-a3f2-21c4af3b62ee")]
        public partial class PersonalFolder : RepoGenBaseFolder
        {
            RepoItemInfo _tabInfo;
            RepoItemInfo _street1Info;
            RepoItemInfo _street2Info;
            RepoItemInfo _cityInfo;
            RepoItemInfo _provinceInfo;
            RepoItemInfo _provincecodeInfo;
            RepoItemInfo _postalcodeInfo;
            RepoItemInfo _phone1Info;
            RepoItemInfo _phone2Info;
            RepoItemInfo _languagepreferenceInfo;
            RepoItemInfo _sinInfo;
            RepoItemInfo _birthdateInfo;
            RepoItemInfo _roecodeInfo;
            RepoItemInfo _hiredateInfo;
            RepoItemInfo _terminatedateInfo;
            RepoItemInfo _departmentInfo;
            RepoItemInfo _jobcategoryInfo;

            /// <summary>
            /// Creates a new Personal  folder.
            /// </summary>
            public PersonalFolder(RepoGenBaseFolder parentFolder) :
                    base("Personal", "", parentFolder, 1000, null, false, "f4667627-40dd-411d-a3f2-21c4af3b62ee", "")
            {
                _tabInfo = new RepoItemInfo(this, "Tab", "?/?/tabpage[@title='Personal']", 3000, null, "52afa08f-5f14-46a0-a1bb-b358b6dc54f4");
                _street1Info = new RepoItemInfo(this, "Street1", "element[@controlid='42']/text", 3000, null, "e0f1f66b-55c6-4353-ba5e-48babbbe3284");
                _street2Info = new RepoItemInfo(this, "Street2", "element[@controlid='43']/text", 3000, null, "1c3c8402-b137-468a-8836-8e8a01e8ab05");
                _cityInfo = new RepoItemInfo(this, "City", "element[@controlid='44']/text", 3000, null, "cad500d0-eb67-403d-b0b1-f49c03af3d67");
                _provinceInfo = new RepoItemInfo(this, "Province", "element[@controlid='45']/text", 3000, null, "22ef6bc0-2273-4be7-8a29-36326e4cfb56");
                _provincecodeInfo = new RepoItemInfo(this, "ProvinceCode", "combobox[@controlid='31']", 3000, null, "17fac9f7-0db6-4483-a58b-bf27f274faaf");
                _postalcodeInfo = new RepoItemInfo(this, "PostalCode", "element[@controlid='46']/text", 3000, null, "f1813c56-dbf3-4c1d-b55a-882bf27c117e");
                _phone1Info = new RepoItemInfo(this, "Phone1", "element[@controlid='47']/text", 3000, null, "6eec9afa-d361-44bf-b873-71cfe48f6f44");
                _phone2Info = new RepoItemInfo(this, "Phone2", "element[@controlid='48']/text", 3000, null, "af61d0ee-18cd-457f-8f4c-bae50f25f776");
                _languagepreferenceInfo = new RepoItemInfo(this, "LanguagePreference", "combobox[@controlid='401']", 3000, null, "e0211a57-4826-44d9-9c02-1ce2312892ea");
                _sinInfo = new RepoItemInfo(this, "SIN", "element[@controlid='49']/text", 3000, null, "b12304c6-b8e4-4e5e-ad6d-485ec1c4b3d3");
                _birthdateInfo = new RepoItemInfo(this, "BirthDate", "element[@controlid='50']/text", 3000, null, "c66aadfe-c224-4dd7-82da-45b415134770");
                _roecodeInfo = new RepoItemInfo(this, "ROECode", "combobox[@controlid='56']", 3000, null, "15d7591c-e67a-4d43-a765-d1bbde94c20f");
                _hiredateInfo = new RepoItemInfo(this, "HireDate", "element[@controlid='52']/text", 3000, null, "70df7361-5be3-4d44-a03d-58861c4740fd");
                _terminatedateInfo = new RepoItemInfo(this, "TerminateDate", "element[@controlid='54']/text", 3000, null, "53c4deca-f383-47ec-8c87-d65766835617");
                _departmentInfo = new RepoItemInfo(this, "Department", "combobox[@controlid='60']", 3000, null, "bd85cd9d-f1fc-4e4d-ae24-5f72d5b913d3");
                _jobcategoryInfo = new RepoItemInfo(this, "JobCategory", "combobox[@controlid='62']", 3000, null, "1ba9a83f-230c-4206-9d75-fc27a61850d7");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("f4667627-40dd-411d-a3f2-21c4af3b62ee")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("f4667627-40dd-411d-a3f2-21c4af3b62ee")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The Tab item.
            /// </summary>
            [RepositoryItem("52afa08f-5f14-46a0-a1bb-b358b6dc54f4")]
            public virtual Ranorex.TabPage Tab
            {
                get
                {
                    return _tabInfo.CreateAdapter<Ranorex.TabPage>(true);
                }
            }

            /// <summary>
            /// The Tab item info.
            /// </summary>
            [RepositoryItemInfo("52afa08f-5f14-46a0-a1bb-b358b6dc54f4")]
            public virtual RepoItemInfo TabInfo
            {
                get
                {
                    return _tabInfo;
                }
            }

            /// <summary>
            /// The Street1 item.
            /// </summary>
            [RepositoryItem("e0f1f66b-55c6-4353-ba5e-48babbbe3284")]
            public virtual Ranorex.Text Street1
            {
                get
                {
                    return _street1Info.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The Street1 item info.
            /// </summary>
            [RepositoryItemInfo("e0f1f66b-55c6-4353-ba5e-48babbbe3284")]
            public virtual RepoItemInfo Street1Info
            {
                get
                {
                    return _street1Info;
                }
            }

            /// <summary>
            /// The Street2 item.
            /// </summary>
            [RepositoryItem("1c3c8402-b137-468a-8836-8e8a01e8ab05")]
            public virtual Ranorex.Text Street2
            {
                get
                {
                    return _street2Info.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The Street2 item info.
            /// </summary>
            [RepositoryItemInfo("1c3c8402-b137-468a-8836-8e8a01e8ab05")]
            public virtual RepoItemInfo Street2Info
            {
                get
                {
                    return _street2Info;
                }
            }

            /// <summary>
            /// The City item.
            /// </summary>
            [RepositoryItem("cad500d0-eb67-403d-b0b1-f49c03af3d67")]
            public virtual Ranorex.Text City
            {
                get
                {
                    return _cityInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The City item info.
            /// </summary>
            [RepositoryItemInfo("cad500d0-eb67-403d-b0b1-f49c03af3d67")]
            public virtual RepoItemInfo CityInfo
            {
                get
                {
                    return _cityInfo;
                }
            }

            /// <summary>
            /// The Province item.
            /// </summary>
            [RepositoryItem("22ef6bc0-2273-4be7-8a29-36326e4cfb56")]
            public virtual Ranorex.Text Province
            {
                get
                {
                    return _provinceInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The Province item info.
            /// </summary>
            [RepositoryItemInfo("22ef6bc0-2273-4be7-8a29-36326e4cfb56")]
            public virtual RepoItemInfo ProvinceInfo
            {
                get
                {
                    return _provinceInfo;
                }
            }

            /// <summary>
            /// The ProvinceCode item.
            /// </summary>
            [RepositoryItem("17fac9f7-0db6-4483-a58b-bf27f274faaf")]
            public virtual Ranorex.ComboBox ProvinceCode
            {
                get
                {
                    return _provincecodeInfo.CreateAdapter<Ranorex.ComboBox>(true);
                }
            }

            /// <summary>
            /// The ProvinceCode item info.
            /// </summary>
            [RepositoryItemInfo("17fac9f7-0db6-4483-a58b-bf27f274faaf")]
            public virtual RepoItemInfo ProvinceCodeInfo
            {
                get
                {
                    return _provincecodeInfo;
                }
            }

            /// <summary>
            /// The PostalCode item.
            /// </summary>
            [RepositoryItem("f1813c56-dbf3-4c1d-b55a-882bf27c117e")]
            public virtual Ranorex.Text PostalCode
            {
                get
                {
                    return _postalcodeInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The PostalCode item info.
            /// </summary>
            [RepositoryItemInfo("f1813c56-dbf3-4c1d-b55a-882bf27c117e")]
            public virtual RepoItemInfo PostalCodeInfo
            {
                get
                {
                    return _postalcodeInfo;
                }
            }

            /// <summary>
            /// The Phone1 item.
            /// </summary>
            [RepositoryItem("6eec9afa-d361-44bf-b873-71cfe48f6f44")]
            public virtual Ranorex.Text Phone1
            {
                get
                {
                    return _phone1Info.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The Phone1 item info.
            /// </summary>
            [RepositoryItemInfo("6eec9afa-d361-44bf-b873-71cfe48f6f44")]
            public virtual RepoItemInfo Phone1Info
            {
                get
                {
                    return _phone1Info;
                }
            }

            /// <summary>
            /// The Phone2 item.
            /// </summary>
            [RepositoryItem("af61d0ee-18cd-457f-8f4c-bae50f25f776")]
            public virtual Ranorex.Text Phone2
            {
                get
                {
                    return _phone2Info.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The Phone2 item info.
            /// </summary>
            [RepositoryItemInfo("af61d0ee-18cd-457f-8f4c-bae50f25f776")]
            public virtual RepoItemInfo Phone2Info
            {
                get
                {
                    return _phone2Info;
                }
            }

            /// <summary>
            /// The LanguagePreference item.
            /// </summary>
            [RepositoryItem("e0211a57-4826-44d9-9c02-1ce2312892ea")]
            public virtual Ranorex.ComboBox LanguagePreference
            {
                get
                {
                    return _languagepreferenceInfo.CreateAdapter<Ranorex.ComboBox>(true);
                }
            }

            /// <summary>
            /// The LanguagePreference item info.
            /// </summary>
            [RepositoryItemInfo("e0211a57-4826-44d9-9c02-1ce2312892ea")]
            public virtual RepoItemInfo LanguagePreferenceInfo
            {
                get
                {
                    return _languagepreferenceInfo;
                }
            }

            /// <summary>
            /// The SIN item.
            /// </summary>
            [RepositoryItem("b12304c6-b8e4-4e5e-ad6d-485ec1c4b3d3")]
            public virtual Ranorex.Text SIN
            {
                get
                {
                    return _sinInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The SIN item info.
            /// </summary>
            [RepositoryItemInfo("b12304c6-b8e4-4e5e-ad6d-485ec1c4b3d3")]
            public virtual RepoItemInfo SINInfo
            {
                get
                {
                    return _sinInfo;
                }
            }

            /// <summary>
            /// The BirthDate item.
            /// </summary>
            [RepositoryItem("c66aadfe-c224-4dd7-82da-45b415134770")]
            public virtual Ranorex.Text BirthDate
            {
                get
                {
                    return _birthdateInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The BirthDate item info.
            /// </summary>
            [RepositoryItemInfo("c66aadfe-c224-4dd7-82da-45b415134770")]
            public virtual RepoItemInfo BirthDateInfo
            {
                get
                {
                    return _birthdateInfo;
                }
            }

            /// <summary>
            /// The ROECode item.
            /// </summary>
            [RepositoryItem("15d7591c-e67a-4d43-a765-d1bbde94c20f")]
            public virtual Ranorex.ComboBox ROECode
            {
                get
                {
                    return _roecodeInfo.CreateAdapter<Ranorex.ComboBox>(true);
                }
            }

            /// <summary>
            /// The ROECode item info.
            /// </summary>
            [RepositoryItemInfo("15d7591c-e67a-4d43-a765-d1bbde94c20f")]
            public virtual RepoItemInfo ROECodeInfo
            {
                get
                {
                    return _roecodeInfo;
                }
            }

            /// <summary>
            /// The HireDate item.
            /// </summary>
            [RepositoryItem("70df7361-5be3-4d44-a03d-58861c4740fd")]
            public virtual Ranorex.Text HireDate
            {
                get
                {
                    return _hiredateInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The HireDate item info.
            /// </summary>
            [RepositoryItemInfo("70df7361-5be3-4d44-a03d-58861c4740fd")]
            public virtual RepoItemInfo HireDateInfo
            {
                get
                {
                    return _hiredateInfo;
                }
            }

            /// <summary>
            /// The TerminateDate item.
            /// </summary>
            [RepositoryItem("53c4deca-f383-47ec-8c87-d65766835617")]
            public virtual Ranorex.Text TerminateDate
            {
                get
                {
                    return _terminatedateInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The TerminateDate item info.
            /// </summary>
            [RepositoryItemInfo("53c4deca-f383-47ec-8c87-d65766835617")]
            public virtual RepoItemInfo TerminateDateInfo
            {
                get
                {
                    return _terminatedateInfo;
                }
            }

            /// <summary>
            /// The Department item.
            /// </summary>
            [RepositoryItem("bd85cd9d-f1fc-4e4d-ae24-5f72d5b913d3")]
            public virtual Ranorex.ComboBox Department
            {
                get
                {
                    return _departmentInfo.CreateAdapter<Ranorex.ComboBox>(true);
                }
            }

            /// <summary>
            /// The Department item info.
            /// </summary>
            [RepositoryItemInfo("bd85cd9d-f1fc-4e4d-ae24-5f72d5b913d3")]
            public virtual RepoItemInfo DepartmentInfo
            {
                get
                {
                    return _departmentInfo;
                }
            }

            /// <summary>
            /// The JobCategory item.
            /// </summary>
            [RepositoryItem("1ba9a83f-230c-4206-9d75-fc27a61850d7")]
            public virtual Ranorex.ComboBox JobCategory
            {
                get
                {
                    return _jobcategoryInfo.CreateAdapter<Ranorex.ComboBox>(true);
                }
            }

            /// <summary>
            /// The JobCategory item info.
            /// </summary>
            [RepositoryItemInfo("1ba9a83f-230c-4206-9d75-fc27a61850d7")]
            public virtual RepoItemInfo JobCategoryInfo
            {
                get
                {
                    return _jobcategoryInfo;
                }
            }
        }

        /// <summary>
        /// The TaxesFolder folder.
        /// </summary>
        [RepositoryFolder("7ea18317-1b0a-4237-b223-ae875f6ce9f7")]
        public partial class TaxesFolder : RepoGenBaseFolder
        {
            RepoItemInfo _tabInfo;
            RepoItemInfo _taxtableInfo;
            RepoItemInfo _personaltaxcreditscontainerInfo;
            RepoItemInfo _additionalfederaltaxInfo;
            RepoItemInfo _deducteiInfo;
            RepoItemInfo _deductqpiporsocsecInfo;
            RepoItemInfo _deductcppqppInfo;
            RepoItemInfo _eirateInfo;
            RepoItemInfo _taxcontainerInfo;

            /// <summary>
            /// Creates a new Taxes  folder.
            /// </summary>
            public TaxesFolder(RepoGenBaseFolder parentFolder) :
                    base("Taxes", "", parentFolder, 1000, null, false, "7ea18317-1b0a-4237-b223-ae875f6ce9f7", "")
            {
                _tabInfo = new RepoItemInfo(this, "Tab", "?/?/tabpage[@title='Taxes']", 3000, null, "df6b8bab-a0d8-450f-8737-39cff224528f");
                _taxtableInfo = new RepoItemInfo(this, "TaxTable", "combobox[@controlid='129']", 3000, null, "93e36326-8408-4dc6-b333-0fb2ad4421eb");
                _personaltaxcreditscontainerInfo = new RepoItemInfo(this, "PersonalTaxCreditsContainer", "element[@controlid='4469']", 3000, null, "a2bcd86c-50a2-4cf2-a149-4d0fe789a86d");
                _additionalfederaltaxInfo = new RepoItemInfo(this, "AdditionalFederalTax", "element[@controlid='131']/text", 3000, null, "d04a2a22-ead2-44a2-90a3-3dc29437d146");
                _deducteiInfo = new RepoItemInfo(this, "DeductEI", "checkbox[@text='Calculate &EI']", 3000, null, "d5b2848e-aa91-410b-848c-315ecc468e1f");
                _deductqpiporsocsecInfo = new RepoItemInfo(this, "DeductQpipOrSocSec", "checkbox[@text='Calculate &QPIP']", 3000, null, "0276ebd4-d8df-4bf7-bf57-ad151a8ad57c");
                _deductcppqppInfo = new RepoItemInfo(this, "DeductCPPQPP", "checkbox[@text='Calc&ulate CPP/QPP']", 3000, null, "8dd45840-127a-4191-b397-3ce858bf5b54");
                _eirateInfo = new RepoItemInfo(this, "EIRate", "element[@controlid='138']/text", 3000, null, "100e1714-7d47-4b16-85c9-f79afc8424cb");
                _taxcontainerInfo = new RepoItemInfo(this, "TaxContainer", "element[@controlid='4475']", 3000, null, "b693b6bc-95ae-4b98-81fc-d97faacfe70d");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("7ea18317-1b0a-4237-b223-ae875f6ce9f7")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("7ea18317-1b0a-4237-b223-ae875f6ce9f7")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The Tab item.
            /// </summary>
            [RepositoryItem("df6b8bab-a0d8-450f-8737-39cff224528f")]
            public virtual Ranorex.TabPage Tab
            {
                get
                {
                    return _tabInfo.CreateAdapter<Ranorex.TabPage>(true);
                }
            }

            /// <summary>
            /// The Tab item info.
            /// </summary>
            [RepositoryItemInfo("df6b8bab-a0d8-450f-8737-39cff224528f")]
            public virtual RepoItemInfo TabInfo
            {
                get
                {
                    return _tabInfo;
                }
            }

            /// <summary>
            /// The TaxTable item.
            /// </summary>
            [RepositoryItem("93e36326-8408-4dc6-b333-0fb2ad4421eb")]
            public virtual Ranorex.ComboBox TaxTable
            {
                get
                {
                    return _taxtableInfo.CreateAdapter<Ranorex.ComboBox>(true);
                }
            }

            /// <summary>
            /// The TaxTable item info.
            /// </summary>
            [RepositoryItemInfo("93e36326-8408-4dc6-b333-0fb2ad4421eb")]
            public virtual RepoItemInfo TaxTableInfo
            {
                get
                {
                    return _taxtableInfo;
                }
            }

            /// <summary>
            /// The PersonalTaxCreditsContainer item.
            /// </summary>
            [RepositoryItem("a2bcd86c-50a2-4cf2-a149-4d0fe789a86d")]
            public virtual Ranorex.Unknown PersonalTaxCreditsContainer
            {
                get
                {
                    return _personaltaxcreditscontainerInfo.CreateAdapter<Ranorex.Unknown>(true);
                }
            }

            /// <summary>
            /// The PersonalTaxCreditsContainer item info.
            /// </summary>
            [RepositoryItemInfo("a2bcd86c-50a2-4cf2-a149-4d0fe789a86d")]
            public virtual RepoItemInfo PersonalTaxCreditsContainerInfo
            {
                get
                {
                    return _personaltaxcreditscontainerInfo;
                }
            }

            /// <summary>
            /// The AdditionalFederalTax item.
            /// </summary>
            [RepositoryItem("d04a2a22-ead2-44a2-90a3-3dc29437d146")]
            public virtual Ranorex.Text AdditionalFederalTax
            {
                get
                {
                    return _additionalfederaltaxInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The AdditionalFederalTax item info.
            /// </summary>
            [RepositoryItemInfo("d04a2a22-ead2-44a2-90a3-3dc29437d146")]
            public virtual RepoItemInfo AdditionalFederalTaxInfo
            {
                get
                {
                    return _additionalfederaltaxInfo;
                }
            }

            /// <summary>
            /// The DeductEI item.
            /// </summary>
            [RepositoryItem("d5b2848e-aa91-410b-848c-315ecc468e1f")]
            public virtual Ranorex.CheckBox DeductEI
            {
                get
                {
                    return _deducteiInfo.CreateAdapter<Ranorex.CheckBox>(true);
                }
            }

            /// <summary>
            /// The DeductEI item info.
            /// </summary>
            [RepositoryItemInfo("d5b2848e-aa91-410b-848c-315ecc468e1f")]
            public virtual RepoItemInfo DeductEIInfo
            {
                get
                {
                    return _deducteiInfo;
                }
            }

            /// <summary>
            /// The DeductQpipOrSocSec item.
            /// </summary>
            [RepositoryItem("0276ebd4-d8df-4bf7-bf57-ad151a8ad57c")]
            public virtual Ranorex.CheckBox DeductQpipOrSocSec
            {
                get
                {
                    return _deductqpiporsocsecInfo.CreateAdapter<Ranorex.CheckBox>(true);
                }
            }

            /// <summary>
            /// The DeductQpipOrSocSec item info.
            /// </summary>
            [RepositoryItemInfo("0276ebd4-d8df-4bf7-bf57-ad151a8ad57c")]
            public virtual RepoItemInfo DeductQpipOrSocSecInfo
            {
                get
                {
                    return _deductqpiporsocsecInfo;
                }
            }

            /// <summary>
            /// The DeductCPPQPP item.
            /// </summary>
            [RepositoryItem("8dd45840-127a-4191-b397-3ce858bf5b54")]
            public virtual Ranorex.CheckBox DeductCPPQPP
            {
                get
                {
                    return _deductcppqppInfo.CreateAdapter<Ranorex.CheckBox>(true);
                }
            }

            /// <summary>
            /// The DeductCPPQPP item info.
            /// </summary>
            [RepositoryItemInfo("8dd45840-127a-4191-b397-3ce858bf5b54")]
            public virtual RepoItemInfo DeductCPPQPPInfo
            {
                get
                {
                    return _deductcppqppInfo;
                }
            }

            /// <summary>
            /// The EIRate item.
            /// </summary>
            [RepositoryItem("100e1714-7d47-4b16-85c9-f79afc8424cb")]
            public virtual Ranorex.Text EIRate
            {
                get
                {
                    return _eirateInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The EIRate item info.
            /// </summary>
            [RepositoryItemInfo("100e1714-7d47-4b16-85c9-f79afc8424cb")]
            public virtual RepoItemInfo EIRateInfo
            {
                get
                {
                    return _eirateInfo;
                }
            }

            /// <summary>
            /// The TaxContainer item.
            /// </summary>
            [RepositoryItem("b693b6bc-95ae-4b98-81fc-d97faacfe70d")]
            public virtual Ranorex.Unknown TaxContainer
            {
                get
                {
                    return _taxcontainerInfo.CreateAdapter<Ranorex.Unknown>(true);
                }
            }

            /// <summary>
            /// The TaxContainer item info.
            /// </summary>
            [RepositoryItemInfo("b693b6bc-95ae-4b98-81fc-d97faacfe70d")]
            public virtual RepoItemInfo TaxContainerInfo
            {
                get
                {
                    return _taxcontainerInfo;
                }
            }
        }

        /// <summary>
        /// The IncomeFolder folder.
        /// </summary>
        [RepositoryFolder("21779d3e-ec47-4ea9-a778-8037db5dd7da")]
        public partial class IncomeFolder : RepoGenBaseFolder
        {
            RepoItemInfo _tabInfo;
            RepoItemInfo _incomecontainerInfo;
            RepoItemInfo _payperiodsperyearInfo;
            RepoItemInfo _retainvacationInfo;
            RepoItemInfo _calculatevacationonvacationInfo;
            RepoItemInfo _retainvacationpercentageInfo;
            RepoItemInfo _recordwageexpensesinInfo;
            RepoItemInfo _wageexpensesbuttonInfo;
            RepoItemInfo _wageexpensesdropdownInfo;

            /// <summary>
            /// Creates a new Income  folder.
            /// </summary>
            public IncomeFolder(RepoGenBaseFolder parentFolder) :
                    base("Income", "", parentFolder, 1000, null, false, "21779d3e-ec47-4ea9-a778-8037db5dd7da", "")
            {
                _tabInfo = new RepoItemInfo(this, "Tab", "?/?/tabpage[@title='Income']", 3000, null, "1277f960-296f-4603-924a-9a32a86e975c");
                _incomecontainerInfo = new RepoItemInfo(this, "IncomeContainer", "element[@controlid='3978']", 3000, null, "ac000383-476f-439d-b95a-19b6ce686255");
                _payperiodsperyearInfo = new RepoItemInfo(this, "PayPeriodsPerYear", "combobox[@controlid='72']", 3000, null, "08a4875d-b8d9-4bd1-9a77-953d8f9d41ef");
                _retainvacationInfo = new RepoItemInfo(this, "RetainVacation", "checkbox[@text='&Retain Vacation']", 3000, null, "7fc39cd0-8628-4ae2-91e4-ce22ca3cc50c");
                _calculatevacationonvacationInfo = new RepoItemInfo(this, "CalculateVacationOnVacation", "checkbox[@text~'^Calculate\\ &Vacation\\ on\\ Va']", 3000, null, "2418c3f7-19d8-48f1-89bb-4db24e00dc5c");
                _retainvacationpercentageInfo = new RepoItemInfo(this, "RetainVacationPercentage", "text[@controlid='74']", 3000, null, "d2c9ff9e-7489-4415-89c6-3036004d4e11");
                _recordwageexpensesinInfo = new RepoItemInfo(this, "RecordWageExpensesIn", "radiobutton[@text~'^The\\ payroll\\ linked\\ accoun']", 3000, null, "7b825d3e-1469-46be-a432-1f91e7b39f11");
                _wageexpensesbuttonInfo = new RepoItemInfo(this, "WageExpensesButton", "radiobutton[@text='']", 3000, null, "d82b4766-6cd5-49c5-a8d5-8193a8ced362");
                _wageexpensesdropdownInfo = new RepoItemInfo(this, "WageExpensesDropDown", "combobox[@controlid='104']", 3000, null, "fd1d42b0-b701-49f8-9578-cb6f33e55d55");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("21779d3e-ec47-4ea9-a778-8037db5dd7da")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("21779d3e-ec47-4ea9-a778-8037db5dd7da")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The Tab item.
            /// </summary>
            [RepositoryItem("1277f960-296f-4603-924a-9a32a86e975c")]
            public virtual Ranorex.TabPage Tab
            {
                get
                {
                    return _tabInfo.CreateAdapter<Ranorex.TabPage>(true);
                }
            }

            /// <summary>
            /// The Tab item info.
            /// </summary>
            [RepositoryItemInfo("1277f960-296f-4603-924a-9a32a86e975c")]
            public virtual RepoItemInfo TabInfo
            {
                get
                {
                    return _tabInfo;
                }
            }

            /// <summary>
            /// The IncomeContainer item.
            /// </summary>
            [RepositoryItem("ac000383-476f-439d-b95a-19b6ce686255")]
            public virtual Ranorex.Unknown IncomeContainer
            {
                get
                {
                    return _incomecontainerInfo.CreateAdapter<Ranorex.Unknown>(true);
                }
            }

            /// <summary>
            /// The IncomeContainer item info.
            /// </summary>
            [RepositoryItemInfo("ac000383-476f-439d-b95a-19b6ce686255")]
            public virtual RepoItemInfo IncomeContainerInfo
            {
                get
                {
                    return _incomecontainerInfo;
                }
            }

            /// <summary>
            /// The PayPeriodsPerYear item.
            /// </summary>
            [RepositoryItem("08a4875d-b8d9-4bd1-9a77-953d8f9d41ef")]
            public virtual Ranorex.ComboBox PayPeriodsPerYear
            {
                get
                {
                    return _payperiodsperyearInfo.CreateAdapter<Ranorex.ComboBox>(true);
                }
            }

            /// <summary>
            /// The PayPeriodsPerYear item info.
            /// </summary>
            [RepositoryItemInfo("08a4875d-b8d9-4bd1-9a77-953d8f9d41ef")]
            public virtual RepoItemInfo PayPeriodsPerYearInfo
            {
                get
                {
                    return _payperiodsperyearInfo;
                }
            }

            /// <summary>
            /// The RetainVacation item.
            /// </summary>
            [RepositoryItem("7fc39cd0-8628-4ae2-91e4-ce22ca3cc50c")]
            public virtual Ranorex.CheckBox RetainVacation
            {
                get
                {
                    return _retainvacationInfo.CreateAdapter<Ranorex.CheckBox>(true);
                }
            }

            /// <summary>
            /// The RetainVacation item info.
            /// </summary>
            [RepositoryItemInfo("7fc39cd0-8628-4ae2-91e4-ce22ca3cc50c")]
            public virtual RepoItemInfo RetainVacationInfo
            {
                get
                {
                    return _retainvacationInfo;
                }
            }

            /// <summary>
            /// The CalculateVacationOnVacation item.
            /// </summary>
            [RepositoryItem("2418c3f7-19d8-48f1-89bb-4db24e00dc5c")]
            public virtual Ranorex.CheckBox CalculateVacationOnVacation
            {
                get
                {
                    return _calculatevacationonvacationInfo.CreateAdapter<Ranorex.CheckBox>(true);
                }
            }

            /// <summary>
            /// The CalculateVacationOnVacation item info.
            /// </summary>
            [RepositoryItemInfo("2418c3f7-19d8-48f1-89bb-4db24e00dc5c")]
            public virtual RepoItemInfo CalculateVacationOnVacationInfo
            {
                get
                {
                    return _calculatevacationonvacationInfo;
                }
            }

            /// <summary>
            /// The RetainVacationPercentage item.
            /// </summary>
            [RepositoryItem("d2c9ff9e-7489-4415-89c6-3036004d4e11")]
            public virtual Ranorex.Text RetainVacationPercentage
            {
                get
                {
                    return _retainvacationpercentageInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The RetainVacationPercentage item info.
            /// </summary>
            [RepositoryItemInfo("d2c9ff9e-7489-4415-89c6-3036004d4e11")]
            public virtual RepoItemInfo RetainVacationPercentageInfo
            {
                get
                {
                    return _retainvacationpercentageInfo;
                }
            }

            /// <summary>
            /// The RecordWageExpensesIn item.
            /// </summary>
            [RepositoryItem("7b825d3e-1469-46be-a432-1f91e7b39f11")]
            public virtual Ranorex.RadioButton RecordWageExpensesIn
            {
                get
                {
                    return _recordwageexpensesinInfo.CreateAdapter<Ranorex.RadioButton>(true);
                }
            }

            /// <summary>
            /// The RecordWageExpensesIn item info.
            /// </summary>
            [RepositoryItemInfo("7b825d3e-1469-46be-a432-1f91e7b39f11")]
            public virtual RepoItemInfo RecordWageExpensesInInfo
            {
                get
                {
                    return _recordwageexpensesinInfo;
                }
            }

            /// <summary>
            /// The WageExpensesButton item.
            /// </summary>
            [RepositoryItem("d82b4766-6cd5-49c5-a8d5-8193a8ced362")]
            public virtual Ranorex.RadioButton WageExpensesButton
            {
                get
                {
                    return _wageexpensesbuttonInfo.CreateAdapter<Ranorex.RadioButton>(true);
                }
            }

            /// <summary>
            /// The WageExpensesButton item info.
            /// </summary>
            [RepositoryItemInfo("d82b4766-6cd5-49c5-a8d5-8193a8ced362")]
            public virtual RepoItemInfo WageExpensesButtonInfo
            {
                get
                {
                    return _wageexpensesbuttonInfo;
                }
            }

            /// <summary>
            /// The WageExpensesDropDown item.
            /// </summary>
            [RepositoryItem("fd1d42b0-b701-49f8-9578-cb6f33e55d55")]
            public virtual Ranorex.ComboBox WageExpensesDropDown
            {
                get
                {
                    return _wageexpensesdropdownInfo.CreateAdapter<Ranorex.ComboBox>(true);
                }
            }

            /// <summary>
            /// The WageExpensesDropDown item info.
            /// </summary>
            [RepositoryItemInfo("fd1d42b0-b701-49f8-9578-cb6f33e55d55")]
            public virtual RepoItemInfo WageExpensesDropDownInfo
            {
                get
                {
                    return _wageexpensesdropdownInfo;
                }
            }
        }

        /// <summary>
        /// The DeductionsFolder folder.
        /// </summary>
        [RepositoryFolder("d33ade79-2ee2-493d-a75d-61d18c6d49e9")]
        public partial class DeductionsFolder : RepoGenBaseFolder
        {
            RepoItemInfo _tabInfo;
            RepoItemInfo _deductionscontainerInfo;

            /// <summary>
            /// Creates a new Deductions  folder.
            /// </summary>
            public DeductionsFolder(RepoGenBaseFolder parentFolder) :
                    base("Deductions", "", parentFolder, 1000, null, false, "d33ade79-2ee2-493d-a75d-61d18c6d49e9", "")
            {
                _tabInfo = new RepoItemInfo(this, "Tab", "?/?/tabpage[@title='Deductions']", 3000, null, "3d3da7e0-aa19-4cf9-bee9-31b05f0bb5c7");
                _deductionscontainerInfo = new RepoItemInfo(this, "DeductionsContainer", "element[@controlid='3979']", 3000, null, "420a281b-4ca3-4d88-bf08-8669462c0fc0");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("d33ade79-2ee2-493d-a75d-61d18c6d49e9")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("d33ade79-2ee2-493d-a75d-61d18c6d49e9")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The Tab item.
            /// </summary>
            [RepositoryItem("3d3da7e0-aa19-4cf9-bee9-31b05f0bb5c7")]
            public virtual Ranorex.TabPage Tab
            {
                get
                {
                    return _tabInfo.CreateAdapter<Ranorex.TabPage>(true);
                }
            }

            /// <summary>
            /// The Tab item info.
            /// </summary>
            [RepositoryItemInfo("3d3da7e0-aa19-4cf9-bee9-31b05f0bb5c7")]
            public virtual RepoItemInfo TabInfo
            {
                get
                {
                    return _tabInfo;
                }
            }

            /// <summary>
            /// The DeductionsContainer item.
            /// </summary>
            [RepositoryItem("420a281b-4ca3-4d88-bf08-8669462c0fc0")]
            public virtual Ranorex.Unknown DeductionsContainer
            {
                get
                {
                    return _deductionscontainerInfo.CreateAdapter<Ranorex.Unknown>(true);
                }
            }

            /// <summary>
            /// The DeductionsContainer item info.
            /// </summary>
            [RepositoryItemInfo("420a281b-4ca3-4d88-bf08-8669462c0fc0")]
            public virtual RepoItemInfo DeductionsContainerInfo
            {
                get
                {
                    return _deductionscontainerInfo;
                }
            }
        }

        /// <summary>
        /// The WCBOtherExpFolder folder.
        /// </summary>
        [RepositoryFolder("78c4e4a8-0468-49de-a4d3-64df412d10cb")]
        public partial class WCBOtherExpFolder : RepoGenBaseFolder
        {
            RepoItemInfo _tabInfo;
            RepoItemInfo _wcbrateInfo;
            RepoItemInfo _wcbcontainerInfo;

            /// <summary>
            /// Creates a new WCBOtherExp  folder.
            /// </summary>
            public WCBOtherExpFolder(RepoGenBaseFolder parentFolder) :
                    base("WCBOtherExp", "", parentFolder, 1000, null, false, "78c4e4a8-0468-49de-a4d3-64df412d10cb", "")
            {
                _tabInfo = new RepoItemInfo(this, "Tab", "?/?/tabpage[@title='WCB & Other Expenses']", 3000, null, "a1f66255-0f52-4436-9860-477827ac610e");
                _wcbrateInfo = new RepoItemInfo(this, "WCBRate", "element[@controlid='140']/text", 3000, null, "b769aada-2dfc-4dc8-a437-13ce3e71ef8b");
                _wcbcontainerInfo = new RepoItemInfo(this, "WCBContainer", "element[@controlid='4494']", 3000, null, "c0148980-5914-4604-a67b-781e19494312");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("78c4e4a8-0468-49de-a4d3-64df412d10cb")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("78c4e4a8-0468-49de-a4d3-64df412d10cb")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The Tab item.
            /// </summary>
            [RepositoryItem("a1f66255-0f52-4436-9860-477827ac610e")]
            public virtual Ranorex.TabPage Tab
            {
                get
                {
                    return _tabInfo.CreateAdapter<Ranorex.TabPage>(true);
                }
            }

            /// <summary>
            /// The Tab item info.
            /// </summary>
            [RepositoryItemInfo("a1f66255-0f52-4436-9860-477827ac610e")]
            public virtual RepoItemInfo TabInfo
            {
                get
                {
                    return _tabInfo;
                }
            }

            /// <summary>
            /// The WCBRate item.
            /// </summary>
            [RepositoryItem("b769aada-2dfc-4dc8-a437-13ce3e71ef8b")]
            public virtual Ranorex.Text WCBRate
            {
                get
                {
                    return _wcbrateInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The WCBRate item info.
            /// </summary>
            [RepositoryItemInfo("b769aada-2dfc-4dc8-a437-13ce3e71ef8b")]
            public virtual RepoItemInfo WCBRateInfo
            {
                get
                {
                    return _wcbrateInfo;
                }
            }

            /// <summary>
            /// The WCBContainer item.
            /// </summary>
            [RepositoryItem("c0148980-5914-4604-a67b-781e19494312")]
            public virtual Ranorex.Unknown WCBContainer
            {
                get
                {
                    return _wcbcontainerInfo.CreateAdapter<Ranorex.Unknown>(true);
                }
            }

            /// <summary>
            /// The WCBContainer item info.
            /// </summary>
            [RepositoryItemInfo("c0148980-5914-4604-a67b-781e19494312")]
            public virtual RepoItemInfo WCBContainerInfo
            {
                get
                {
                    return _wcbcontainerInfo;
                }
            }
        }

        /// <summary>
        /// The EntitlementsFolder folder.
        /// </summary>
        [RepositoryFolder("e31890a3-9716-434d-ae84-7a15e35263c0")]
        public partial class EntitlementsFolder : RepoGenBaseFolder
        {
            RepoItemInfo _tabInfo;
            RepoItemInfo _hoursinworkdayInfo;
            RepoItemInfo _entitlementscontainerInfo;

            /// <summary>
            /// Creates a new Entitlements  folder.
            /// </summary>
            public EntitlementsFolder(RepoGenBaseFolder parentFolder) :
                    base("Entitlements", "", parentFolder, 1000, null, false, "e31890a3-9716-434d-ae84-7a15e35263c0", "")
            {
                _tabInfo = new RepoItemInfo(this, "Tab", "?/?/tabpage[@title='Entitlements']", 3000, null, "c633165c-3de4-4e07-bd7d-769e729d3413");
                _hoursinworkdayInfo = new RepoItemInfo(this, "HoursInWorkDay", "element[@controlid='908']/text", 3000, null, "f3be18fb-17e3-4b1c-adbf-da265fa4be9a");
                _entitlementscontainerInfo = new RepoItemInfo(this, "EntitlementsContainer", "element[@controlid='3850']", 3000, null, "2f15e7c2-e3ed-4d46-9311-1ec2926b60b6");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("e31890a3-9716-434d-ae84-7a15e35263c0")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("e31890a3-9716-434d-ae84-7a15e35263c0")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The Tab item.
            /// </summary>
            [RepositoryItem("c633165c-3de4-4e07-bd7d-769e729d3413")]
            public virtual Ranorex.TabPage Tab
            {
                get
                {
                    return _tabInfo.CreateAdapter<Ranorex.TabPage>(true);
                }
            }

            /// <summary>
            /// The Tab item info.
            /// </summary>
            [RepositoryItemInfo("c633165c-3de4-4e07-bd7d-769e729d3413")]
            public virtual RepoItemInfo TabInfo
            {
                get
                {
                    return _tabInfo;
                }
            }

            /// <summary>
            /// The HoursInWorkDay item.
            /// </summary>
            [RepositoryItem("f3be18fb-17e3-4b1c-adbf-da265fa4be9a")]
            public virtual Ranorex.Text HoursInWorkDay
            {
                get
                {
                    return _hoursinworkdayInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The HoursInWorkDay item info.
            /// </summary>
            [RepositoryItemInfo("f3be18fb-17e3-4b1c-adbf-da265fa4be9a")]
            public virtual RepoItemInfo HoursInWorkDayInfo
            {
                get
                {
                    return _hoursinworkdayInfo;
                }
            }

            /// <summary>
            /// The EntitlementsContainer item.
            /// </summary>
            [RepositoryItem("2f15e7c2-e3ed-4d46-9311-1ec2926b60b6")]
            public virtual Ranorex.Unknown EntitlementsContainer
            {
                get
                {
                    return _entitlementscontainerInfo.CreateAdapter<Ranorex.Unknown>(true);
                }
            }

            /// <summary>
            /// The EntitlementsContainer item info.
            /// </summary>
            [RepositoryItemInfo("2f15e7c2-e3ed-4d46-9311-1ec2926b60b6")]
            public virtual RepoItemInfo EntitlementsContainerInfo
            {
                get
                {
                    return _entitlementscontainerInfo;
                }
            }
        }

        /// <summary>
        /// The DirectDepositFolder folder.
        /// </summary>
        [RepositoryFolder("dd0c479a-ab5b-4164-a385-f564f3d72d7f")]
        public partial class DirectDepositFolder : RepoGenBaseFolder
        {
            RepoItemInfo _tabInfo;
            RepoItemInfo _ddInfo;
            RepoItemInfo _directdepositcontainerInfo;

            /// <summary>
            /// Creates a new DirectDeposit  folder.
            /// </summary>
            public DirectDepositFolder(RepoGenBaseFolder parentFolder) :
                    base("DirectDeposit", "", parentFolder, 1000, null, false, "dd0c479a-ab5b-4164-a385-f564f3d72d7f", "")
            {
                _tabInfo = new RepoItemInfo(this, "Tab", "?/?/tabpage[@title='Direct Deposit']", 3000, null, "7dd7aa36-387d-49f6-9f67-156b12812066");
                _ddInfo = new RepoItemInfo(this, "DD", "checkbox[@text~'^&Direct\\ deposit\\ paycheque']", 3000, null, "c387e71a-9ebc-4358-8aca-341ef337bc42");
                _directdepositcontainerInfo = new RepoItemInfo(this, "DirectDepositContainer", "element[@controlid='3700']", 3000, null, "4d8fbcca-3067-4be0-837b-39416f492e54");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("dd0c479a-ab5b-4164-a385-f564f3d72d7f")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("dd0c479a-ab5b-4164-a385-f564f3d72d7f")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The Tab item.
            /// </summary>
            [RepositoryItem("7dd7aa36-387d-49f6-9f67-156b12812066")]
            public virtual Ranorex.TabPage Tab
            {
                get
                {
                    return _tabInfo.CreateAdapter<Ranorex.TabPage>(true);
                }
            }

            /// <summary>
            /// The Tab item info.
            /// </summary>
            [RepositoryItemInfo("7dd7aa36-387d-49f6-9f67-156b12812066")]
            public virtual RepoItemInfo TabInfo
            {
                get
                {
                    return _tabInfo;
                }
            }

            /// <summary>
            /// The DD item.
            /// </summary>
            [RepositoryItem("c387e71a-9ebc-4358-8aca-341ef337bc42")]
            public virtual Ranorex.CheckBox DD
            {
                get
                {
                    return _ddInfo.CreateAdapter<Ranorex.CheckBox>(true);
                }
            }

            /// <summary>
            /// The DD item info.
            /// </summary>
            [RepositoryItemInfo("c387e71a-9ebc-4358-8aca-341ef337bc42")]
            public virtual RepoItemInfo DDInfo
            {
                get
                {
                    return _ddInfo;
                }
            }

            /// <summary>
            /// The DirectDepositContainer item.
            /// </summary>
            [RepositoryItem("4d8fbcca-3067-4be0-837b-39416f492e54")]
            public virtual Ranorex.Unknown DirectDepositContainer
            {
                get
                {
                    return _directdepositcontainerInfo.CreateAdapter<Ranorex.Unknown>(true);
                }
            }

            /// <summary>
            /// The DirectDepositContainer item info.
            /// </summary>
            [RepositoryItemInfo("4d8fbcca-3067-4be0-837b-39416f492e54")]
            public virtual RepoItemInfo DirectDepositContainerInfo
            {
                get
                {
                    return _directdepositcontainerInfo;
                }
            }
        }

        /// <summary>
        /// The MemoFolder folder.
        /// </summary>
        [RepositoryFolder("44fad97c-c07c-432d-bb88-45dec1656c1d")]
        public partial class MemoFolder : RepoGenBaseFolder
        {
            RepoItemInfo _tabInfo;
            RepoItemInfo _memoInfo;
            RepoItemInfo _tododateInfo;
            RepoItemInfo _displaythismemoInfo;

            /// <summary>
            /// Creates a new Memo  folder.
            /// </summary>
            public MemoFolder(RepoGenBaseFolder parentFolder) :
                    base("Memo", "", parentFolder, 1000, null, false, "44fad97c-c07c-432d-bb88-45dec1656c1d", "")
            {
                _tabInfo = new RepoItemInfo(this, "Tab", "?/?/tabpage[@title='Memo']", 3000, null, "ef5e40b3-6e29-48de-bb92-3dd074952648");
                _memoInfo = new RepoItemInfo(this, "Memo", "element[@controlid='582']/text", 3000, null, "f7ea4a0c-45c2-42e1-bbcc-cb3f4c3ddfba");
                _tododateInfo = new RepoItemInfo(this, "ToDoDate", "element[@controlid='583']/text", 3000, null, "690d0006-bd2c-41b1-b8a8-0abe47986668");
                _displaythismemoInfo = new RepoItemInfo(this, "DisplayThisMemo", "checkbox[@text~'^Displa&y\\ this\\ memo\\ in\\ the']", 3000, null, "84369a99-24e4-49f8-ae5b-8228e5392b91");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("44fad97c-c07c-432d-bb88-45dec1656c1d")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("44fad97c-c07c-432d-bb88-45dec1656c1d")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The Tab item.
            /// </summary>
            [RepositoryItem("ef5e40b3-6e29-48de-bb92-3dd074952648")]
            public virtual Ranorex.TabPage Tab
            {
                get
                {
                    return _tabInfo.CreateAdapter<Ranorex.TabPage>(true);
                }
            }

            /// <summary>
            /// The Tab item info.
            /// </summary>
            [RepositoryItemInfo("ef5e40b3-6e29-48de-bb92-3dd074952648")]
            public virtual RepoItemInfo TabInfo
            {
                get
                {
                    return _tabInfo;
                }
            }

            /// <summary>
            /// The Memo item.
            /// </summary>
            [RepositoryItem("f7ea4a0c-45c2-42e1-bbcc-cb3f4c3ddfba")]
            public virtual Ranorex.Text Memo
            {
                get
                {
                    return _memoInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The Memo item info.
            /// </summary>
            [RepositoryItemInfo("f7ea4a0c-45c2-42e1-bbcc-cb3f4c3ddfba")]
            public virtual RepoItemInfo MemoInfo
            {
                get
                {
                    return _memoInfo;
                }
            }

            /// <summary>
            /// The ToDoDate item.
            /// </summary>
            [RepositoryItem("690d0006-bd2c-41b1-b8a8-0abe47986668")]
            public virtual Ranorex.Text ToDoDate
            {
                get
                {
                    return _tododateInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The ToDoDate item info.
            /// </summary>
            [RepositoryItemInfo("690d0006-bd2c-41b1-b8a8-0abe47986668")]
            public virtual RepoItemInfo ToDoDateInfo
            {
                get
                {
                    return _tododateInfo;
                }
            }

            /// <summary>
            /// The DisplayThisMemo item.
            /// </summary>
            [RepositoryItem("84369a99-24e4-49f8-ae5b-8228e5392b91")]
            public virtual Ranorex.CheckBox DisplayThisMemo
            {
                get
                {
                    return _displaythismemoInfo.CreateAdapter<Ranorex.CheckBox>(true);
                }
            }

            /// <summary>
            /// The DisplayThisMemo item info.
            /// </summary>
            [RepositoryItemInfo("84369a99-24e4-49f8-ae5b-8228e5392b91")]
            public virtual RepoItemInfo DisplayThisMemoInfo
            {
                get
                {
                    return _displaythismemoInfo;
                }
            }
        }

        /// <summary>
        /// The AdditionalInfoFolder folder.
        /// </summary>
        [RepositoryFolder("fe05f852-66a3-4533-a4ad-a2a7e9470256")]
        public partial class AdditionalInfoFolder : RepoGenBaseFolder
        {
            RepoItemInfo _tabInfo;
            RepoItemInfo _additional1Info;
            RepoItemInfo _addcheckbox1Info;
            RepoItemInfo _additional2Info;
            RepoItemInfo _addcheckbox2Info;
            RepoItemInfo _additional3Info;
            RepoItemInfo _addcheckbox3Info;

            /// <summary>
            /// Creates a new AdditionalInfo  folder.
            /// </summary>
            public AdditionalInfoFolder(RepoGenBaseFolder parentFolder) :
                    base("AdditionalInfo", "", parentFolder, 1000, null, false, "fe05f852-66a3-4533-a4ad-a2a7e9470256", "")
            {
                _tabInfo = new RepoItemInfo(this, "Tab", "?/?/tabpage[@title='Additional Info']", 3000, null, "05386a04-500d-4329-8a65-19455996d617");
                _additional1Info = new RepoItemInfo(this, "Additional1", "element[@controlid='805']/text", 3000, null, "2046a22b-df2f-4dc5-bb81-73c2668d6b02");
                _addcheckbox1Info = new RepoItemInfo(this, "AddCheckBox1", "checkbox[@controlid='811']", 3000, null, "fc42c9c3-b45a-4abb-969a-abd995e2d53c");
                _additional2Info = new RepoItemInfo(this, "Additional2", "element[@controlid='806']/text", 3000, null, "aa8aaec5-cf85-424e-a6c2-1e8b1f67b847");
                _addcheckbox2Info = new RepoItemInfo(this, "AddCheckBox2", "checkbox[@controlid='812']", 3000, null, "b6b98dec-95e7-43c6-9a42-c79d604b8467");
                _additional3Info = new RepoItemInfo(this, "Additional3", "element[@controlid='807']/text", 3000, null, "cdc6fcc8-3753-4eb6-ad03-2484d7067b7b");
                _addcheckbox3Info = new RepoItemInfo(this, "AddCheckBox3", "checkbox[@controlid='813']", 3000, null, "80d24a4d-dbf3-4d89-89a8-3be889f0debf");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("fe05f852-66a3-4533-a4ad-a2a7e9470256")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("fe05f852-66a3-4533-a4ad-a2a7e9470256")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The Tab item.
            /// </summary>
            [RepositoryItem("05386a04-500d-4329-8a65-19455996d617")]
            public virtual Ranorex.TabPage Tab
            {
                get
                {
                    return _tabInfo.CreateAdapter<Ranorex.TabPage>(true);
                }
            }

            /// <summary>
            /// The Tab item info.
            /// </summary>
            [RepositoryItemInfo("05386a04-500d-4329-8a65-19455996d617")]
            public virtual RepoItemInfo TabInfo
            {
                get
                {
                    return _tabInfo;
                }
            }

            /// <summary>
            /// The Additional1 item.
            /// </summary>
            [RepositoryItem("2046a22b-df2f-4dc5-bb81-73c2668d6b02")]
            public virtual Ranorex.Text Additional1
            {
                get
                {
                    return _additional1Info.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The Additional1 item info.
            /// </summary>
            [RepositoryItemInfo("2046a22b-df2f-4dc5-bb81-73c2668d6b02")]
            public virtual RepoItemInfo Additional1Info
            {
                get
                {
                    return _additional1Info;
                }
            }

            /// <summary>
            /// The AddCheckBox1 item.
            /// </summary>
            [RepositoryItem("fc42c9c3-b45a-4abb-969a-abd995e2d53c")]
            public virtual Ranorex.CheckBox AddCheckBox1
            {
                get
                {
                    return _addcheckbox1Info.CreateAdapter<Ranorex.CheckBox>(true);
                }
            }

            /// <summary>
            /// The AddCheckBox1 item info.
            /// </summary>
            [RepositoryItemInfo("fc42c9c3-b45a-4abb-969a-abd995e2d53c")]
            public virtual RepoItemInfo AddCheckBox1Info
            {
                get
                {
                    return _addcheckbox1Info;
                }
            }

            /// <summary>
            /// The Additional2 item.
            /// </summary>
            [RepositoryItem("aa8aaec5-cf85-424e-a6c2-1e8b1f67b847")]
            public virtual Ranorex.Text Additional2
            {
                get
                {
                    return _additional2Info.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The Additional2 item info.
            /// </summary>
            [RepositoryItemInfo("aa8aaec5-cf85-424e-a6c2-1e8b1f67b847")]
            public virtual RepoItemInfo Additional2Info
            {
                get
                {
                    return _additional2Info;
                }
            }

            /// <summary>
            /// The AddCheckBox2 item.
            /// </summary>
            [RepositoryItem("b6b98dec-95e7-43c6-9a42-c79d604b8467")]
            public virtual Ranorex.CheckBox AddCheckBox2
            {
                get
                {
                    return _addcheckbox2Info.CreateAdapter<Ranorex.CheckBox>(true);
                }
            }

            /// <summary>
            /// The AddCheckBox2 item info.
            /// </summary>
            [RepositoryItemInfo("b6b98dec-95e7-43c6-9a42-c79d604b8467")]
            public virtual RepoItemInfo AddCheckBox2Info
            {
                get
                {
                    return _addcheckbox2Info;
                }
            }

            /// <summary>
            /// The Additional3 item.
            /// </summary>
            [RepositoryItem("cdc6fcc8-3753-4eb6-ad03-2484d7067b7b")]
            public virtual Ranorex.Text Additional3
            {
                get
                {
                    return _additional3Info.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The Additional3 item info.
            /// </summary>
            [RepositoryItemInfo("cdc6fcc8-3753-4eb6-ad03-2484d7067b7b")]
            public virtual RepoItemInfo Additional3Info
            {
                get
                {
                    return _additional3Info;
                }
            }

            /// <summary>
            /// The AddCheckBox3 item.
            /// </summary>
            [RepositoryItem("80d24a4d-dbf3-4d89-89a8-3be889f0debf")]
            public virtual Ranorex.CheckBox AddCheckBox3
            {
                get
                {
                    return _addcheckbox3Info.CreateAdapter<Ranorex.CheckBox>(true);
                }
            }

            /// <summary>
            /// The AddCheckBox3 item info.
            /// </summary>
            [RepositoryItemInfo("80d24a4d-dbf3-4d89-89a8-3be889f0debf")]
            public virtual RepoItemInfo AddCheckBox3Info
            {
                get
                {
                    return _addcheckbox3Info;
                }
            }
        }

        /// <summary>
        /// The T4RL1Folder folder.
        /// </summary>
        [RepositoryFolder("727f61b1-8179-4819-a8ed-d0b625612f18")]
        public partial class T4RL1Folder : RepoGenBaseFolder
        {
            RepoItemInfo _tabInfo;
            RepoItemInfo _eiinsearningsInfo;
            RepoItemInfo _pensionableearningsInfo;
            RepoItemInfo _qpipinsearningsInfo;
            RepoItemInfo _rppdpspInfo;
            RepoItemInfo _pensionadjustmentInfo;
            RepoItemInfo _t4empcodeInfo;
            RepoItemInfo _historicaleiinsearningsInfo;
            RepoItemInfo _historicalpensionableearningsInfo;
            RepoItemInfo _historicalqpipearningsInfo;

            /// <summary>
            /// Creates a new T4RL1  folder.
            /// </summary>
            public T4RL1Folder(RepoGenBaseFolder parentFolder) :
                    base("T4RL1", "", parentFolder, 1000, null, false, "727f61b1-8179-4819-a8ed-d0b625612f18", "")
            {
                _tabInfo = new RepoItemInfo(this, "Tab", "?/?/tabpage[@title='T4 and RL-1 Reporting ']", 3000, null, "84690b7e-4bd1-4853-9adc-94dd917376dd");
                _eiinsearningsInfo = new RepoItemInfo(this, "EIInsEarnings", "text[@controlid='950']", 3000, null, "65617393-5f9d-4a85-8477-d4701747a11e");
                _pensionableearningsInfo = new RepoItemInfo(this, "PensionableEarnings", "text[@controlid='956']", 3000, null, "6268f775-e38b-486b-9fd4-74411901a246");
                _qpipinsearningsInfo = new RepoItemInfo(this, "QPIPInsEarnings", "text[@controlid='982']", 3000, null, "1208ea33-1f9a-4dac-8a9f-75646159298b");
                _rppdpspInfo = new RepoItemInfo(this, "RPPDPSP", "element[@controlid='954']/text", 3000, null, "a3ce5b2c-d6fa-4f56-b866-dc93ef554a5c");
                _pensionadjustmentInfo = new RepoItemInfo(this, "PensionAdjustment", "element[@controlid='959']/text", 3000, null, "1e1d5b38-f418-45ba-968d-9e513901b1eb");
                _t4empcodeInfo = new RepoItemInfo(this, "T4EmpCode", "combobox[@controlid='970']", 3000, null, "085bb3c7-1ff7-42c4-a2af-11967dc4d338");
                _historicaleiinsearningsInfo = new RepoItemInfo(this, "HistoricalEIInsEarnings", "text[@controlid='952']", 3000, null, "129d0343-4233-4441-9c63-2800134327dc");
                _historicalpensionableearningsInfo = new RepoItemInfo(this, "HistoricalPensionableEarnings", "text[@controlid='961']", 3000, null, "51e2ce70-8889-4b3a-a63d-2b1b30400eeb");
                _historicalqpipearningsInfo = new RepoItemInfo(this, "HistoricalQpipEarnings", "text[@controlid='984']", 3000, null, "f15c8d5f-e412-47ec-96ea-a4fd49384814");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("727f61b1-8179-4819-a8ed-d0b625612f18")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("727f61b1-8179-4819-a8ed-d0b625612f18")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The Tab item.
            /// </summary>
            [RepositoryItem("84690b7e-4bd1-4853-9adc-94dd917376dd")]
            public virtual Ranorex.TabPage Tab
            {
                get
                {
                    return _tabInfo.CreateAdapter<Ranorex.TabPage>(true);
                }
            }

            /// <summary>
            /// The Tab item info.
            /// </summary>
            [RepositoryItemInfo("84690b7e-4bd1-4853-9adc-94dd917376dd")]
            public virtual RepoItemInfo TabInfo
            {
                get
                {
                    return _tabInfo;
                }
            }

            /// <summary>
            /// The EIInsEarnings item.
            /// </summary>
            [RepositoryItem("65617393-5f9d-4a85-8477-d4701747a11e")]
            public virtual Ranorex.Text EIInsEarnings
            {
                get
                {
                    return _eiinsearningsInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The EIInsEarnings item info.
            /// </summary>
            [RepositoryItemInfo("65617393-5f9d-4a85-8477-d4701747a11e")]
            public virtual RepoItemInfo EIInsEarningsInfo
            {
                get
                {
                    return _eiinsearningsInfo;
                }
            }

            /// <summary>
            /// The PensionableEarnings item.
            /// </summary>
            [RepositoryItem("6268f775-e38b-486b-9fd4-74411901a246")]
            public virtual Ranorex.Text PensionableEarnings
            {
                get
                {
                    return _pensionableearningsInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The PensionableEarnings item info.
            /// </summary>
            [RepositoryItemInfo("6268f775-e38b-486b-9fd4-74411901a246")]
            public virtual RepoItemInfo PensionableEarningsInfo
            {
                get
                {
                    return _pensionableearningsInfo;
                }
            }

            /// <summary>
            /// The QPIPInsEarnings item.
            /// </summary>
            [RepositoryItem("1208ea33-1f9a-4dac-8a9f-75646159298b")]
            public virtual Ranorex.Text QPIPInsEarnings
            {
                get
                {
                    return _qpipinsearningsInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The QPIPInsEarnings item info.
            /// </summary>
            [RepositoryItemInfo("1208ea33-1f9a-4dac-8a9f-75646159298b")]
            public virtual RepoItemInfo QPIPInsEarningsInfo
            {
                get
                {
                    return _qpipinsearningsInfo;
                }
            }

            /// <summary>
            /// The RPPDPSP item.
            /// </summary>
            [RepositoryItem("a3ce5b2c-d6fa-4f56-b866-dc93ef554a5c")]
            public virtual Ranorex.Text RPPDPSP
            {
                get
                {
                    return _rppdpspInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The RPPDPSP item info.
            /// </summary>
            [RepositoryItemInfo("a3ce5b2c-d6fa-4f56-b866-dc93ef554a5c")]
            public virtual RepoItemInfo RPPDPSPInfo
            {
                get
                {
                    return _rppdpspInfo;
                }
            }

            /// <summary>
            /// The PensionAdjustment item.
            /// </summary>
            [RepositoryItem("1e1d5b38-f418-45ba-968d-9e513901b1eb")]
            public virtual Ranorex.Text PensionAdjustment
            {
                get
                {
                    return _pensionadjustmentInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The PensionAdjustment item info.
            /// </summary>
            [RepositoryItemInfo("1e1d5b38-f418-45ba-968d-9e513901b1eb")]
            public virtual RepoItemInfo PensionAdjustmentInfo
            {
                get
                {
                    return _pensionadjustmentInfo;
                }
            }

            /// <summary>
            /// The T4EmpCode item.
            /// </summary>
            [RepositoryItem("085bb3c7-1ff7-42c4-a2af-11967dc4d338")]
            public virtual Ranorex.ComboBox T4EmpCode
            {
                get
                {
                    return _t4empcodeInfo.CreateAdapter<Ranorex.ComboBox>(true);
                }
            }

            /// <summary>
            /// The T4EmpCode item info.
            /// </summary>
            [RepositoryItemInfo("085bb3c7-1ff7-42c4-a2af-11967dc4d338")]
            public virtual RepoItemInfo T4EmpCodeInfo
            {
                get
                {
                    return _t4empcodeInfo;
                }
            }

            /// <summary>
            /// The HistoricalEIInsEarnings item.
            /// </summary>
            [RepositoryItem("129d0343-4233-4441-9c63-2800134327dc")]
            public virtual Ranorex.Text HistoricalEIInsEarnings
            {
                get
                {
                    return _historicaleiinsearningsInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The HistoricalEIInsEarnings item info.
            /// </summary>
            [RepositoryItemInfo("129d0343-4233-4441-9c63-2800134327dc")]
            public virtual RepoItemInfo HistoricalEIInsEarningsInfo
            {
                get
                {
                    return _historicaleiinsearningsInfo;
                }
            }

            /// <summary>
            /// The HistoricalPensionableEarnings item.
            /// </summary>
            [RepositoryItem("51e2ce70-8889-4b3a-a63d-2b1b30400eeb")]
            public virtual Ranorex.Text HistoricalPensionableEarnings
            {
                get
                {
                    return _historicalpensionableearningsInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The HistoricalPensionableEarnings item info.
            /// </summary>
            [RepositoryItemInfo("51e2ce70-8889-4b3a-a63d-2b1b30400eeb")]
            public virtual RepoItemInfo HistoricalPensionableEarningsInfo
            {
                get
                {
                    return _historicalpensionableearningsInfo;
                }
            }

            /// <summary>
            /// The HistoricalQpipEarnings item.
            /// </summary>
            [RepositoryItem("f15c8d5f-e412-47ec-96ea-a4fd49384814")]
            public virtual Ranorex.Text HistoricalQpipEarnings
            {
                get
                {
                    return _historicalqpipearningsInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The HistoricalQpipEarnings item info.
            /// </summary>
            [RepositoryItemInfo("f15c8d5f-e412-47ec-96ea-a4fd49384814")]
            public virtual RepoItemInfo HistoricalQpipEarningsInfo
            {
                get
                {
                    return _historicalqpipearningsInfo;
                }
            }
        }

        /// <summary>
        /// The EmployeeIconAppFolder folder.
        /// </summary>
        [RepositoryFolder("8a5ba7ff-d262-47dd-8a87-839e0b10025b")]
        public partial class EmployeeIconAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _createnewInfo;

            /// <summary>
            /// Creates a new EmployeeIcon  folder.
            /// </summary>
            public EmployeeIconAppFolder(RepoGenBaseFolder parentFolder) :
                    base("EmployeeIcon", "/form[@title='Employees']", parentFolder, 3000, null, true, "8a5ba7ff-d262-47dd-8a87-839e0b10025b", "")
            {
                _createnewInfo = new RepoItemInfo(this, "CreateNew", "?/?/toolbar[@class='ToolbarWindow32' and @instance='0']/button[@text='Create (Ctrl+N)']", 3000, null, "e428c3b2-df57-4c7e-953f-3eb20ce0a32f");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("8a5ba7ff-d262-47dd-8a87-839e0b10025b")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("8a5ba7ff-d262-47dd-8a87-839e0b10025b")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The CreateNew item.
            /// </summary>
            [RepositoryItem("e428c3b2-df57-4c7e-953f-3eb20ce0a32f")]
            public virtual Ranorex.Button CreateNew
            {
                get
                {
                    return _createnewInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The CreateNew item info.
            /// </summary>
            [RepositoryItemInfo("e428c3b2-df57-4c7e-953f-3eb20ce0a32f")]
            public virtual RepoItemInfo CreateNewInfo
            {
                get
                {
                    return _createnewInfo;
                }
            }
        }

    }
#pragma warning restore 0436
}