///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Drawing;
using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace Sage50.Repository
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    /// The class representing the PayrollJournalRes element repository.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", "8.0")]
    [RepositoryFolder("f934d11d-6caf-475e-bf81-b8cd416596ee")]
    public partial class PayrollJournalRes : RepoGenBaseFolder
    {
        static PayrollJournalRes instance = new PayrollJournalRes();
        PayrollJournalResFolders.PayrollJournalAppFolder _payrolljournal;
        PayrollJournalResFolders.ProjAllocByHourAppFolder _projallocbyhour;

        /// <summary>
        /// Gets the singleton class instance representing the PayrollJournalRes element repository.
        /// </summary>
        [RepositoryFolder("f934d11d-6caf-475e-bf81-b8cd416596ee")]
        public static PayrollJournalRes Instance
        {
            get { return instance; }
        }

        /// <summary>
        /// Repository class constructor.
        /// </summary>
        public PayrollJournalRes() 
            : base("PayrollJournalRes", "/", null, 0, false, "f934d11d-6caf-475e-bf81-b8cd416596ee", ".\\RepositoryImages\\PayrollJournalResf934d11d.rximgres")
        {
            _payrolljournal = new PayrollJournalResFolders.PayrollJournalAppFolder(this);
            _projallocbyhour = new PayrollJournalResFolders.ProjAllocByHourAppFolder(this);
        }

#region Variables

#endregion

        /// <summary>
        /// The Self item info.
        /// </summary>
        [RepositoryItemInfo("f934d11d-6caf-475e-bf81-b8cd416596ee")]
        public virtual RepoItemInfo SelfInfo
        {
            get
            {
                return _selfInfo;
            }
        }

        /// <summary>
        /// The PayrollJournal folder.
        /// </summary>
        [RepositoryFolder("556cecd8-f670-4b76-8416-f29f169ca0fc")]
        public virtual PayrollJournalResFolders.PayrollJournalAppFolder PayrollJournal
        {
            get { return _payrolljournal; }
        }

        /// <summary>
        /// The ProjAllocByHour folder.
        /// </summary>
        [RepositoryFolder("fba265e8-0eb8-4536-b958-1617768e4865")]
        public virtual PayrollJournalResFolders.ProjAllocByHourAppFolder ProjAllocByHour
        {
            get { return _projallocbyhour; }
        }
    }

    /// <summary>
    /// Inner folder classes.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", "8.0")]
    public partial class PayrollJournalResFolders
    {
        /// <summary>
        /// The PayrollJournalAppFolder folder.
        /// </summary>
        [RepositoryFolder("556cecd8-f670-4b76-8416-f29f169ca0fc")]
        public partial class PayrollJournalAppFolder : RepoGenBaseFolder
        {
            PayrollJournalResFolders.IncomeFolder _income;
            PayrollJournalResFolders.VacationFolder _vacation;
            PayrollJournalResFolders.DeductionsFolder _deductions;
            PayrollJournalResFolders.TaxesFolder _taxes;
            PayrollJournalResFolders.UserDefinedExpensesFolder _userdefinedexpenses;
            PayrollJournalResFolders.EntitlementsFolder _entitlements;
            PayrollJournalResFolders.QuebecTipsFolder _quebectips;
            RepoItemInfo _employeenameInfo;
            RepoItemInfo _paychequenumberInfo;
            RepoItemInfo _adjustInfo;
            RepoItemInfo _manualentertaxInfo;
            RepoItemInfo _printInfo;
            RepoItemInfo _undoInfo;
            RepoItemInfo _reverseInfo;
            RepoItemInfo _accountpaidfromInfo;
            RepoItemInfo _paychequedateInfo;
            RepoItemInfo _directdepositInfo;
            RepoItemInfo _periodendInfo;
            RepoItemInfo _postInfo;
            RepoItemInfo _recallInfo;
            RepoItemInfo _netpayInfo;
            RepoItemInfo _allocatetoprojectsInfo;

            /// <summary>
            /// Creates a new PayrollJournal  folder.
            /// </summary>
            public PayrollJournalAppFolder(RepoGenBaseFolder parentFolder) :
                    base("PayrollJournal", "/form[@controlname='PayrollFormCdn']", parentFolder, 3000, null, true, "556cecd8-f670-4b76-8416-f29f169ca0fc", "")
            {
                _income = new PayrollJournalResFolders.IncomeFolder(this);
                _vacation = new PayrollJournalResFolders.VacationFolder(this);
                _deductions = new PayrollJournalResFolders.DeductionsFolder(this);
                _taxes = new PayrollJournalResFolders.TaxesFolder(this);
                _userdefinedexpenses = new PayrollJournalResFolders.UserDefinedExpensesFolder(this);
                _entitlements = new PayrollJournalResFolders.EntitlementsFolder(this);
                _quebectips = new PayrollJournalResFolders.QuebecTipsFolder(this);
                _employeenameInfo = new RepoItemInfo(this, "EmployeeName", "combobox[@controlname='m_employeeList']", 10000, null, "cbf80e31-7b5c-4d08-89f5-a2f63843020f");
                _paychequenumberInfo = new RepoItemInfo(this, "PaychequeNumber", "?/?/text[@accessiblename='Cheque Number:']", 3000, null, "3903fc16-b4dd-4a98-b550-975b8d9c7f94");
                _adjustInfo = new RepoItemInfo(this, "Adjust", "?/?/button[@accessiblename='Adjust']", 3000, null, "1a8b6014-30d1-4e2f-a149-6a0cfc87c183");
                _manualentertaxInfo = new RepoItemInfo(this, "ManualEnterTax", "toolbar/button[10]", 3000, null, "4ad17326-5cfa-46f1-982a-e4a4e5e1a347");
                _printInfo = new RepoItemInfo(this, "Print", "?/?/button[@accessiblename='Print']", 3000, null, "715a116d-a96c-4761-af33-2be6a15a3bfa");
                _undoInfo = new RepoItemInfo(this, "Undo", "?/?/button[@accessiblename='Clear']", 3000, null, "e02ea82b-cdde-4cf3-a2d1-81a32a0fad28");
                _reverseInfo = new RepoItemInfo(this, "Reverse", "?/?/button[@accessiblename='Void']", 3000, null, "d307eae6-64c2-4c64-a1de-ed0b0ecccca9");
                _accountpaidfromInfo = new RepoItemInfo(this, "AccountPaidFrom", "combobox[@controlname='m_paidFromAccount']", 3000, null, "062fcbdc-a7d1-4415-9832-4e6674c98727");
                _paychequedateInfo = new RepoItemInfo(this, "PaychequeDate", "container[@controlname='m_datePicker']/?/?/text[@accessiblerole='Text']", 3000, null, "75380240-64d6-4ccc-9aad-363bc51ac404");
                _directdepositInfo = new RepoItemInfo(this, "DirectDeposit", "checkbox[@controlname='m_directDeposit']", 3000, null, "82fc62c3-e719-40f2-9e5a-152cde0ad6af");
                _periodendInfo = new RepoItemInfo(this, "PeriodEnd", "container[@controlname='m_periodEndDate']/?/?/text[@accessiblerole='Text']", 3000, null, "6b63bb3d-2cd3-4071-986e-24a89af974b9");
                _postInfo = new RepoItemInfo(this, "Post", "button[@controlname='m_postButton']", 3000, null, "4e39ff8c-6bec-492c-a3fb-022f3949323b");
                _recallInfo = new RepoItemInfo(this, "Recall", "?/?/button[@accessiblename='Recall']", 3000, null, "3faba8ec-a79b-4180-b463-65ca3f505458");
                _netpayInfo = new RepoItemInfo(this, "NetPay", "text[@controlname='m_netPay']", 3000, null, "6c6485d2-7b1e-4877-acb7-e4fc13f82017");
                _allocatetoprojectsInfo = new RepoItemInfo(this, "AllocateToProjects", "?/?/button[@accessiblename='Alloc.']", 30000, null, "856c7e67-f283-4da5-9e9a-d410ce124ca0");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("556cecd8-f670-4b76-8416-f29f169ca0fc")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("556cecd8-f670-4b76-8416-f29f169ca0fc")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The EmployeeName item.
            /// </summary>
            [RepositoryItem("cbf80e31-7b5c-4d08-89f5-a2f63843020f")]
            public virtual Ranorex.ComboBox EmployeeName
            {
                get
                {
                    return _employeenameInfo.CreateAdapter<Ranorex.ComboBox>(true);
                }
            }

            /// <summary>
            /// The EmployeeName item info.
            /// </summary>
            [RepositoryItemInfo("cbf80e31-7b5c-4d08-89f5-a2f63843020f")]
            public virtual RepoItemInfo EmployeeNameInfo
            {
                get
                {
                    return _employeenameInfo;
                }
            }

            /// <summary>
            /// The PaychequeNumber item.
            /// </summary>
            [RepositoryItem("3903fc16-b4dd-4a98-b550-975b8d9c7f94")]
            public virtual Ranorex.Text PaychequeNumber
            {
                get
                {
                    return _paychequenumberInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The PaychequeNumber item info.
            /// </summary>
            [RepositoryItemInfo("3903fc16-b4dd-4a98-b550-975b8d9c7f94")]
            public virtual RepoItemInfo PaychequeNumberInfo
            {
                get
                {
                    return _paychequenumberInfo;
                }
            }

            /// <summary>
            /// The Adjust item.
            /// </summary>
            [RepositoryItem("1a8b6014-30d1-4e2f-a149-6a0cfc87c183")]
            public virtual Ranorex.Button Adjust
            {
                get
                {
                    return _adjustInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The Adjust item info.
            /// </summary>
            [RepositoryItemInfo("1a8b6014-30d1-4e2f-a149-6a0cfc87c183")]
            public virtual RepoItemInfo AdjustInfo
            {
                get
                {
                    return _adjustInfo;
                }
            }

            /// <summary>
            /// The ManualEnterTax item.
            /// </summary>
            [RepositoryItem("4ad17326-5cfa-46f1-982a-e4a4e5e1a347")]
            public virtual Ranorex.Button ManualEnterTax
            {
                get
                {
                    return _manualentertaxInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The ManualEnterTax item info.
            /// </summary>
            [RepositoryItemInfo("4ad17326-5cfa-46f1-982a-e4a4e5e1a347")]
            public virtual RepoItemInfo ManualEnterTaxInfo
            {
                get
                {
                    return _manualentertaxInfo;
                }
            }

            /// <summary>
            /// The Print item.
            /// </summary>
            [RepositoryItem("715a116d-a96c-4761-af33-2be6a15a3bfa")]
            public virtual Ranorex.Button Print
            {
                get
                {
                    return _printInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The Print item info.
            /// </summary>
            [RepositoryItemInfo("715a116d-a96c-4761-af33-2be6a15a3bfa")]
            public virtual RepoItemInfo PrintInfo
            {
                get
                {
                    return _printInfo;
                }
            }

            /// <summary>
            /// The Undo item.
            /// </summary>
            [RepositoryItem("e02ea82b-cdde-4cf3-a2d1-81a32a0fad28")]
            public virtual Ranorex.Button Undo
            {
                get
                {
                    return _undoInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The Undo item info.
            /// </summary>
            [RepositoryItemInfo("e02ea82b-cdde-4cf3-a2d1-81a32a0fad28")]
            public virtual RepoItemInfo UndoInfo
            {
                get
                {
                    return _undoInfo;
                }
            }

            /// <summary>
            /// The Reverse item.
            /// </summary>
            [RepositoryItem("d307eae6-64c2-4c64-a1de-ed0b0ecccca9")]
            public virtual Ranorex.Button Reverse
            {
                get
                {
                    return _reverseInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The Reverse item info.
            /// </summary>
            [RepositoryItemInfo("d307eae6-64c2-4c64-a1de-ed0b0ecccca9")]
            public virtual RepoItemInfo ReverseInfo
            {
                get
                {
                    return _reverseInfo;
                }
            }

            /// <summary>
            /// The AccountPaidFrom item.
            /// </summary>
            [RepositoryItem("062fcbdc-a7d1-4415-9832-4e6674c98727")]
            public virtual Ranorex.ComboBox AccountPaidFrom
            {
                get
                {
                    return _accountpaidfromInfo.CreateAdapter<Ranorex.ComboBox>(true);
                }
            }

            /// <summary>
            /// The AccountPaidFrom item info.
            /// </summary>
            [RepositoryItemInfo("062fcbdc-a7d1-4415-9832-4e6674c98727")]
            public virtual RepoItemInfo AccountPaidFromInfo
            {
                get
                {
                    return _accountpaidfromInfo;
                }
            }

            /// <summary>
            /// The PaychequeDate item.
            /// </summary>
            [RepositoryItem("75380240-64d6-4ccc-9aad-363bc51ac404")]
            public virtual Ranorex.Text PaychequeDate
            {
                get
                {
                    return _paychequedateInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The PaychequeDate item info.
            /// </summary>
            [RepositoryItemInfo("75380240-64d6-4ccc-9aad-363bc51ac404")]
            public virtual RepoItemInfo PaychequeDateInfo
            {
                get
                {
                    return _paychequedateInfo;
                }
            }

            /// <summary>
            /// The DirectDeposit item.
            /// </summary>
            [RepositoryItem("82fc62c3-e719-40f2-9e5a-152cde0ad6af")]
            public virtual Ranorex.CheckBox DirectDeposit
            {
                get
                {
                    return _directdepositInfo.CreateAdapter<Ranorex.CheckBox>(true);
                }
            }

            /// <summary>
            /// The DirectDeposit item info.
            /// </summary>
            [RepositoryItemInfo("82fc62c3-e719-40f2-9e5a-152cde0ad6af")]
            public virtual RepoItemInfo DirectDepositInfo
            {
                get
                {
                    return _directdepositInfo;
                }
            }

            /// <summary>
            /// The PeriodEnd item.
            /// </summary>
            [RepositoryItem("6b63bb3d-2cd3-4071-986e-24a89af974b9")]
            public virtual Ranorex.Text PeriodEnd
            {
                get
                {
                    return _periodendInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The PeriodEnd item info.
            /// </summary>
            [RepositoryItemInfo("6b63bb3d-2cd3-4071-986e-24a89af974b9")]
            public virtual RepoItemInfo PeriodEndInfo
            {
                get
                {
                    return _periodendInfo;
                }
            }

            /// <summary>
            /// The Post item.
            /// </summary>
            [RepositoryItem("4e39ff8c-6bec-492c-a3fb-022f3949323b")]
            public virtual Ranorex.Button Post
            {
                get
                {
                    return _postInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The Post item info.
            /// </summary>
            [RepositoryItemInfo("4e39ff8c-6bec-492c-a3fb-022f3949323b")]
            public virtual RepoItemInfo PostInfo
            {
                get
                {
                    return _postInfo;
                }
            }

            /// <summary>
            /// The Recall item.
            /// </summary>
            [RepositoryItem("3faba8ec-a79b-4180-b463-65ca3f505458")]
            public virtual Ranorex.Button Recall
            {
                get
                {
                    return _recallInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The Recall item info.
            /// </summary>
            [RepositoryItemInfo("3faba8ec-a79b-4180-b463-65ca3f505458")]
            public virtual RepoItemInfo RecallInfo
            {
                get
                {
                    return _recallInfo;
                }
            }

            /// <summary>
            /// The NetPay item.
            /// </summary>
            [RepositoryItem("6c6485d2-7b1e-4877-acb7-e4fc13f82017")]
            public virtual Ranorex.Text NetPay
            {
                get
                {
                    return _netpayInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The NetPay item info.
            /// </summary>
            [RepositoryItemInfo("6c6485d2-7b1e-4877-acb7-e4fc13f82017")]
            public virtual RepoItemInfo NetPayInfo
            {
                get
                {
                    return _netpayInfo;
                }
            }

            /// <summary>
            /// The AllocateToProjects item.
            /// </summary>
            [RepositoryItem("856c7e67-f283-4da5-9e9a-d410ce124ca0")]
            public virtual Ranorex.Button AllocateToProjects
            {
                get
                {
                    return _allocatetoprojectsInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The AllocateToProjects item info.
            /// </summary>
            [RepositoryItemInfo("856c7e67-f283-4da5-9e9a-d410ce124ca0")]
            public virtual RepoItemInfo AllocateToProjectsInfo
            {
                get
                {
                    return _allocatetoprojectsInfo;
                }
            }

            /// <summary>
            /// The Income folder.
            /// </summary>
            [RepositoryFolder("faa3f554-6593-46fe-aa75-c66bed7178b2")]
            public virtual PayrollJournalResFolders.IncomeFolder Income
            {
                get { return _income; }
            }

            /// <summary>
            /// The Vacation folder.
            /// </summary>
            [RepositoryFolder("e89e77a5-aff3-4b33-baec-77747c572278")]
            public virtual PayrollJournalResFolders.VacationFolder Vacation
            {
                get { return _vacation; }
            }

            /// <summary>
            /// The Deductions folder.
            /// </summary>
            [RepositoryFolder("2638bad0-24d2-4ab6-a951-7c6326a1c917")]
            public virtual PayrollJournalResFolders.DeductionsFolder Deductions
            {
                get { return _deductions; }
            }

            /// <summary>
            /// The Taxes folder.
            /// </summary>
            [RepositoryFolder("3807ba53-0228-47de-a201-75099bb1b9b6")]
            public virtual PayrollJournalResFolders.TaxesFolder Taxes
            {
                get { return _taxes; }
            }

            /// <summary>
            /// The UserDefinedExpenses folder.
            /// </summary>
            [RepositoryFolder("1e26c8ff-a3a9-4a2d-9158-91814e7c24c6")]
            public virtual PayrollJournalResFolders.UserDefinedExpensesFolder UserDefinedExpenses
            {
                get { return _userdefinedexpenses; }
            }

            /// <summary>
            /// The Entitlements folder.
            /// </summary>
            [RepositoryFolder("204207bd-6065-4829-98ae-3c470ac82593")]
            public virtual PayrollJournalResFolders.EntitlementsFolder Entitlements
            {
                get { return _entitlements; }
            }

            /// <summary>
            /// The QuebecTips folder.
            /// </summary>
            [RepositoryFolder("b0e766f8-7b8f-45df-b7c2-25ac212afbda")]
            public virtual PayrollJournalResFolders.QuebecTipsFolder QuebecTips
            {
                get { return _quebectips; }
            }
        }

        /// <summary>
        /// The IncomeFolder folder.
        /// </summary>
        [RepositoryFolder("faa3f554-6593-46fe-aa75-c66bed7178b2")]
        public partial class IncomeFolder : RepoGenBaseFolder
        {
            RepoItemInfo _tabInfo;
            RepoItemInfo _earningincomegridInfo;
            RepoItemInfo _otherincomegridInfo;

            /// <summary>
            /// Creates a new Income  folder.
            /// </summary>
            public IncomeFolder(RepoGenBaseFolder parentFolder) :
                    base("Income", "", parentFolder, 3000, null, false, "faa3f554-6593-46fe-aa75-c66bed7178b2", "")
            {
                _tabInfo = new RepoItemInfo(this, "Tab", "container[@controlname='m_paychequeTabs']/?/?/tabpage[@accessiblename='Income']", 3000, null, "1a7d362b-7d00-496f-a72e-05f6a50979e6");
                _earningincomegridInfo = new RepoItemInfo(this, "EarningIncomeGrid", "container[@controlname='m_paychequeTabs']/?/?/tabpage[@controlname='m_incomeTabPage']//table[@controlname='m_simplyGridView']", 3000, null, "50eceaf3-f573-4fdb-98d0-c659b41a34cd");
                _otherincomegridInfo = new RepoItemInfo(this, "OtherIncomeGrid", "container[@controlname='m_paychequeTabs']/?/?/tabpage[@controlname='m_incomeTabPage']/?/?/container[@controlname='m_otherIncomeGrid']/table[@controlname='m_simplyGridView']", 3000, null, "88bf6188-887c-4204-aa7d-9803f3e48e20");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("faa3f554-6593-46fe-aa75-c66bed7178b2")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("faa3f554-6593-46fe-aa75-c66bed7178b2")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The Tab item.
            /// </summary>
            [RepositoryItem("1a7d362b-7d00-496f-a72e-05f6a50979e6")]
            public virtual Ranorex.TabPage Tab
            {
                get
                {
                    return _tabInfo.CreateAdapter<Ranorex.TabPage>(true);
                }
            }

            /// <summary>
            /// The Tab item info.
            /// </summary>
            [RepositoryItemInfo("1a7d362b-7d00-496f-a72e-05f6a50979e6")]
            public virtual RepoItemInfo TabInfo
            {
                get
                {
                    return _tabInfo;
                }
            }

            /// <summary>
            /// The EarningIncomeGrid item.
            /// </summary>
            [RepositoryItem("50eceaf3-f573-4fdb-98d0-c659b41a34cd")]
            public virtual Ranorex.Table EarningIncomeGrid
            {
                get
                {
                    return _earningincomegridInfo.CreateAdapter<Ranorex.Table>(true);
                }
            }

            /// <summary>
            /// The EarningIncomeGrid item info.
            /// </summary>
            [RepositoryItemInfo("50eceaf3-f573-4fdb-98d0-c659b41a34cd")]
            public virtual RepoItemInfo EarningIncomeGridInfo
            {
                get
                {
                    return _earningincomegridInfo;
                }
            }

            /// <summary>
            /// The OtherIncomeGrid item.
            /// </summary>
            [RepositoryItem("88bf6188-887c-4204-aa7d-9803f3e48e20")]
            public virtual Ranorex.Table OtherIncomeGrid
            {
                get
                {
                    return _otherincomegridInfo.CreateAdapter<Ranorex.Table>(true);
                }
            }

            /// <summary>
            /// The OtherIncomeGrid item info.
            /// </summary>
            [RepositoryItemInfo("88bf6188-887c-4204-aa7d-9803f3e48e20")]
            public virtual RepoItemInfo OtherIncomeGridInfo
            {
                get
                {
                    return _otherincomegridInfo;
                }
            }
        }

        /// <summary>
        /// The VacationFolder folder.
        /// </summary>
        [RepositoryFolder("e89e77a5-aff3-4b33-baec-77747c572278")]
        public partial class VacationFolder : RepoGenBaseFolder
        {
            RepoItemInfo _tabInfo;
            RepoItemInfo _vacationgridInfo;

            /// <summary>
            /// Creates a new Vacation  folder.
            /// </summary>
            public VacationFolder(RepoGenBaseFolder parentFolder) :
                    base("Vacation", "", parentFolder, 3000, null, false, "e89e77a5-aff3-4b33-baec-77747c572278", "")
            {
                _tabInfo = new RepoItemInfo(this, "Tab", "container[@controlname='m_paychequeTabs']/?/?/tabpage[@accessiblename='Vacation']", 3000, null, "4c796c86-0d5e-4183-bd4e-a96cc71874ba");
                _vacationgridInfo = new RepoItemInfo(this, "VacationGrid", ".//tabpage[@controlname='m_vacationTabPage']/table[@controlname='m_vacationGrid']", 3000, null, "5e59ff24-f76e-447a-9611-25401c161853");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("e89e77a5-aff3-4b33-baec-77747c572278")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("e89e77a5-aff3-4b33-baec-77747c572278")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The Tab item.
            /// </summary>
            [RepositoryItem("4c796c86-0d5e-4183-bd4e-a96cc71874ba")]
            public virtual Ranorex.TabPage Tab
            {
                get
                {
                    return _tabInfo.CreateAdapter<Ranorex.TabPage>(true);
                }
            }

            /// <summary>
            /// The Tab item info.
            /// </summary>
            [RepositoryItemInfo("4c796c86-0d5e-4183-bd4e-a96cc71874ba")]
            public virtual RepoItemInfo TabInfo
            {
                get
                {
                    return _tabInfo;
                }
            }

            /// <summary>
            /// The VacationGrid item.
            /// </summary>
            [RepositoryItem("5e59ff24-f76e-447a-9611-25401c161853")]
            public virtual Ranorex.Table VacationGrid
            {
                get
                {
                    return _vacationgridInfo.CreateAdapter<Ranorex.Table>(true);
                }
            }

            /// <summary>
            /// The VacationGrid item info.
            /// </summary>
            [RepositoryItemInfo("5e59ff24-f76e-447a-9611-25401c161853")]
            public virtual RepoItemInfo VacationGridInfo
            {
                get
                {
                    return _vacationgridInfo;
                }
            }
        }

        /// <summary>
        /// The DeductionsFolder folder.
        /// </summary>
        [RepositoryFolder("2638bad0-24d2-4ab6-a951-7c6326a1c917")]
        public partial class DeductionsFolder : RepoGenBaseFolder
        {
            RepoItemInfo _tabInfo;
            RepoItemInfo _deductiongridInfo;

            /// <summary>
            /// Creates a new Deductions  folder.
            /// </summary>
            public DeductionsFolder(RepoGenBaseFolder parentFolder) :
                    base("Deductions", "", parentFolder, 3000, null, false, "2638bad0-24d2-4ab6-a951-7c6326a1c917", "")
            {
                _tabInfo = new RepoItemInfo(this, "Tab", "container[@controlname='m_paychequeTabs']/?/?/tabpage[@accessiblename='Deductions']", 3000, null, "04e555f5-200a-40a0-ab0b-a1070caf9704");
                _deductiongridInfo = new RepoItemInfo(this, "DeductionGrid", "container[@controlname='m_paychequeTabs']/?/?/tabpage[@controlname='m_deductionTabPage']/?/?/table[@controlname='m_simplyGridView']", 3000, null, "e284c104-7f62-49ff-a472-f7a083dfde31");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("2638bad0-24d2-4ab6-a951-7c6326a1c917")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("2638bad0-24d2-4ab6-a951-7c6326a1c917")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The Tab item.
            /// </summary>
            [RepositoryItem("04e555f5-200a-40a0-ab0b-a1070caf9704")]
            public virtual Ranorex.TabPage Tab
            {
                get
                {
                    return _tabInfo.CreateAdapter<Ranorex.TabPage>(true);
                }
            }

            /// <summary>
            /// The Tab item info.
            /// </summary>
            [RepositoryItemInfo("04e555f5-200a-40a0-ab0b-a1070caf9704")]
            public virtual RepoItemInfo TabInfo
            {
                get
                {
                    return _tabInfo;
                }
            }

            /// <summary>
            /// The DeductionGrid item.
            /// </summary>
            [RepositoryItem("e284c104-7f62-49ff-a472-f7a083dfde31")]
            public virtual Ranorex.Table DeductionGrid
            {
                get
                {
                    return _deductiongridInfo.CreateAdapter<Ranorex.Table>(true);
                }
            }

            /// <summary>
            /// The DeductionGrid item info.
            /// </summary>
            [RepositoryItemInfo("e284c104-7f62-49ff-a472-f7a083dfde31")]
            public virtual RepoItemInfo DeductionGridInfo
            {
                get
                {
                    return _deductiongridInfo;
                }
            }
        }

        /// <summary>
        /// The TaxesFolder folder.
        /// </summary>
        [RepositoryFolder("3807ba53-0228-47de-a201-75099bb1b9b6")]
        public partial class TaxesFolder : RepoGenBaseFolder
        {
            RepoItemInfo _tabInfo;
            RepoItemInfo _taxesgridInfo;

            /// <summary>
            /// Creates a new Taxes  folder.
            /// </summary>
            public TaxesFolder(RepoGenBaseFolder parentFolder) :
                    base("Taxes", "", parentFolder, 3000, null, false, "3807ba53-0228-47de-a201-75099bb1b9b6", "")
            {
                _tabInfo = new RepoItemInfo(this, "Tab", "container[@controlname='m_paychequeTabs']/?/?/tabpage[@accessiblename='Taxes']", 3000, null, "158ba468-c5b5-4fd1-be15-802ad8aa1a2e");
                _taxesgridInfo = new RepoItemInfo(this, "TaxesGrid", "container[@controlname='m_paychequeTabs']/?/?/tabpage[@controlname='m_taxTabPage']/?/?/table[@controlname='m_simplyGridView']", 3000, null, "0cbe7dd4-ab23-44a0-ae74-57340579b740");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("3807ba53-0228-47de-a201-75099bb1b9b6")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("3807ba53-0228-47de-a201-75099bb1b9b6")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The Tab item.
            /// </summary>
            [RepositoryItem("158ba468-c5b5-4fd1-be15-802ad8aa1a2e")]
            public virtual Ranorex.TabPage Tab
            {
                get
                {
                    return _tabInfo.CreateAdapter<Ranorex.TabPage>(true);
                }
            }

            /// <summary>
            /// The Tab item info.
            /// </summary>
            [RepositoryItemInfo("158ba468-c5b5-4fd1-be15-802ad8aa1a2e")]
            public virtual RepoItemInfo TabInfo
            {
                get
                {
                    return _tabInfo;
                }
            }

            /// <summary>
            /// The TaxesGrid item.
            /// </summary>
            [RepositoryItem("0cbe7dd4-ab23-44a0-ae74-57340579b740")]
            public virtual Ranorex.Table TaxesGrid
            {
                get
                {
                    return _taxesgridInfo.CreateAdapter<Ranorex.Table>(true);
                }
            }

            /// <summary>
            /// The TaxesGrid item info.
            /// </summary>
            [RepositoryItemInfo("0cbe7dd4-ab23-44a0-ae74-57340579b740")]
            public virtual RepoItemInfo TaxesGridInfo
            {
                get
                {
                    return _taxesgridInfo;
                }
            }
        }

        /// <summary>
        /// The UserDefinedExpensesFolder folder.
        /// </summary>
        [RepositoryFolder("1e26c8ff-a3a9-4a2d-9158-91814e7c24c6")]
        public partial class UserDefinedExpensesFolder : RepoGenBaseFolder
        {
            RepoItemInfo _tabInfo;
            RepoItemInfo _expensesgridInfo;

            /// <summary>
            /// Creates a new UserDefinedExpenses  folder.
            /// </summary>
            public UserDefinedExpensesFolder(RepoGenBaseFolder parentFolder) :
                    base("UserDefinedExpenses", "", parentFolder, 3000, null, false, "1e26c8ff-a3a9-4a2d-9158-91814e7c24c6", "")
            {
                _tabInfo = new RepoItemInfo(this, "Tab", "container[@controlname='m_paychequeTabs']/?/?/tabpage[@accessiblename='User-Defined Expenses']", 3000, null, "a7c5314d-e7c2-450a-885a-55ea2ffa2b30");
                _expensesgridInfo = new RepoItemInfo(this, "ExpensesGrid", "container[@controlname='m_paychequeTabs']/?/?/tabpage[@controlname='m_expenseTabPage']/?/?/table[@controlname='m_simplyGridView']", 3000, null, "7c89efa1-dfe6-439c-88bf-8e1169a78633");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("1e26c8ff-a3a9-4a2d-9158-91814e7c24c6")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("1e26c8ff-a3a9-4a2d-9158-91814e7c24c6")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The Tab item.
            /// </summary>
            [RepositoryItem("a7c5314d-e7c2-450a-885a-55ea2ffa2b30")]
            public virtual Ranorex.TabPage Tab
            {
                get
                {
                    return _tabInfo.CreateAdapter<Ranorex.TabPage>(true);
                }
            }

            /// <summary>
            /// The Tab item info.
            /// </summary>
            [RepositoryItemInfo("a7c5314d-e7c2-450a-885a-55ea2ffa2b30")]
            public virtual RepoItemInfo TabInfo
            {
                get
                {
                    return _tabInfo;
                }
            }

            /// <summary>
            /// The ExpensesGrid item.
            /// </summary>
            [RepositoryItem("7c89efa1-dfe6-439c-88bf-8e1169a78633")]
            public virtual Ranorex.Table ExpensesGrid
            {
                get
                {
                    return _expensesgridInfo.CreateAdapter<Ranorex.Table>(true);
                }
            }

            /// <summary>
            /// The ExpensesGrid item info.
            /// </summary>
            [RepositoryItemInfo("7c89efa1-dfe6-439c-88bf-8e1169a78633")]
            public virtual RepoItemInfo ExpensesGridInfo
            {
                get
                {
                    return _expensesgridInfo;
                }
            }
        }

        /// <summary>
        /// The EntitlementsFolder folder.
        /// </summary>
        [RepositoryFolder("204207bd-6065-4829-98ae-3c470ac82593")]
        public partial class EntitlementsFolder : RepoGenBaseFolder
        {
            RepoItemInfo _tabInfo;
            RepoItemInfo _hoursworkedthisperiodInfo;
            RepoItemInfo _entitlementgridInfo;

            /// <summary>
            /// Creates a new Entitlements  folder.
            /// </summary>
            public EntitlementsFolder(RepoGenBaseFolder parentFolder) :
                    base("Entitlements", "", parentFolder, 3000, null, false, "204207bd-6065-4829-98ae-3c470ac82593", "")
            {
                _tabInfo = new RepoItemInfo(this, "Tab", "container[@controlname='m_paychequeTabs']/?/?/tabpage[@accessiblename='Entitlements']", 3000, null, "88114ad7-109c-4db3-87e3-4b0cac78c472");
                _hoursworkedthisperiodInfo = new RepoItemInfo(this, "HoursWorkedThisPeriod", "container[@controlname='m_paychequeTabs']/?/?/tabpage[@controlname='m_entitlementTabPage']/?/?/text[@accessiblename='Hours worked this period:']", 3000, null, "b17c2787-7283-495f-ba14-4139f39642b9");
                _entitlementgridInfo = new RepoItemInfo(this, "EntitlementGrid", ".//tabpage[@controlname='m_entitlementTabPage']/table[@controlname='m_entitlementGrid']", 30000, null, "6993f1ed-c28a-4f71-833f-9f6e9c438e98");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("204207bd-6065-4829-98ae-3c470ac82593")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("204207bd-6065-4829-98ae-3c470ac82593")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The Tab item.
            /// </summary>
            [RepositoryItem("88114ad7-109c-4db3-87e3-4b0cac78c472")]
            public virtual Ranorex.TabPage Tab
            {
                get
                {
                    return _tabInfo.CreateAdapter<Ranorex.TabPage>(true);
                }
            }

            /// <summary>
            /// The Tab item info.
            /// </summary>
            [RepositoryItemInfo("88114ad7-109c-4db3-87e3-4b0cac78c472")]
            public virtual RepoItemInfo TabInfo
            {
                get
                {
                    return _tabInfo;
                }
            }

            /// <summary>
            /// The HoursWorkedThisPeriod item.
            /// </summary>
            [RepositoryItem("b17c2787-7283-495f-ba14-4139f39642b9")]
            public virtual Ranorex.Text HoursWorkedThisPeriod
            {
                get
                {
                    return _hoursworkedthisperiodInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The HoursWorkedThisPeriod item info.
            /// </summary>
            [RepositoryItemInfo("b17c2787-7283-495f-ba14-4139f39642b9")]
            public virtual RepoItemInfo HoursWorkedThisPeriodInfo
            {
                get
                {
                    return _hoursworkedthisperiodInfo;
                }
            }

            /// <summary>
            /// The EntitlementGrid item.
            /// </summary>
            [RepositoryItem("6993f1ed-c28a-4f71-833f-9f6e9c438e98")]
            public virtual Ranorex.Table EntitlementGrid
            {
                get
                {
                    return _entitlementgridInfo.CreateAdapter<Ranorex.Table>(true);
                }
            }

            /// <summary>
            /// The EntitlementGrid item info.
            /// </summary>
            [RepositoryItemInfo("6993f1ed-c28a-4f71-833f-9f6e9c438e98")]
            public virtual RepoItemInfo EntitlementGridInfo
            {
                get
                {
                    return _entitlementgridInfo;
                }
            }
        }

        /// <summary>
        /// The QuebecTipsFolder folder.
        /// </summary>
        [RepositoryFolder("b0e766f8-7b8f-45df-b7c2-25ac212afbda")]
        public partial class QuebecTipsFolder : RepoGenBaseFolder
        {
            RepoItemInfo _tabInfo;
            RepoItemInfo _quebectipsgridInfo;

            /// <summary>
            /// Creates a new QuebecTips  folder.
            /// </summary>
            public QuebecTipsFolder(RepoGenBaseFolder parentFolder) :
                    base("QuebecTips", "", parentFolder, 3000, null, false, "b0e766f8-7b8f-45df-b7c2-25ac212afbda", "")
            {
                _tabInfo = new RepoItemInfo(this, "Tab", "container[@controlname='m_paychequeTabs']/?/?/tabpage[@accessiblename='Quebec Tips']", 3000, null, "3f65e1a4-c83d-4f6a-aba8-2b4264598f10");
                _quebectipsgridInfo = new RepoItemInfo(this, "QuebecTipsGrid", ".//tabpage[@controlname='m_quebecTipsTabPage']/table[@controlname='m_quebecTipsGrid']", 3000, null, "fe4f7621-4437-4cfa-81d1-1e61098eb656");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("b0e766f8-7b8f-45df-b7c2-25ac212afbda")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("b0e766f8-7b8f-45df-b7c2-25ac212afbda")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The Tab item.
            /// </summary>
            [RepositoryItem("3f65e1a4-c83d-4f6a-aba8-2b4264598f10")]
            public virtual Ranorex.TabPage Tab
            {
                get
                {
                    return _tabInfo.CreateAdapter<Ranorex.TabPage>(true);
                }
            }

            /// <summary>
            /// The Tab item info.
            /// </summary>
            [RepositoryItemInfo("3f65e1a4-c83d-4f6a-aba8-2b4264598f10")]
            public virtual RepoItemInfo TabInfo
            {
                get
                {
                    return _tabInfo;
                }
            }

            /// <summary>
            /// The QuebecTipsGrid item.
            /// </summary>
            [RepositoryItem("fe4f7621-4437-4cfa-81d1-1e61098eb656")]
            public virtual Ranorex.Table QuebecTipsGrid
            {
                get
                {
                    return _quebectipsgridInfo.CreateAdapter<Ranorex.Table>(true);
                }
            }

            /// <summary>
            /// The QuebecTipsGrid item info.
            /// </summary>
            [RepositoryItemInfo("fe4f7621-4437-4cfa-81d1-1e61098eb656")]
            public virtual RepoItemInfo QuebecTipsGridInfo
            {
                get
                {
                    return _quebectipsgridInfo;
                }
            }
        }

        /// <summary>
        /// The ProjAllocByHourAppFolder folder.
        /// </summary>
        [RepositoryFolder("fba265e8-0eb8-4536-b958-1617768e4865")]
        public partial class ProjAllocByHourAppFolder : RepoGenBaseFolder
        {

            /// <summary>
            /// Creates a new ProjAllocByHour  folder.
            /// </summary>
            public ProjAllocByHourAppFolder(RepoGenBaseFolder parentFolder) :
                    base("ProjAllocByHour", "/form[@controlname='ProjAllocByHourForm']", parentFolder, 30000, null, true, "fba265e8-0eb8-4536-b958-1617768e4865", "")
            {
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("fba265e8-0eb8-4536-b958-1617768e4865")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("fba265e8-0eb8-4536-b958-1617768e4865")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }
        }

    }
#pragma warning restore 0436
}