///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Drawing;
using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace Sage50.Repository
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    /// The class representing the ProjectLedgerRes element repository.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", "8.0")]
    [RepositoryFolder("66ed229b-3a5f-48c0-80bc-a21cd6c27dc7")]
    public partial class ProjectLedgerRes : RepoGenBaseFolder
    {
        static ProjectLedgerRes instance = new ProjectLedgerRes();
        ProjectLedgerResFolders.ProjectLedgerAppFolder _projectledger;
        ProjectLedgerResFolders.ProjectIconAppFolder _projecticon;

        /// <summary>
        /// Gets the singleton class instance representing the ProjectLedgerRes element repository.
        /// </summary>
        [RepositoryFolder("66ed229b-3a5f-48c0-80bc-a21cd6c27dc7")]
        public static ProjectLedgerRes Instance
        {
            get { return instance; }
        }

        /// <summary>
        /// Repository class constructor.
        /// </summary>
        public ProjectLedgerRes() 
            : base("ProjectLedgerRes", "/", null, 0, false, "66ed229b-3a5f-48c0-80bc-a21cd6c27dc7", ".\\RepositoryImages\\ProjectLedgerRes66ed229b.rximgres")
        {
            _projectledger = new ProjectLedgerResFolders.ProjectLedgerAppFolder(this);
            _projecticon = new ProjectLedgerResFolders.ProjectIconAppFolder(this);
        }

#region Variables

#endregion

        /// <summary>
        /// The Self item info.
        /// </summary>
        [RepositoryItemInfo("66ed229b-3a5f-48c0-80bc-a21cd6c27dc7")]
        public virtual RepoItemInfo SelfInfo
        {
            get
            {
                return _selfInfo;
            }
        }

        /// <summary>
        /// The ProjectLedger folder.
        /// </summary>
        [RepositoryFolder("fdeabf97-8ce2-4389-84d2-c86f0d3950fb")]
        public virtual ProjectLedgerResFolders.ProjectLedgerAppFolder ProjectLedger
        {
            get { return _projectledger; }
        }

        /// <summary>
        /// The ProjectIcon folder.
        /// </summary>
        [RepositoryFolder("645766b1-3a09-4ad8-84c9-5aa9903c31b7")]
        public virtual ProjectLedgerResFolders.ProjectIconAppFolder ProjectIcon
        {
            get { return _projecticon; }
        }
    }

    /// <summary>
    /// Inner folder classes.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", "8.0")]
    public partial class ProjectLedgerResFolders
    {
        /// <summary>
        /// The ProjectLedgerAppFolder folder.
        /// </summary>
        [RepositoryFolder("fdeabf97-8ce2-4389-84d2-c86f0d3950fb")]
        public partial class ProjectLedgerAppFolder : RepoGenBaseFolder
        {
            ProjectLedgerResFolders.ProjectFolder _project;
            ProjectLedgerResFolders.AdditionalInfoFolder _additionalinfo;
            ProjectLedgerResFolders.BudgetFolder _budget;
            RepoItemInfo _buttondetailsInfo;
            RepoItemInfo _saveandcloseInfo;
            RepoItemInfo _buttoncreateanotherInfo;
            RepoItemInfo _createanewtoolbuttonInfo;
            RepoItemInfo _saveInfo;
            RepoItemInfo _selectrecordInfo;
            RepoItemInfo _inactiveprojectInfo;
            RepoItemInfo _tabcontrolInfo;

            /// <summary>
            /// Creates a new ProjectLedger  folder.
            /// </summary>
            public ProjectLedgerAppFolder(RepoGenBaseFolder parentFolder) :
                    base("ProjectLedger", "/form[@title='Project Ledger']", parentFolder, 30000, null, true, "fdeabf97-8ce2-4389-84d2-c86f0d3950fb", "")
            {
                _project = new ProjectLedgerResFolders.ProjectFolder(this);
                _additionalinfo = new ProjectLedgerResFolders.AdditionalInfoFolder(this);
                _budget = new ProjectLedgerResFolders.BudgetFolder(this);
                _buttondetailsInfo = new RepoItemInfo(this, "ButtonDetails", "button[@text='&Details...']", 30000, null, "e581a6c8-1bd0-472f-bbbc-d7bd6eb91069");
                _saveandcloseInfo = new RepoItemInfo(this, "SaveAndClose", "button[@text='Save a&nd Close']", 30000, null, "9e952ece-cd8f-4e52-ac80-53058660f35f");
                _buttoncreateanotherInfo = new RepoItemInfo(this, "ButtonCreateAnother", "button[@text='&Create Another']", 30000, null, "94b740cc-a059-490f-8345-63f0da44453b");
                _createanewtoolbuttonInfo = new RepoItemInfo(this, "CreateANewToolButton", "?/?/toolbar[@class='ToolbarWindow32' and @instance='0']/button[@text~'^Create\\ a\\ new\\ Project\\ \\(Ct']", 3000, null, "9cfb97be-06f2-4111-befe-dfa354ce0d71");
                _saveInfo = new RepoItemInfo(this, "Save", "?/?/toolbar[@class='ToolbarWindow32' and @instance='0']/button[@text~'^Save\\ the\\ current\\ Project']", 3000, null, "1f3c22f5-7ec7-42c5-a38a-5f880f80f48a");
                _selectrecordInfo = new RepoItemInfo(this, "SelectRecord", "?/?/toolbar[@class='ToolbarWindow32' and @instance='1']/combobox[@controlid='504']", 3000, null, "61295f49-3e5b-49b2-92dd-a5e83973ef22");
                _inactiveprojectInfo = new RepoItemInfo(this, "InactiveProject", "checkbox[@controlid='47']", 30000, null, "38360ff6-a3f1-49cc-af15-166ecca16a52");
                _tabcontrolInfo = new RepoItemInfo(this, "TabControl", "tabpagelist[@class='SysTabControl32']", 30000, null, "f6638840-b32b-411b-8d6f-f21cf6ebbc1b");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("fdeabf97-8ce2-4389-84d2-c86f0d3950fb")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("fdeabf97-8ce2-4389-84d2-c86f0d3950fb")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The ButtonDetails item.
            /// </summary>
            [RepositoryItem("e581a6c8-1bd0-472f-bbbc-d7bd6eb91069")]
            public virtual Ranorex.Button ButtonDetails
            {
                get
                {
                    return _buttondetailsInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The ButtonDetails item info.
            /// </summary>
            [RepositoryItemInfo("e581a6c8-1bd0-472f-bbbc-d7bd6eb91069")]
            public virtual RepoItemInfo ButtonDetailsInfo
            {
                get
                {
                    return _buttondetailsInfo;
                }
            }

            /// <summary>
            /// The SaveAndClose item.
            /// </summary>
            [RepositoryItem("9e952ece-cd8f-4e52-ac80-53058660f35f")]
            public virtual Ranorex.Button SaveAndClose
            {
                get
                {
                    return _saveandcloseInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The SaveAndClose item info.
            /// </summary>
            [RepositoryItemInfo("9e952ece-cd8f-4e52-ac80-53058660f35f")]
            public virtual RepoItemInfo SaveAndCloseInfo
            {
                get
                {
                    return _saveandcloseInfo;
                }
            }

            /// <summary>
            /// The ButtonCreateAnother item.
            /// </summary>
            [RepositoryItem("94b740cc-a059-490f-8345-63f0da44453b")]
            public virtual Ranorex.Button ButtonCreateAnother
            {
                get
                {
                    return _buttoncreateanotherInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The ButtonCreateAnother item info.
            /// </summary>
            [RepositoryItemInfo("94b740cc-a059-490f-8345-63f0da44453b")]
            public virtual RepoItemInfo ButtonCreateAnotherInfo
            {
                get
                {
                    return _buttoncreateanotherInfo;
                }
            }

            /// <summary>
            /// The CreateANewToolButton item.
            /// </summary>
            [RepositoryItem("9cfb97be-06f2-4111-befe-dfa354ce0d71")]
            public virtual Ranorex.Button CreateANewToolButton
            {
                get
                {
                    return _createanewtoolbuttonInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The CreateANewToolButton item info.
            /// </summary>
            [RepositoryItemInfo("9cfb97be-06f2-4111-befe-dfa354ce0d71")]
            public virtual RepoItemInfo CreateANewToolButtonInfo
            {
                get
                {
                    return _createanewtoolbuttonInfo;
                }
            }

            /// <summary>
            /// The Save item.
            /// </summary>
            [RepositoryItem("1f3c22f5-7ec7-42c5-a38a-5f880f80f48a")]
            public virtual Ranorex.Button Save
            {
                get
                {
                    return _saveInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The Save item info.
            /// </summary>
            [RepositoryItemInfo("1f3c22f5-7ec7-42c5-a38a-5f880f80f48a")]
            public virtual RepoItemInfo SaveInfo
            {
                get
                {
                    return _saveInfo;
                }
            }

            /// <summary>
            /// The SelectRecord item.
            /// </summary>
            [RepositoryItem("61295f49-3e5b-49b2-92dd-a5e83973ef22")]
            public virtual Ranorex.ComboBox SelectRecord
            {
                get
                {
                    return _selectrecordInfo.CreateAdapter<Ranorex.ComboBox>(true);
                }
            }

            /// <summary>
            /// The SelectRecord item info.
            /// </summary>
            [RepositoryItemInfo("61295f49-3e5b-49b2-92dd-a5e83973ef22")]
            public virtual RepoItemInfo SelectRecordInfo
            {
                get
                {
                    return _selectrecordInfo;
                }
            }

            /// <summary>
            /// The InactiveProject item.
            /// </summary>
            [RepositoryItem("38360ff6-a3f1-49cc-af15-166ecca16a52")]
            public virtual Ranorex.CheckBox InactiveProject
            {
                get
                {
                    return _inactiveprojectInfo.CreateAdapter<Ranorex.CheckBox>(true);
                }
            }

            /// <summary>
            /// The InactiveProject item info.
            /// </summary>
            [RepositoryItemInfo("38360ff6-a3f1-49cc-af15-166ecca16a52")]
            public virtual RepoItemInfo InactiveProjectInfo
            {
                get
                {
                    return _inactiveprojectInfo;
                }
            }

            /// <summary>
            /// The TabControl item.
            /// </summary>
            [RepositoryItem("f6638840-b32b-411b-8d6f-f21cf6ebbc1b")]
            public virtual Ranorex.TabPageList TabControl
            {
                get
                {
                    return _tabcontrolInfo.CreateAdapter<Ranorex.TabPageList>(true);
                }
            }

            /// <summary>
            /// The TabControl item info.
            /// </summary>
            [RepositoryItemInfo("f6638840-b32b-411b-8d6f-f21cf6ebbc1b")]
            public virtual RepoItemInfo TabControlInfo
            {
                get
                {
                    return _tabcontrolInfo;
                }
            }

            /// <summary>
            /// The Project folder.
            /// </summary>
            [RepositoryFolder("2367f51c-26b0-49e5-9ca8-78378dfd6c5d")]
            public virtual ProjectLedgerResFolders.ProjectFolder Project
            {
                get { return _project; }
            }

            /// <summary>
            /// The AdditionalInfo folder.
            /// </summary>
            [RepositoryFolder("3f28add0-6e0c-4972-b8dd-c05c3a80a5e7")]
            public virtual ProjectLedgerResFolders.AdditionalInfoFolder AdditionalInfo
            {
                get { return _additionalinfo; }
            }

            /// <summary>
            /// The Budget folder.
            /// </summary>
            [RepositoryFolder("dcf6af05-6b56-4525-a69c-e0a00e42a181")]
            public virtual ProjectLedgerResFolders.BudgetFolder Budget
            {
                get { return _budget; }
            }
        }

        /// <summary>
        /// The ProjectFolder folder.
        /// </summary>
        [RepositoryFolder("2367f51c-26b0-49e5-9ca8-78378dfd6c5d")]
        public partial class ProjectFolder : RepoGenBaseFolder
        {
            RepoItemInfo _tabInfo;
            RepoItemInfo _projectnameInfo;
            RepoItemInfo _startdateInfo;
            RepoItemInfo _enddateInfo;
            RepoItemInfo _revenueInfo;
            RepoItemInfo _expenseInfo;
            RepoItemInfo _statusInfo;

            /// <summary>
            /// Creates a new Project  folder.
            /// </summary>
            public ProjectFolder(RepoGenBaseFolder parentFolder) :
                    base("Project", "", parentFolder, 30000, null, false, "2367f51c-26b0-49e5-9ca8-78378dfd6c5d", "")
            {
                _tabInfo = new RepoItemInfo(this, "Tab", "?/?/tabpage[@title='Project']", 3000, null, "4e52ffd5-23bd-437f-a219-d7e49f885909");
                _projectnameInfo = new RepoItemInfo(this, "ProjectName", "element[@controlid='23']/text", 3000, null, "dc275952-935b-43e0-8e79-8274721081cb");
                _startdateInfo = new RepoItemInfo(this, "StartDate", "element[@controlid='27']/text", 3000, null, "58acd22f-e749-4234-9838-30ad3b639fde");
                _enddateInfo = new RepoItemInfo(this, "EndDate", "element[@controlid='301']/text", 3000, null, "db8fe4ae-1565-4438-bef3-b632abb18ba6");
                _revenueInfo = new RepoItemInfo(this, "Revenue", "element[@controlid='29']/text", 3000, null, "90c8d5fe-98a3-4ce2-8d26-634411828647");
                _expenseInfo = new RepoItemInfo(this, "Expense", "element[@controlid='30']/text", 3000, null, "199b2238-7988-492c-a40b-e442719b462a");
                _statusInfo = new RepoItemInfo(this, "Status", "combobox[@controlid='304']", 30000, null, "26879eaa-80b6-4d29-bd8f-d4d6da6a1403");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("2367f51c-26b0-49e5-9ca8-78378dfd6c5d")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("2367f51c-26b0-49e5-9ca8-78378dfd6c5d")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The Tab item.
            /// </summary>
            [RepositoryItem("4e52ffd5-23bd-437f-a219-d7e49f885909")]
            public virtual Ranorex.TabPage Tab
            {
                get
                {
                    return _tabInfo.CreateAdapter<Ranorex.TabPage>(true);
                }
            }

            /// <summary>
            /// The Tab item info.
            /// </summary>
            [RepositoryItemInfo("4e52ffd5-23bd-437f-a219-d7e49f885909")]
            public virtual RepoItemInfo TabInfo
            {
                get
                {
                    return _tabInfo;
                }
            }

            /// <summary>
            /// The ProjectName item.
            /// </summary>
            [RepositoryItem("dc275952-935b-43e0-8e79-8274721081cb")]
            public virtual Ranorex.Text ProjectName
            {
                get
                {
                    return _projectnameInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The ProjectName item info.
            /// </summary>
            [RepositoryItemInfo("dc275952-935b-43e0-8e79-8274721081cb")]
            public virtual RepoItemInfo ProjectNameInfo
            {
                get
                {
                    return _projectnameInfo;
                }
            }

            /// <summary>
            /// The StartDate item.
            /// </summary>
            [RepositoryItem("58acd22f-e749-4234-9838-30ad3b639fde")]
            public virtual Ranorex.Text StartDate
            {
                get
                {
                    return _startdateInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The StartDate item info.
            /// </summary>
            [RepositoryItemInfo("58acd22f-e749-4234-9838-30ad3b639fde")]
            public virtual RepoItemInfo StartDateInfo
            {
                get
                {
                    return _startdateInfo;
                }
            }

            /// <summary>
            /// The EndDate item.
            /// </summary>
            [RepositoryItem("db8fe4ae-1565-4438-bef3-b632abb18ba6")]
            public virtual Ranorex.Text EndDate
            {
                get
                {
                    return _enddateInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The EndDate item info.
            /// </summary>
            [RepositoryItemInfo("db8fe4ae-1565-4438-bef3-b632abb18ba6")]
            public virtual RepoItemInfo EndDateInfo
            {
                get
                {
                    return _enddateInfo;
                }
            }

            /// <summary>
            /// The Revenue item.
            /// </summary>
            [RepositoryItem("90c8d5fe-98a3-4ce2-8d26-634411828647")]
            public virtual Ranorex.Text Revenue
            {
                get
                {
                    return _revenueInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The Revenue item info.
            /// </summary>
            [RepositoryItemInfo("90c8d5fe-98a3-4ce2-8d26-634411828647")]
            public virtual RepoItemInfo RevenueInfo
            {
                get
                {
                    return _revenueInfo;
                }
            }

            /// <summary>
            /// The Expense item.
            /// </summary>
            [RepositoryItem("199b2238-7988-492c-a40b-e442719b462a")]
            public virtual Ranorex.Text Expense
            {
                get
                {
                    return _expenseInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The Expense item info.
            /// </summary>
            [RepositoryItemInfo("199b2238-7988-492c-a40b-e442719b462a")]
            public virtual RepoItemInfo ExpenseInfo
            {
                get
                {
                    return _expenseInfo;
                }
            }

            /// <summary>
            /// The Status item.
            /// </summary>
            [RepositoryItem("26879eaa-80b6-4d29-bd8f-d4d6da6a1403")]
            public virtual Ranorex.ComboBox Status
            {
                get
                {
                    return _statusInfo.CreateAdapter<Ranorex.ComboBox>(true);
                }
            }

            /// <summary>
            /// The Status item info.
            /// </summary>
            [RepositoryItemInfo("26879eaa-80b6-4d29-bd8f-d4d6da6a1403")]
            public virtual RepoItemInfo StatusInfo
            {
                get
                {
                    return _statusInfo;
                }
            }
        }

        /// <summary>
        /// The AdditionalInfoFolder folder.
        /// </summary>
        [RepositoryFolder("3f28add0-6e0c-4972-b8dd-c05c3a80a5e7")]
        public partial class AdditionalInfoFolder : RepoGenBaseFolder
        {
            RepoItemInfo _additional1Info;
            RepoItemInfo _additional2Info;
            RepoItemInfo _additional3Info;
            RepoItemInfo _additional4Info;
            RepoItemInfo _additional5Info;
            RepoItemInfo _addcheckbox1Info;
            RepoItemInfo _addcheckbox2Info;
            RepoItemInfo _addcheckbox3Info;
            RepoItemInfo _addcheckbox4Info;
            RepoItemInfo _addcheckbox5Info;
            RepoItemInfo _tabInfo;

            /// <summary>
            /// Creates a new AdditionalInfo  folder.
            /// </summary>
            public AdditionalInfoFolder(RepoGenBaseFolder parentFolder) :
                    base("AdditionalInfo", "", parentFolder, 30000, null, false, "3f28add0-6e0c-4972-b8dd-c05c3a80a5e7", "")
            {
                _additional1Info = new RepoItemInfo(this, "Additional1", "element[@controlid='805']/text", 3000, null, "fdfffdd0-1fd8-4f48-8ec6-e4d08878e6e0");
                _additional2Info = new RepoItemInfo(this, "Additional2", "element[@controlid='806']/text", 3000, null, "8417ae00-9a7e-4fe6-8b81-0dbf31910386");
                _additional3Info = new RepoItemInfo(this, "Additional3", "element[@controlid='807']/text", 3000, null, "fb1d80a2-d2b0-443a-8f7b-c4e282868106");
                _additional4Info = new RepoItemInfo(this, "Additional4", "element[@controlid='808']/text", 3000, null, "ec254af6-81b5-4016-a06f-be2856a01c2e");
                _additional5Info = new RepoItemInfo(this, "Additional5", "element[@controlid='809']/text", 3000, null, "1db64cce-009c-4383-8a49-a969b146ea68");
                _addcheckbox1Info = new RepoItemInfo(this, "AddCheckBox1", "checkbox[@controlid='811']", 30000, null, "d50ae3a6-af1d-41af-baf5-d528351e5a98");
                _addcheckbox2Info = new RepoItemInfo(this, "AddCheckBox2", "checkbox[@controlid='812']", 30000, null, "bda8636c-1a4e-41ce-b00b-90d0359d043f");
                _addcheckbox3Info = new RepoItemInfo(this, "AddCheckBox3", "checkbox[@controlid='813']", 30000, null, "296f5960-1634-4527-b467-71c425682f4d");
                _addcheckbox4Info = new RepoItemInfo(this, "AddCheckBox4", "checkbox[@controlid='814']", 30000, null, "c8c0b9d7-348e-40ad-a20d-0b88ce5842a6");
                _addcheckbox5Info = new RepoItemInfo(this, "AddCheckBox5", "checkbox[@controlid='815']", 30000, null, "d61f6d85-29e4-4fe7-a4d4-880f9b93426d");
                _tabInfo = new RepoItemInfo(this, "Tab", "?/?/tabpage[@title='Additional Info']", 3000, null, "f3f5daa6-3886-41b8-9019-660e50e844b9");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("3f28add0-6e0c-4972-b8dd-c05c3a80a5e7")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("3f28add0-6e0c-4972-b8dd-c05c3a80a5e7")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The Additional1 item.
            /// </summary>
            [RepositoryItem("fdfffdd0-1fd8-4f48-8ec6-e4d08878e6e0")]
            public virtual Ranorex.Text Additional1
            {
                get
                {
                    return _additional1Info.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The Additional1 item info.
            /// </summary>
            [RepositoryItemInfo("fdfffdd0-1fd8-4f48-8ec6-e4d08878e6e0")]
            public virtual RepoItemInfo Additional1Info
            {
                get
                {
                    return _additional1Info;
                }
            }

            /// <summary>
            /// The Additional2 item.
            /// </summary>
            [RepositoryItem("8417ae00-9a7e-4fe6-8b81-0dbf31910386")]
            public virtual Ranorex.Text Additional2
            {
                get
                {
                    return _additional2Info.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The Additional2 item info.
            /// </summary>
            [RepositoryItemInfo("8417ae00-9a7e-4fe6-8b81-0dbf31910386")]
            public virtual RepoItemInfo Additional2Info
            {
                get
                {
                    return _additional2Info;
                }
            }

            /// <summary>
            /// The Additional3 item.
            /// </summary>
            [RepositoryItem("fb1d80a2-d2b0-443a-8f7b-c4e282868106")]
            public virtual Ranorex.Text Additional3
            {
                get
                {
                    return _additional3Info.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The Additional3 item info.
            /// </summary>
            [RepositoryItemInfo("fb1d80a2-d2b0-443a-8f7b-c4e282868106")]
            public virtual RepoItemInfo Additional3Info
            {
                get
                {
                    return _additional3Info;
                }
            }

            /// <summary>
            /// The Additional4 item.
            /// </summary>
            [RepositoryItem("ec254af6-81b5-4016-a06f-be2856a01c2e")]
            public virtual Ranorex.Text Additional4
            {
                get
                {
                    return _additional4Info.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The Additional4 item info.
            /// </summary>
            [RepositoryItemInfo("ec254af6-81b5-4016-a06f-be2856a01c2e")]
            public virtual RepoItemInfo Additional4Info
            {
                get
                {
                    return _additional4Info;
                }
            }

            /// <summary>
            /// The Additional5 item.
            /// </summary>
            [RepositoryItem("1db64cce-009c-4383-8a49-a969b146ea68")]
            public virtual Ranorex.Text Additional5
            {
                get
                {
                    return _additional5Info.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The Additional5 item info.
            /// </summary>
            [RepositoryItemInfo("1db64cce-009c-4383-8a49-a969b146ea68")]
            public virtual RepoItemInfo Additional5Info
            {
                get
                {
                    return _additional5Info;
                }
            }

            /// <summary>
            /// The AddCheckBox1 item.
            /// </summary>
            [RepositoryItem("d50ae3a6-af1d-41af-baf5-d528351e5a98")]
            public virtual Ranorex.CheckBox AddCheckBox1
            {
                get
                {
                    return _addcheckbox1Info.CreateAdapter<Ranorex.CheckBox>(true);
                }
            }

            /// <summary>
            /// The AddCheckBox1 item info.
            /// </summary>
            [RepositoryItemInfo("d50ae3a6-af1d-41af-baf5-d528351e5a98")]
            public virtual RepoItemInfo AddCheckBox1Info
            {
                get
                {
                    return _addcheckbox1Info;
                }
            }

            /// <summary>
            /// The AddCheckBox2 item.
            /// </summary>
            [RepositoryItem("bda8636c-1a4e-41ce-b00b-90d0359d043f")]
            public virtual Ranorex.CheckBox AddCheckBox2
            {
                get
                {
                    return _addcheckbox2Info.CreateAdapter<Ranorex.CheckBox>(true);
                }
            }

            /// <summary>
            /// The AddCheckBox2 item info.
            /// </summary>
            [RepositoryItemInfo("bda8636c-1a4e-41ce-b00b-90d0359d043f")]
            public virtual RepoItemInfo AddCheckBox2Info
            {
                get
                {
                    return _addcheckbox2Info;
                }
            }

            /// <summary>
            /// The AddCheckBox3 item.
            /// </summary>
            [RepositoryItem("296f5960-1634-4527-b467-71c425682f4d")]
            public virtual Ranorex.CheckBox AddCheckBox3
            {
                get
                {
                    return _addcheckbox3Info.CreateAdapter<Ranorex.CheckBox>(true);
                }
            }

            /// <summary>
            /// The AddCheckBox3 item info.
            /// </summary>
            [RepositoryItemInfo("296f5960-1634-4527-b467-71c425682f4d")]
            public virtual RepoItemInfo AddCheckBox3Info
            {
                get
                {
                    return _addcheckbox3Info;
                }
            }

            /// <summary>
            /// The AddCheckBox4 item.
            /// </summary>
            [RepositoryItem("c8c0b9d7-348e-40ad-a20d-0b88ce5842a6")]
            public virtual Ranorex.CheckBox AddCheckBox4
            {
                get
                {
                    return _addcheckbox4Info.CreateAdapter<Ranorex.CheckBox>(true);
                }
            }

            /// <summary>
            /// The AddCheckBox4 item info.
            /// </summary>
            [RepositoryItemInfo("c8c0b9d7-348e-40ad-a20d-0b88ce5842a6")]
            public virtual RepoItemInfo AddCheckBox4Info
            {
                get
                {
                    return _addcheckbox4Info;
                }
            }

            /// <summary>
            /// The AddCheckBox5 item.
            /// </summary>
            [RepositoryItem("d61f6d85-29e4-4fe7-a4d4-880f9b93426d")]
            public virtual Ranorex.CheckBox AddCheckBox5
            {
                get
                {
                    return _addcheckbox5Info.CreateAdapter<Ranorex.CheckBox>(true);
                }
            }

            /// <summary>
            /// The AddCheckBox5 item info.
            /// </summary>
            [RepositoryItemInfo("d61f6d85-29e4-4fe7-a4d4-880f9b93426d")]
            public virtual RepoItemInfo AddCheckBox5Info
            {
                get
                {
                    return _addcheckbox5Info;
                }
            }

            /// <summary>
            /// The Tab item.
            /// </summary>
            [RepositoryItem("f3f5daa6-3886-41b8-9019-660e50e844b9")]
            public virtual Ranorex.TabPage Tab
            {
                get
                {
                    return _tabInfo.CreateAdapter<Ranorex.TabPage>(true);
                }
            }

            /// <summary>
            /// The Tab item info.
            /// </summary>
            [RepositoryItemInfo("f3f5daa6-3886-41b8-9019-660e50e844b9")]
            public virtual RepoItemInfo TabInfo
            {
                get
                {
                    return _tabInfo;
                }
            }
        }

        /// <summary>
        /// The BudgetFolder folder.
        /// </summary>
        [RepositoryFolder("dcf6af05-6b56-4525-a69c-e0a00e42a181")]
        public partial class BudgetFolder : RepoGenBaseFolder
        {
            RepoItemInfo _tabInfo;
            RepoItemInfo _budgetthisprojectInfo;
            RepoItemInfo _budgetcontainerInfo;

            /// <summary>
            /// Creates a new Budget  folder.
            /// </summary>
            public BudgetFolder(RepoGenBaseFolder parentFolder) :
                    base("Budget", "", parentFolder, 30000, null, false, "dcf6af05-6b56-4525-a69c-e0a00e42a181", "")
            {
                _tabInfo = new RepoItemInfo(this, "Tab", "?/?/tabpage[@title='Budget']", 3000, null, "53284595-a994-4d1e-8e2e-6c2a6d1710c7");
                _budgetthisprojectInfo = new RepoItemInfo(this, "BudgetThisProject", "checkbox[@controlid='34']", 30000, null, "755f0cd9-1130-4df2-9bc5-197fb997291f");
                _budgetcontainerInfo = new RepoItemInfo(this, "BudgetContainer", "element[@controlid='3600']", 3000, null, "91cd3b2a-9b3c-4b9c-b6df-2938cae21d60");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("dcf6af05-6b56-4525-a69c-e0a00e42a181")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("dcf6af05-6b56-4525-a69c-e0a00e42a181")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The Tab item.
            /// </summary>
            [RepositoryItem("53284595-a994-4d1e-8e2e-6c2a6d1710c7")]
            public virtual Ranorex.TabPage Tab
            {
                get
                {
                    return _tabInfo.CreateAdapter<Ranorex.TabPage>(true);
                }
            }

            /// <summary>
            /// The Tab item info.
            /// </summary>
            [RepositoryItemInfo("53284595-a994-4d1e-8e2e-6c2a6d1710c7")]
            public virtual RepoItemInfo TabInfo
            {
                get
                {
                    return _tabInfo;
                }
            }

            /// <summary>
            /// The BudgetThisProject item.
            /// </summary>
            [RepositoryItem("755f0cd9-1130-4df2-9bc5-197fb997291f")]
            public virtual Ranorex.CheckBox BudgetThisProject
            {
                get
                {
                    return _budgetthisprojectInfo.CreateAdapter<Ranorex.CheckBox>(true);
                }
            }

            /// <summary>
            /// The BudgetThisProject item info.
            /// </summary>
            [RepositoryItemInfo("755f0cd9-1130-4df2-9bc5-197fb997291f")]
            public virtual RepoItemInfo BudgetThisProjectInfo
            {
                get
                {
                    return _budgetthisprojectInfo;
                }
            }

            /// <summary>
            /// The BudgetContainer item.
            /// </summary>
            [RepositoryItem("91cd3b2a-9b3c-4b9c-b6df-2938cae21d60")]
            public virtual Ranorex.Unknown BudgetContainer
            {
                get
                {
                    return _budgetcontainerInfo.CreateAdapter<Ranorex.Unknown>(true);
                }
            }

            /// <summary>
            /// The BudgetContainer item info.
            /// </summary>
            [RepositoryItemInfo("91cd3b2a-9b3c-4b9c-b6df-2938cae21d60")]
            public virtual RepoItemInfo BudgetContainerInfo
            {
                get
                {
                    return _budgetcontainerInfo;
                }
            }
        }

        /// <summary>
        /// The ProjectIconAppFolder folder.
        /// </summary>
        [RepositoryFolder("645766b1-3a09-4ad8-84c9-5aa9903c31b7")]
        public partial class ProjectIconAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _createnewInfo;

            /// <summary>
            /// Creates a new ProjectIcon  folder.
            /// </summary>
            public ProjectIconAppFolder(RepoGenBaseFolder parentFolder) :
                    base("ProjectIcon", "/form[@title='Project']", parentFolder, 3000, null, true, "645766b1-3a09-4ad8-84c9-5aa9903c31b7", "")
            {
                _createnewInfo = new RepoItemInfo(this, "CreateNew", "?/?/toolbar[@class='ToolbarWindow32' and @instance='0']/button[@text='Create (Ctrl+N)']", 3000, null, "2d56184c-2acb-4e31-90f3-1b3b0813b396");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("645766b1-3a09-4ad8-84c9-5aa9903c31b7")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("645766b1-3a09-4ad8-84c9-5aa9903c31b7")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The CreateNew item.
            /// </summary>
            [RepositoryItem("2d56184c-2acb-4e31-90f3-1b3b0813b396")]
            public virtual Ranorex.Button CreateNew
            {
                get
                {
                    return _createnewInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The CreateNew item info.
            /// </summary>
            [RepositoryItemInfo("2d56184c-2acb-4e31-90f3-1b3b0813b396")]
            public virtual RepoItemInfo CreateNewInfo
            {
                get
                {
                    return _createnewInfo;
                }
            }
        }

    }
#pragma warning restore 0436
}