///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Drawing;
using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace Sage50.Repository
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    /// The class representing the PurchasesJournalRes element repository.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", "8.0")]
    [RepositoryFolder("103469e0-8ab2-4b13-9ef5-88ed9135b495")]
    public partial class PurchasesJournalRes : RepoGenBaseFolder
    {
        static PurchasesJournalRes instance = new PurchasesJournalRes();
        PurchasesJournalResFolders.PurchasesJournalAppFolder _purchasesjournal;
        PurchasesJournalResFolders.TrackShipmentsAppFolder _trackshipments;

        /// <summary>
        /// Gets the singleton class instance representing the PurchasesJournalRes element repository.
        /// </summary>
        [RepositoryFolder("103469e0-8ab2-4b13-9ef5-88ed9135b495")]
        public static PurchasesJournalRes Instance
        {
            get { return instance; }
        }

        /// <summary>
        /// Repository class constructor.
        /// </summary>
        public PurchasesJournalRes() 
            : base("PurchasesJournalRes", "/", null, 0, false, "103469e0-8ab2-4b13-9ef5-88ed9135b495", ".\\RepositoryImages\\PurchasesJournalRes103469e0.rximgres")
        {
            _purchasesjournal = new PurchasesJournalResFolders.PurchasesJournalAppFolder(this);
            _trackshipments = new PurchasesJournalResFolders.TrackShipmentsAppFolder(this);
        }

#region Variables

#endregion

        /// <summary>
        /// The Self item info.
        /// </summary>
        [RepositoryItemInfo("103469e0-8ab2-4b13-9ef5-88ed9135b495")]
        public virtual RepoItemInfo SelfInfo
        {
            get
            {
                return _selfInfo;
            }
        }

        /// <summary>
        /// The PurchasesJournal folder.
        /// </summary>
        [RepositoryFolder("b4023a91-805e-4299-b6e1-265049735583")]
        public virtual PurchasesJournalResFolders.PurchasesJournalAppFolder PurchasesJournal
        {
            get { return _purchasesjournal; }
        }

        /// <summary>
        /// The TrackShipments folder.
        /// </summary>
        [RepositoryFolder("768f7f76-bd50-4405-aa9a-3a2bf854f0a3")]
        public virtual PurchasesJournalResFolders.TrackShipmentsAppFolder TrackShipments
        {
            get { return _trackshipments; }
        }
    }

    /// <summary>
    /// Inner folder classes.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", "8.0")]
    public partial class PurchasesJournalResFolders
    {
        /// <summary>
        /// The PurchasesJournalAppFolder folder.
        /// </summary>
        [RepositoryFolder("b4023a91-805e-4299-b6e1-265049735583")]
        public partial class PurchasesJournalAppFolder : RepoGenBaseFolder
        {
            PurchasesJournalResFolders.ToolBarFolder _toolbar;
            RepoItemInfo _transtypedropdownInfo;
            RepoItemInfo _orderquotenoInfo;
            RepoItemInfo _orderquotenotextInfo;
            RepoItemInfo _paidbyInfo;
            RepoItemInfo _paidfromInfo;
            RepoItemInfo _chequenumberInfo;
            RepoItemInfo _invoicenumberInfo;
            RepoItemInfo _shipdateInfo;
            RepoItemInfo _vendornameInfo;
            RepoItemInfo _vendornametextInfo;
            RepoItemInfo _invoicedateInfo;
            RepoItemInfo _exchangerateInfo;
            RepoItemInfo _storeitemsatInfo;
            RepoItemInfo _transcontainerInfo;
            RepoItemInfo _containtextInfo;
            RepoItemInfo _itemdropdownInfo;
            RepoItemInfo _prepayrefnumberInfo;
            RepoItemInfo _prepaymentamountInfo;
            RepoItemInfo _directdepositnumInfo;
            RepoItemInfo _freightamountInfo;
            RepoItemInfo _freightcodeInfo;
            RepoItemInfo _freighttaxtotalInfo;
            RepoItemInfo _freighttax1Info;
            RepoItemInfo _freighttax2Info;
            RepoItemInfo _termspercentInfo;
            RepoItemInfo _termsdayInfo;
            RepoItemInfo _termsnetdaysInfo;
            RepoItemInfo _earlydiscountInfo;
            RepoItemInfo _trackshipmentsInfo;
            RepoItemInfo _recurringentryInfo;
            RepoItemInfo _postInfo;
            RepoItemInfo _invoiceprojecttextInfo;

            /// <summary>
            /// Creates a new PurchasesJournal  folder.
            /// </summary>
            public PurchasesJournalAppFolder(RepoGenBaseFolder parentFolder) :
                    base("PurchasesJournal", "/form[@controlname='PurchasesForm']", parentFolder, 3000, null, true, "b4023a91-805e-4299-b6e1-265049735583", "")
            {
                _toolbar = new PurchasesJournalResFolders.ToolBarFolder(this);
                _transtypedropdownInfo = new RepoItemInfo(this, "TransTypeDropDown", "combobox[@controlname='m_transTypeCombo']", 3000, null, "6dd236c1-526b-4519-a98a-280c7c922979");
                _orderquotenoInfo = new RepoItemInfo(this, "OrderQuoteNo", "combobox[@controlname='m_orderQuoteNoCombo']", 3000, null, "47718175-500e-406c-a508-d5f4ffedd0e9");
                _orderquotenotextInfo = new RepoItemInfo(this, "OrderQuoteNoText", "combobox[@controlname='m_orderQuoteNoCombo']/text[@controlid='1001']", 3000, null, "28142eb7-16f1-40d9-823a-99fd14177e27");
                _paidbyInfo = new RepoItemInfo(this, "PaidBy", "combobox[@controlname='m_paidbyCombo']", 3000, null, "53bca0c1-e1dc-4df5-9fac-9603e5bdd63c");
                _paidfromInfo = new RepoItemInfo(this, "PaidFrom", "combobox[@controlname='m_paidFromCombo']", 3000, null, "5945a464-1804-4821-b192-b8d8df02c96d");
                _chequenumberInfo = new RepoItemInfo(this, "ChequeNumber", "text[@controlname='m_chqNumTxtBox']/text[@accessiblename='Shipping Address: ']", 3000, null, "b0d9de5e-db8a-47be-b3e2-f8d867776a7b");
                _invoicenumberInfo = new RepoItemInfo(this, "InvoiceNumber", "text[@controlname='m_invoiceNoText']/text[@accessiblerole='Text']", 3000, null, "05326d29-9aa5-488d-938a-84bbacc68a28");
                _shipdateInfo = new RepoItemInfo(this, "ShipDate", "container[@controlname='m_shipdatePicker']/?/?/text[@accessiblerole='Text']", 3000, null, "f9093f10-c9a4-4523-8368-bf594b30b623");
                _vendornameInfo = new RepoItemInfo(this, "VendorName", "container[@controlname='m_vendorChoose']/?/?/combobox[@controlname='m_ledgerListCombo']", 3000, null, "e0e0ecde-d186-43a1-9966-e016e5611754");
                _vendornametextInfo = new RepoItemInfo(this, "VendorNameText", "container[@controlname='m_vendorChoose']/?/?/combobox[@controlname='m_ledgerListCombo']/text[@controlid='1001']", 3000, null, "b5df9d6b-3dfd-44f4-b8ff-2aff4520169c");
                _invoicedateInfo = new RepoItemInfo(this, "InvoiceDate", "container[@controlname='m_datePicker']/?/?/text[@accessiblerole='Text']", 3000, null, "9d961898-9fec-4f64-864a-b5bad49e3d00");
                _exchangerateInfo = new RepoItemInfo(this, "ExchangeRate", "container[@controlname='m_exchangeRate']/?/?/text[@accessiblerole='Text']", 3000, null, "7557e1c1-a7e6-4a9c-af32-db8848682351");
                _storeitemsatInfo = new RepoItemInfo(this, "StoreItemsAt", "combobox[@controlname='m_locationsCombo']", 3000, null, "21bd14e0-e3ef-4a3f-8999-cf4afa5a82fb");
                _transcontainerInfo = new RepoItemInfo(this, "TransContainer", "table[@controlname='m_invoiceGrid']", 3000, null, "355c4276-a1a0-467b-87b6-f0c1697aedb6");
                _containtextInfo = new RepoItemInfo(this, "ContainText", "table[@controlname='m_invoiceGrid']//text[@controlname='m_enterTxt']", 3000, null, "58e03fa8-11cb-4bb3-a4f1-f27be23dae04");
                _itemdropdownInfo = new RepoItemInfo(this, "ItemDropDown", "table[@controlname='m_invoiceGrid']//button[@controlname='m_popupButton']", 30000, null, "f0cf15a6-4b6a-4085-9131-3b0307fbc992");
                _prepayrefnumberInfo = new RepoItemInfo(this, "PrepayRefNumber", "?/?/text[@accessiblename='Shipping Address: ']", 3000, null, "5bf480cd-5484-4cf1-911d-a5a085298c16");
                _prepaymentamountInfo = new RepoItemInfo(this, "PrepaymentAmount", "?/?/text[@accessiblename='Paid From: ']", 3000, null, "89baeafa-98f6-45b3-897f-4ac7a5fd9d18");
                _directdepositnumInfo = new RepoItemInfo(this, "DirectDepositNum", "?/?/text[@accessiblename='*' and @accessiblerole='Text']", 3000, null, "8fded640-fea6-44bb-909a-d6b446a8c376");
                _freightamountInfo = new RepoItemInfo(this, "FreightAmount", "container[@controlname='m_jourFreights']/text[@controlname='m_freightAmtBox']/text[@accessiblerole='Text']", 3000, null, "2ade450b-b14d-4ba5-8a35-4fa92ea75f79");
                _freightcodeInfo = new RepoItemInfo(this, "FreightCode", "container[@controlname='m_jourFreights']/text[@controlname='m_freightTaxCodeBox']/text[@accessiblerole='Text']", 3000, null, "aff995a5-5084-4208-b38f-db129d456818");
                _freighttaxtotalInfo = new RepoItemInfo(this, "FreightTaxTotal", "container[@controlname='m_jourFreights']/?/?/text[@accessiblerole='Text']", 3000, null, "a476478f-b010-41b7-9c60-4d88fdbf864b");
                _freighttax1Info = new RepoItemInfo(this, "FreightTax1", "container[@controlname='m_jourFreights']/text[@controlname='m_freightTaxAmt1Box']/text[@accessiblerole='Text']", 3000, null, "c12ce463-00cf-4d35-a2b4-f63826e8d3fa");
                _freighttax2Info = new RepoItemInfo(this, "FreightTax2", "container[@controlname='m_jourFreights']/text[@controlname='m_freightTaxAmt2Box']/text[@accessiblerole='Text']", 3000, null, "d4157de4-e13a-44b3-8bd4-e7f2eff792be");
                _termspercentInfo = new RepoItemInfo(this, "TermsPercent", "container[@controlname='m_paymentTerms']/?/?/text[@accessiblerole='Text']", 3000, null, "814b2168-81bf-420e-823f-0d0c2d8bdc49");
                _termsdayInfo = new RepoItemInfo(this, "TermsDay", "container[@controlname='m_paymentTerms']/text[@controlname='m_discDays']/text[@accessiblename='Early Payment Terms:']", 3000, null, "0e81f4d5-f785-45c0-a8f2-c72f36348d63");
                _termsnetdaysInfo = new RepoItemInfo(this, "TermsNetDays", "container[@controlname='m_paymentTerms']/?/?/text[@accessiblename='Early Payment Terms:']", 3000, null, "b85661aa-358d-4969-b160-52c8a0d2ec16");
                _earlydiscountInfo = new RepoItemInfo(this, "EarlyDiscount", "container[@controlname='m_paymentDisc']/text[@controlname='m_discPercent']/text[@accessiblerole='Text']", 3000, null, "a3c19f79-a64b-402f-8538-3c60ccf22b63");
                _trackshipmentsInfo = new RepoItemInfo(this, "TrackShipments", "?/?/button[@accessiblename='Shipments']", 3000, null, "215ac230-2461-469f-9353-6c69debb5e82");
                _recurringentryInfo = new RepoItemInfo(this, "RecurringEntry", "?/?/button[@accessiblename='Store']", 3000, null, "8fd903ab-f8ff-4f74-8fde-0fbcc07d6dc1");
                _postInfo = new RepoItemInfo(this, "Post", "button[@controlname='m_postButton']", 3000, null, "dc9abe98-8773-42f0-aede-b372d34aa072");
                _invoiceprojecttextInfo = new RepoItemInfo(this, "InvoiceProjectText", "?/?/combobox[@controlname='m_projectCombo']/text[@controlid='1001']", 3000, null, "c9408373-61ad-4a97-b90b-85efb7ecd0d9");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("b4023a91-805e-4299-b6e1-265049735583")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("b4023a91-805e-4299-b6e1-265049735583")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The TransTypeDropDown item.
            /// </summary>
            [RepositoryItem("6dd236c1-526b-4519-a98a-280c7c922979")]
            public virtual Ranorex.ComboBox TransTypeDropDown
            {
                get
                {
                    return _transtypedropdownInfo.CreateAdapter<Ranorex.ComboBox>(true);
                }
            }

            /// <summary>
            /// The TransTypeDropDown item info.
            /// </summary>
            [RepositoryItemInfo("6dd236c1-526b-4519-a98a-280c7c922979")]
            public virtual RepoItemInfo TransTypeDropDownInfo
            {
                get
                {
                    return _transtypedropdownInfo;
                }
            }

            /// <summary>
            /// The OrderQuoteNo item.
            /// </summary>
            [RepositoryItem("47718175-500e-406c-a508-d5f4ffedd0e9")]
            public virtual Ranorex.ComboBox OrderQuoteNo
            {
                get
                {
                    return _orderquotenoInfo.CreateAdapter<Ranorex.ComboBox>(true);
                }
            }

            /// <summary>
            /// The OrderQuoteNo item info.
            /// </summary>
            [RepositoryItemInfo("47718175-500e-406c-a508-d5f4ffedd0e9")]
            public virtual RepoItemInfo OrderQuoteNoInfo
            {
                get
                {
                    return _orderquotenoInfo;
                }
            }

            /// <summary>
            /// The OrderQuoteNoText item.
            /// </summary>
            [RepositoryItem("28142eb7-16f1-40d9-823a-99fd14177e27")]
            public virtual Ranorex.Text OrderQuoteNoText
            {
                get
                {
                    return _orderquotenotextInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The OrderQuoteNoText item info.
            /// </summary>
            [RepositoryItemInfo("28142eb7-16f1-40d9-823a-99fd14177e27")]
            public virtual RepoItemInfo OrderQuoteNoTextInfo
            {
                get
                {
                    return _orderquotenotextInfo;
                }
            }

            /// <summary>
            /// The PaidBy item.
            /// </summary>
            [RepositoryItem("53bca0c1-e1dc-4df5-9fac-9603e5bdd63c")]
            public virtual Ranorex.ComboBox PaidBy
            {
                get
                {
                    return _paidbyInfo.CreateAdapter<Ranorex.ComboBox>(true);
                }
            }

            /// <summary>
            /// The PaidBy item info.
            /// </summary>
            [RepositoryItemInfo("53bca0c1-e1dc-4df5-9fac-9603e5bdd63c")]
            public virtual RepoItemInfo PaidByInfo
            {
                get
                {
                    return _paidbyInfo;
                }
            }

            /// <summary>
            /// The PaidFrom item.
            /// </summary>
            [RepositoryItem("5945a464-1804-4821-b192-b8d8df02c96d")]
            public virtual Ranorex.ComboBox PaidFrom
            {
                get
                {
                    return _paidfromInfo.CreateAdapter<Ranorex.ComboBox>(true);
                }
            }

            /// <summary>
            /// The PaidFrom item info.
            /// </summary>
            [RepositoryItemInfo("5945a464-1804-4821-b192-b8d8df02c96d")]
            public virtual RepoItemInfo PaidFromInfo
            {
                get
                {
                    return _paidfromInfo;
                }
            }

            /// <summary>
            /// The ChequeNumber item.
            /// </summary>
            [RepositoryItem("b0d9de5e-db8a-47be-b3e2-f8d867776a7b")]
            public virtual Ranorex.Text ChequeNumber
            {
                get
                {
                    return _chequenumberInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The ChequeNumber item info.
            /// </summary>
            [RepositoryItemInfo("b0d9de5e-db8a-47be-b3e2-f8d867776a7b")]
            public virtual RepoItemInfo ChequeNumberInfo
            {
                get
                {
                    return _chequenumberInfo;
                }
            }

            /// <summary>
            /// The InvoiceNumber item.
            /// </summary>
            [RepositoryItem("05326d29-9aa5-488d-938a-84bbacc68a28")]
            public virtual Ranorex.Text InvoiceNumber
            {
                get
                {
                    return _invoicenumberInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The InvoiceNumber item info.
            /// </summary>
            [RepositoryItemInfo("05326d29-9aa5-488d-938a-84bbacc68a28")]
            public virtual RepoItemInfo InvoiceNumberInfo
            {
                get
                {
                    return _invoicenumberInfo;
                }
            }

            /// <summary>
            /// The ShipDate item.
            /// </summary>
            [RepositoryItem("f9093f10-c9a4-4523-8368-bf594b30b623")]
            public virtual Ranorex.Text ShipDate
            {
                get
                {
                    return _shipdateInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The ShipDate item info.
            /// </summary>
            [RepositoryItemInfo("f9093f10-c9a4-4523-8368-bf594b30b623")]
            public virtual RepoItemInfo ShipDateInfo
            {
                get
                {
                    return _shipdateInfo;
                }
            }

            /// <summary>
            /// The VendorName item.
            /// </summary>
            [RepositoryItem("e0e0ecde-d186-43a1-9966-e016e5611754")]
            public virtual Ranorex.ComboBox VendorName
            {
                get
                {
                    return _vendornameInfo.CreateAdapter<Ranorex.ComboBox>(true);
                }
            }

            /// <summary>
            /// The VendorName item info.
            /// </summary>
            [RepositoryItemInfo("e0e0ecde-d186-43a1-9966-e016e5611754")]
            public virtual RepoItemInfo VendorNameInfo
            {
                get
                {
                    return _vendornameInfo;
                }
            }

            /// <summary>
            /// The VendorNameText item.
            /// </summary>
            [RepositoryItem("b5df9d6b-3dfd-44f4-b8ff-2aff4520169c")]
            public virtual Ranorex.Text VendorNameText
            {
                get
                {
                    return _vendornametextInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The VendorNameText item info.
            /// </summary>
            [RepositoryItemInfo("b5df9d6b-3dfd-44f4-b8ff-2aff4520169c")]
            public virtual RepoItemInfo VendorNameTextInfo
            {
                get
                {
                    return _vendornametextInfo;
                }
            }

            /// <summary>
            /// The InvoiceDate item.
            /// </summary>
            [RepositoryItem("9d961898-9fec-4f64-864a-b5bad49e3d00")]
            public virtual Ranorex.Text InvoiceDate
            {
                get
                {
                    return _invoicedateInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The InvoiceDate item info.
            /// </summary>
            [RepositoryItemInfo("9d961898-9fec-4f64-864a-b5bad49e3d00")]
            public virtual RepoItemInfo InvoiceDateInfo
            {
                get
                {
                    return _invoicedateInfo;
                }
            }

            /// <summary>
            /// The ExchangeRate item.
            /// </summary>
            [RepositoryItem("7557e1c1-a7e6-4a9c-af32-db8848682351")]
            public virtual Ranorex.Text ExchangeRate
            {
                get
                {
                    return _exchangerateInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The ExchangeRate item info.
            /// </summary>
            [RepositoryItemInfo("7557e1c1-a7e6-4a9c-af32-db8848682351")]
            public virtual RepoItemInfo ExchangeRateInfo
            {
                get
                {
                    return _exchangerateInfo;
                }
            }

            /// <summary>
            /// The StoreItemsAt item.
            /// </summary>
            [RepositoryItem("21bd14e0-e3ef-4a3f-8999-cf4afa5a82fb")]
            public virtual Ranorex.ComboBox StoreItemsAt
            {
                get
                {
                    return _storeitemsatInfo.CreateAdapter<Ranorex.ComboBox>(true);
                }
            }

            /// <summary>
            /// The StoreItemsAt item info.
            /// </summary>
            [RepositoryItemInfo("21bd14e0-e3ef-4a3f-8999-cf4afa5a82fb")]
            public virtual RepoItemInfo StoreItemsAtInfo
            {
                get
                {
                    return _storeitemsatInfo;
                }
            }

            /// <summary>
            /// The TransContainer item.
            /// </summary>
            [RepositoryItem("355c4276-a1a0-467b-87b6-f0c1697aedb6")]
            public virtual Ranorex.Table TransContainer
            {
                get
                {
                    return _transcontainerInfo.CreateAdapter<Ranorex.Table>(true);
                }
            }

            /// <summary>
            /// The TransContainer item info.
            /// </summary>
            [RepositoryItemInfo("355c4276-a1a0-467b-87b6-f0c1697aedb6")]
            public virtual RepoItemInfo TransContainerInfo
            {
                get
                {
                    return _transcontainerInfo;
                }
            }

            /// <summary>
            /// The ContainText item.
            /// </summary>
            [RepositoryItem("58e03fa8-11cb-4bb3-a4f1-f27be23dae04")]
            public virtual Ranorex.Text ContainText
            {
                get
                {
                    return _containtextInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The ContainText item info.
            /// </summary>
            [RepositoryItemInfo("58e03fa8-11cb-4bb3-a4f1-f27be23dae04")]
            public virtual RepoItemInfo ContainTextInfo
            {
                get
                {
                    return _containtextInfo;
                }
            }

            /// <summary>
            /// The ItemDropDown item.
            /// </summary>
            [RepositoryItem("f0cf15a6-4b6a-4085-9131-3b0307fbc992")]
            public virtual Ranorex.Button ItemDropDown
            {
                get
                {
                    return _itemdropdownInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The ItemDropDown item info.
            /// </summary>
            [RepositoryItemInfo("f0cf15a6-4b6a-4085-9131-3b0307fbc992")]
            public virtual RepoItemInfo ItemDropDownInfo
            {
                get
                {
                    return _itemdropdownInfo;
                }
            }

            /// <summary>
            /// The PrepayRefNumber item.
            /// </summary>
            [RepositoryItem("5bf480cd-5484-4cf1-911d-a5a085298c16")]
            public virtual Ranorex.Text PrepayRefNumber
            {
                get
                {
                    return _prepayrefnumberInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The PrepayRefNumber item info.
            /// </summary>
            [RepositoryItemInfo("5bf480cd-5484-4cf1-911d-a5a085298c16")]
            public virtual RepoItemInfo PrepayRefNumberInfo
            {
                get
                {
                    return _prepayrefnumberInfo;
                }
            }

            /// <summary>
            /// The PrepaymentAmount item.
            /// </summary>
            [RepositoryItem("89baeafa-98f6-45b3-897f-4ac7a5fd9d18")]
            public virtual Ranorex.Text PrepaymentAmount
            {
                get
                {
                    return _prepaymentamountInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The PrepaymentAmount item info.
            /// </summary>
            [RepositoryItemInfo("89baeafa-98f6-45b3-897f-4ac7a5fd9d18")]
            public virtual RepoItemInfo PrepaymentAmountInfo
            {
                get
                {
                    return _prepaymentamountInfo;
                }
            }

            /// <summary>
            /// The DirectDepositNum item.
            /// </summary>
            [RepositoryItem("8fded640-fea6-44bb-909a-d6b446a8c376")]
            public virtual Ranorex.Text DirectDepositNum
            {
                get
                {
                    return _directdepositnumInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The DirectDepositNum item info.
            /// </summary>
            [RepositoryItemInfo("8fded640-fea6-44bb-909a-d6b446a8c376")]
            public virtual RepoItemInfo DirectDepositNumInfo
            {
                get
                {
                    return _directdepositnumInfo;
                }
            }

            /// <summary>
            /// The FreightAmount item.
            /// </summary>
            [RepositoryItem("2ade450b-b14d-4ba5-8a35-4fa92ea75f79")]
            public virtual Ranorex.Text FreightAmount
            {
                get
                {
                    return _freightamountInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The FreightAmount item info.
            /// </summary>
            [RepositoryItemInfo("2ade450b-b14d-4ba5-8a35-4fa92ea75f79")]
            public virtual RepoItemInfo FreightAmountInfo
            {
                get
                {
                    return _freightamountInfo;
                }
            }

            /// <summary>
            /// The FreightCode item.
            /// </summary>
            [RepositoryItem("aff995a5-5084-4208-b38f-db129d456818")]
            public virtual Ranorex.Text FreightCode
            {
                get
                {
                    return _freightcodeInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The FreightCode item info.
            /// </summary>
            [RepositoryItemInfo("aff995a5-5084-4208-b38f-db129d456818")]
            public virtual RepoItemInfo FreightCodeInfo
            {
                get
                {
                    return _freightcodeInfo;
                }
            }

            /// <summary>
            /// The FreightTaxTotal item.
            /// </summary>
            [RepositoryItem("a476478f-b010-41b7-9c60-4d88fdbf864b")]
            public virtual Ranorex.Text FreightTaxTotal
            {
                get
                {
                    return _freighttaxtotalInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The FreightTaxTotal item info.
            /// </summary>
            [RepositoryItemInfo("a476478f-b010-41b7-9c60-4d88fdbf864b")]
            public virtual RepoItemInfo FreightTaxTotalInfo
            {
                get
                {
                    return _freighttaxtotalInfo;
                }
            }

            /// <summary>
            /// The FreightTax1 item.
            /// </summary>
            [RepositoryItem("c12ce463-00cf-4d35-a2b4-f63826e8d3fa")]
            public virtual Ranorex.Text FreightTax1
            {
                get
                {
                    return _freighttax1Info.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The FreightTax1 item info.
            /// </summary>
            [RepositoryItemInfo("c12ce463-00cf-4d35-a2b4-f63826e8d3fa")]
            public virtual RepoItemInfo FreightTax1Info
            {
                get
                {
                    return _freighttax1Info;
                }
            }

            /// <summary>
            /// The FreightTax2 item.
            /// </summary>
            [RepositoryItem("d4157de4-e13a-44b3-8bd4-e7f2eff792be")]
            public virtual Ranorex.Text FreightTax2
            {
                get
                {
                    return _freighttax2Info.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The FreightTax2 item info.
            /// </summary>
            [RepositoryItemInfo("d4157de4-e13a-44b3-8bd4-e7f2eff792be")]
            public virtual RepoItemInfo FreightTax2Info
            {
                get
                {
                    return _freighttax2Info;
                }
            }

            /// <summary>
            /// The TermsPercent item.
            /// </summary>
            [RepositoryItem("814b2168-81bf-420e-823f-0d0c2d8bdc49")]
            public virtual Ranorex.Text TermsPercent
            {
                get
                {
                    return _termspercentInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The TermsPercent item info.
            /// </summary>
            [RepositoryItemInfo("814b2168-81bf-420e-823f-0d0c2d8bdc49")]
            public virtual RepoItemInfo TermsPercentInfo
            {
                get
                {
                    return _termspercentInfo;
                }
            }

            /// <summary>
            /// The TermsDay item.
            /// </summary>
            [RepositoryItem("0e81f4d5-f785-45c0-a8f2-c72f36348d63")]
            public virtual Ranorex.Text TermsDay
            {
                get
                {
                    return _termsdayInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The TermsDay item info.
            /// </summary>
            [RepositoryItemInfo("0e81f4d5-f785-45c0-a8f2-c72f36348d63")]
            public virtual RepoItemInfo TermsDayInfo
            {
                get
                {
                    return _termsdayInfo;
                }
            }

            /// <summary>
            /// The TermsNetDays item.
            /// </summary>
            [RepositoryItem("b85661aa-358d-4969-b160-52c8a0d2ec16")]
            public virtual Ranorex.Text TermsNetDays
            {
                get
                {
                    return _termsnetdaysInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The TermsNetDays item info.
            /// </summary>
            [RepositoryItemInfo("b85661aa-358d-4969-b160-52c8a0d2ec16")]
            public virtual RepoItemInfo TermsNetDaysInfo
            {
                get
                {
                    return _termsnetdaysInfo;
                }
            }

            /// <summary>
            /// The EarlyDiscount item.
            /// </summary>
            [RepositoryItem("a3c19f79-a64b-402f-8538-3c60ccf22b63")]
            public virtual Ranorex.Text EarlyDiscount
            {
                get
                {
                    return _earlydiscountInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The EarlyDiscount item info.
            /// </summary>
            [RepositoryItemInfo("a3c19f79-a64b-402f-8538-3c60ccf22b63")]
            public virtual RepoItemInfo EarlyDiscountInfo
            {
                get
                {
                    return _earlydiscountInfo;
                }
            }

            /// <summary>
            /// The TrackShipments item.
            /// </summary>
            [RepositoryItem("215ac230-2461-469f-9353-6c69debb5e82")]
            public virtual Ranorex.Button TrackShipments
            {
                get
                {
                    return _trackshipmentsInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The TrackShipments item info.
            /// </summary>
            [RepositoryItemInfo("215ac230-2461-469f-9353-6c69debb5e82")]
            public virtual RepoItemInfo TrackShipmentsInfo
            {
                get
                {
                    return _trackshipmentsInfo;
                }
            }

            /// <summary>
            /// The RecurringEntry item.
            /// </summary>
            [RepositoryItem("8fd903ab-f8ff-4f74-8fde-0fbcc07d6dc1")]
            public virtual Ranorex.Button RecurringEntry
            {
                get
                {
                    return _recurringentryInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The RecurringEntry item info.
            /// </summary>
            [RepositoryItemInfo("8fd903ab-f8ff-4f74-8fde-0fbcc07d6dc1")]
            public virtual RepoItemInfo RecurringEntryInfo
            {
                get
                {
                    return _recurringentryInfo;
                }
            }

            /// <summary>
            /// The Post item.
            /// </summary>
            [RepositoryItem("dc9abe98-8773-42f0-aede-b372d34aa072")]
            public virtual Ranorex.Button Post
            {
                get
                {
                    return _postInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The Post item info.
            /// </summary>
            [RepositoryItemInfo("dc9abe98-8773-42f0-aede-b372d34aa072")]
            public virtual RepoItemInfo PostInfo
            {
                get
                {
                    return _postInfo;
                }
            }

            /// <summary>
            /// The InvoiceProjectText item.
            /// </summary>
            [RepositoryItem("c9408373-61ad-4a97-b90b-85efb7ecd0d9")]
            public virtual Ranorex.Text InvoiceProjectText
            {
                get
                {
                    return _invoiceprojecttextInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The InvoiceProjectText item info.
            /// </summary>
            [RepositoryItemInfo("c9408373-61ad-4a97-b90b-85efb7ecd0d9")]
            public virtual RepoItemInfo InvoiceProjectTextInfo
            {
                get
                {
                    return _invoiceprojecttextInfo;
                }
            }

            /// <summary>
            /// The ToolBar folder.
            /// </summary>
            [RepositoryFolder("7d085662-2fc9-4685-84f2-5d9c5c9e0d9f")]
            public virtual PurchasesJournalResFolders.ToolBarFolder ToolBar
            {
                get { return _toolbar; }
            }
        }

        /// <summary>
        /// The ToolBarFolder folder.
        /// </summary>
        [RepositoryFolder("7d085662-2fc9-4685-84f2-5d9c5c9e0d9f")]
        public partial class ToolBarFolder : RepoGenBaseFolder
        {
            RepoItemInfo _adjustInfo;
            RepoItemInfo _lookupInfo;

            /// <summary>
            /// Creates a new ToolBar  folder.
            /// </summary>
            public ToolBarFolder(RepoGenBaseFolder parentFolder) :
                    base("ToolBar", "", parentFolder, 1000, null, false, "7d085662-2fc9-4685-84f2-5d9c5c9e0d9f", "")
            {
                _adjustInfo = new RepoItemInfo(this, "Adjust", "?/?/button[@accessiblename='Adjust']", 3000, null, "86eedaa0-72ba-4b21-ad7c-239b5464e87f");
                _lookupInfo = new RepoItemInfo(this, "LookUp", "?/?/button[@accessiblename='Look up']", 3000, null, "83e8688c-c69f-49e3-9b72-afcc04a644c5");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("7d085662-2fc9-4685-84f2-5d9c5c9e0d9f")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("7d085662-2fc9-4685-84f2-5d9c5c9e0d9f")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The Adjust item.
            /// </summary>
            [RepositoryItem("86eedaa0-72ba-4b21-ad7c-239b5464e87f")]
            public virtual Ranorex.Button Adjust
            {
                get
                {
                    return _adjustInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The Adjust item info.
            /// </summary>
            [RepositoryItemInfo("86eedaa0-72ba-4b21-ad7c-239b5464e87f")]
            public virtual RepoItemInfo AdjustInfo
            {
                get
                {
                    return _adjustInfo;
                }
            }

            /// <summary>
            /// The LookUp item.
            /// </summary>
            [RepositoryItem("83e8688c-c69f-49e3-9b72-afcc04a644c5")]
            public virtual Ranorex.Button LookUp
            {
                get
                {
                    return _lookupInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The LookUp item info.
            /// </summary>
            [RepositoryItemInfo("83e8688c-c69f-49e3-9b72-afcc04a644c5")]
            public virtual RepoItemInfo LookUpInfo
            {
                get
                {
                    return _lookupInfo;
                }
            }
        }

        /// <summary>
        /// The TrackShipmentsAppFolder folder.
        /// </summary>
        [RepositoryFolder("768f7f76-bd50-4405-aa9a-3a2bf854f0a3")]
        public partial class TrackShipmentsAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _shippertextInfo;
            RepoItemInfo _shipperInfo;
            RepoItemInfo _okInfo;
            RepoItemInfo _cancelInfo;
            RepoItemInfo _trackingnumberInfo;

            /// <summary>
            /// Creates a new TrackShipments  folder.
            /// </summary>
            public TrackShipmentsAppFolder(RepoGenBaseFolder parentFolder) :
                    base("TrackShipments", "/form[@controlname='TrackShipmentsForm']", parentFolder, 3000, null, true, "768f7f76-bd50-4405-aa9a-3a2bf854f0a3", "")
            {
                _shippertextInfo = new RepoItemInfo(this, "ShipperText", "?/?/text[@controlid='1001']", 3000, null, "bfc027b7-4651-4b4d-905c-e615b748a3f1");
                _shipperInfo = new RepoItemInfo(this, "Shipper", "combobox[@controlname='m_shipperComboBox']", 3000, null, "e8958916-74c8-462a-803e-eaa98416672d");
                _okInfo = new RepoItemInfo(this, "OK", "button[@controlname='m_OKButton']", 3000, null, "11269b7a-e280-412a-88e4-ddb780f839b3");
                _cancelInfo = new RepoItemInfo(this, "Cancel", "button[@controlname='m_cancelButton']", 3000, null, "7f5e4889-77e1-45a4-b4f6-b58f41651184");
                _trackingnumberInfo = new RepoItemInfo(this, "TrackingNumber", "text[@controlname='m_trackingNumberSimplyChar']/text[@accessiblerole='Text']", 3000, null, "4d0b8e7c-e741-47a8-803f-80e43405167f");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("768f7f76-bd50-4405-aa9a-3a2bf854f0a3")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("768f7f76-bd50-4405-aa9a-3a2bf854f0a3")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The ShipperText item.
            /// </summary>
            [RepositoryItem("bfc027b7-4651-4b4d-905c-e615b748a3f1")]
            public virtual Ranorex.Text ShipperText
            {
                get
                {
                    return _shippertextInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The ShipperText item info.
            /// </summary>
            [RepositoryItemInfo("bfc027b7-4651-4b4d-905c-e615b748a3f1")]
            public virtual RepoItemInfo ShipperTextInfo
            {
                get
                {
                    return _shippertextInfo;
                }
            }

            /// <summary>
            /// The Shipper item.
            /// </summary>
            [RepositoryItem("e8958916-74c8-462a-803e-eaa98416672d")]
            public virtual Ranorex.ComboBox Shipper
            {
                get
                {
                    return _shipperInfo.CreateAdapter<Ranorex.ComboBox>(true);
                }
            }

            /// <summary>
            /// The Shipper item info.
            /// </summary>
            [RepositoryItemInfo("e8958916-74c8-462a-803e-eaa98416672d")]
            public virtual RepoItemInfo ShipperInfo
            {
                get
                {
                    return _shipperInfo;
                }
            }

            /// <summary>
            /// The OK item.
            /// </summary>
            [RepositoryItem("11269b7a-e280-412a-88e4-ddb780f839b3")]
            public virtual Ranorex.Button OK
            {
                get
                {
                    return _okInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The OK item info.
            /// </summary>
            [RepositoryItemInfo("11269b7a-e280-412a-88e4-ddb780f839b3")]
            public virtual RepoItemInfo OKInfo
            {
                get
                {
                    return _okInfo;
                }
            }

            /// <summary>
            /// The Cancel item.
            /// </summary>
            [RepositoryItem("7f5e4889-77e1-45a4-b4f6-b58f41651184")]
            public virtual Ranorex.Button Cancel
            {
                get
                {
                    return _cancelInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The Cancel item info.
            /// </summary>
            [RepositoryItemInfo("7f5e4889-77e1-45a4-b4f6-b58f41651184")]
            public virtual RepoItemInfo CancelInfo
            {
                get
                {
                    return _cancelInfo;
                }
            }

            /// <summary>
            /// The TrackingNumber item.
            /// </summary>
            [RepositoryItem("4d0b8e7c-e741-47a8-803f-80e43405167f")]
            public virtual Ranorex.Text TrackingNumber
            {
                get
                {
                    return _trackingnumberInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The TrackingNumber item info.
            /// </summary>
            [RepositoryItemInfo("4d0b8e7c-e741-47a8-803f-80e43405167f")]
            public virtual RepoItemInfo TrackingNumberInfo
            {
                get
                {
                    return _trackingnumberInfo;
                }
            }
        }

    }
#pragma warning restore 0436
}