///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Drawing;
using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace Sage50.Repository
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    /// The class representing the ReportCentreRes element repository.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", "8.0")]
    [RepositoryFolder("eaeee20a-46e0-4cca-9ec1-953335ec2965")]
    public partial class ReportCentreRes : RepoGenBaseFolder
    {
        static ReportCentreRes instance = new ReportCentreRes();
        ReportCentreResFolders.ReportCentreAppFolder _reportcentre;
        ReportCentreResFolders.ReportOptionsAppFolder _reportoptions;
        ReportCentreResFolders.ReportDisplayAppFolder _reportdisplay;

        /// <summary>
        /// Gets the singleton class instance representing the ReportCentreRes element repository.
        /// </summary>
        [RepositoryFolder("eaeee20a-46e0-4cca-9ec1-953335ec2965")]
        public static ReportCentreRes Instance
        {
            get { return instance; }
        }

        /// <summary>
        /// Repository class constructor.
        /// </summary>
        public ReportCentreRes() 
            : base("ReportCentreRes", "/", null, 0, false, "eaeee20a-46e0-4cca-9ec1-953335ec2965", ".\\RepositoryImages\\ReportCentreReseaeee20a.rximgres")
        {
            _reportcentre = new ReportCentreResFolders.ReportCentreAppFolder(this);
            _reportoptions = new ReportCentreResFolders.ReportOptionsAppFolder(this);
            _reportdisplay = new ReportCentreResFolders.ReportDisplayAppFolder(this);
        }

#region Variables

#endregion

        /// <summary>
        /// The Self item info.
        /// </summary>
        [RepositoryItemInfo("eaeee20a-46e0-4cca-9ec1-953335ec2965")]
        public virtual RepoItemInfo SelfInfo
        {
            get
            {
                return _selfInfo;
            }
        }

        /// <summary>
        /// The ReportCentre folder.
        /// </summary>
        [RepositoryFolder("2d21d7ba-e079-45e2-9dd7-3d4e4395c786")]
        public virtual ReportCentreResFolders.ReportCentreAppFolder ReportCentre
        {
            get { return _reportcentre; }
        }

        /// <summary>
        /// The ReportOptions folder.
        /// </summary>
        [RepositoryFolder("01c30076-2b4d-43e6-ae5e-8548eaa8b84f")]
        public virtual ReportCentreResFolders.ReportOptionsAppFolder ReportOptions
        {
            get { return _reportoptions; }
        }

        /// <summary>
        /// The ReportDisplay folder.
        /// </summary>
        [RepositoryFolder("eab6977d-29eb-4eda-80c9-244864ee3625")]
        public virtual ReportCentreResFolders.ReportDisplayAppFolder ReportDisplay
        {
            get { return _reportdisplay; }
        }
    }

    /// <summary>
    /// Inner folder classes.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", "8.0")]
    public partial class ReportCentreResFolders
    {
        /// <summary>
        /// The ReportCentreAppFolder folder.
        /// </summary>
        [RepositoryFolder("2d21d7ba-e079-45e2-9dd7-3d4e4395c786")]
        public partial class ReportCentreAppFolder : RepoGenBaseFolder
        {
            ReportCentreResFolders.ReportsTreeFolder _reportstree;
            RepoItemInfo _reporttypeInfo;
            RepoItemInfo _detailsInfo;
            RepoItemInfo _displayInfo;
            RepoItemInfo _reportlistInfo;
            RepoItemInfo _balancesheetytdInfo;
            RepoItemInfo _customeragedsummaryytdInfo;
            RepoItemInfo _vendoragedsummaryytdInfo;
            RepoItemInfo _yeartodateInfo;
            RepoItemInfo _balancesheet_standardInfo;
            RepoItemInfo _balancesheet_comparativeInfo;
            RepoItemInfo _balancesheet_multiperiodInfo;
            RepoItemInfo _incomestatement_standardInfo;
            RepoItemInfo _incomestatement_comparative2periodInfo;
            RepoItemInfo _incomestatement_comparative4periodInfo;
            RepoItemInfo _incomestatement_multiperiod1Info;
            RepoItemInfo _incomestatement_grossmarginstandardInfo;
            RepoItemInfo _incomestatement_grossmargincomparativeInfo;
            RepoItemInfo _trialbalance_standard2Info;
            RepoItemInfo _trialbalance_comparative1Info;
            RepoItemInfo _trialbalance_netchangesforperiodInfo;
            RepoItemInfo _trialbalance_multiperiodInfo;

            /// <summary>
            /// Creates a new ReportCentre  folder.
            /// </summary>
            public ReportCentreAppFolder(RepoGenBaseFolder parentFolder) :
                    base("ReportCentre", "/form[@title='Report Centre']", parentFolder, 3000, null, true, "2d21d7ba-e079-45e2-9dd7-3d4e4395c786", "")
            {
                _reportstree = new ReportCentreResFolders.ReportsTreeFolder(this);
                _reporttypeInfo = new RepoItemInfo(this, "ReportType", "text[@controlid='2501']", 3000, null, "17639024-46f8-4d10-a99a-a1b09c6a791b");
                _detailsInfo = new RepoItemInfo(this, "Details", "text[@controlid='2506']", 3000, null, "8ef8d5f9-b807-4e01-a698-92d19d99dcc2");
                _displayInfo = new RepoItemInfo(this, "Display", "button[@text='&Create']", 30000, null, "7886ad81-c881-4304-a3ff-37a101fe7864");
                _reportlistInfo = new RepoItemInfo(this, "ReportList", "element[@controlid='2502']", 30000, null, "e031a093-40e5-49a6-aa33-faeef61677c3");
                _balancesheetytdInfo = new RepoItemInfo(this, "BalanceSheetYTD", ".//treeitem[@accessiblename='Year to Date']/treeitem[@accessiblename='Balance Sheet YTD']", 30000, null, "06e36a72-36fa-43ec-925e-e2bbabaa3094");
                _customeragedsummaryytdInfo = new RepoItemInfo(this, "CustomerAgedSummaryYTD", ".//treeitem[@accessiblename='Year to Date']/treeitem[@accessiblename='Customer Aged Summary YTD']", 30000, null, "4dec617f-5976-4131-b859-44771093d70d");
                _vendoragedsummaryytdInfo = new RepoItemInfo(this, "VendorAgedSummaryYTD", ".//treeitem[@accessiblename='Year to Date']/treeitem[@accessiblename='Vendor Aged Summary YTD']", 30000, null, "d53341b1-7f60-4977-8238-3091a559d87c");
                _yeartodateInfo = new RepoItemInfo(this, "YearToDate", "?/?/tree[@accessiblerole='Outline']/treeitem[@accessiblename='Year to Date']", 30000, null, "d6e6c9ea-d953-4594-a6d8-19e79d222731");
                _balancesheet_standardInfo = new RepoItemInfo(this, "BalanceSheet_Standard", ".//treeitem[@accessiblename='Balance Sheet']/treeitem[@accessiblename='Standard']", 30000, null, "38ebfd1c-69b2-4fb5-8fcc-8c40ca59c1b0");
                _balancesheet_comparativeInfo = new RepoItemInfo(this, "BalanceSheet_Comparative", ".//treeitem[@accessiblename='Balance Sheet']/treeitem[@accessiblename='Comparative']", 30000, null, "61fa6f64-047c-4d43-919b-9bceaa5831e3");
                _balancesheet_multiperiodInfo = new RepoItemInfo(this, "BalanceSheet_MultiPeriod", ".//treeitem[@accessiblename='Balance Sheet']/treeitem[@accessiblename='Multi-Period']", 30000, null, "e6e4e153-b27a-4177-93c2-245785db9dd2");
                _incomestatement_standardInfo = new RepoItemInfo(this, "IncomeStatement_Standard", ".//treeitem[@accessiblename='Income Statement']/treeitem[@accessiblename='Standard']", 30000, null, "ab56c225-40fe-4991-96dc-e56e7affbfa6");
                _incomestatement_comparative2periodInfo = new RepoItemInfo(this, "IncomeStatement_Comparative2Period", ".//treeitem[@accessiblename='Income Statement']/treeitem[@accessiblename='Comparative 2 Period']", 30000, null, "c6efccc7-1305-47b2-accc-def76e5e2f5d");
                _incomestatement_comparative4periodInfo = new RepoItemInfo(this, "IncomeStatement_Comparative4Period", ".//treeitem[@accessiblename='Income Statement']/treeitem[@accessiblename='Comparative 4 Period']", 30000, null, "2e805805-63da-42bb-952e-8bfcac702ee9");
                _incomestatement_multiperiod1Info = new RepoItemInfo(this, "IncomeStatement_MultiPeriod1", ".//treeitem[@accessiblename='Income Statement']/treeitem[@accessiblename='Multi-Period']", 30000, null, "d6d7e454-e493-4572-9c60-f496c8d83871");
                _incomestatement_grossmarginstandardInfo = new RepoItemInfo(this, "IncomeStatement_GrossMarginStandard", ".//treeitem[@accessiblename='Income Statement']/treeitem[@accessiblename='Gross Margin - Standard']", 30000, null, "6adef295-fdbf-4317-b34f-6e2a2d320dff");
                _incomestatement_grossmargincomparativeInfo = new RepoItemInfo(this, "IncomeStatement_GrossMarginComparative", ".//treeitem[@accessiblename='Income Statement']/treeitem[@accessiblename~'^Gross\\ Margin\\ -\\ Comparativ']", 30000, null, "c67ebc86-b340-4a80-b3cf-b2dc8a8186f8");
                _trialbalance_standard2Info = new RepoItemInfo(this, "TrialBalance_Standard2", ".//treeitem[@accessiblename='Trial Balance']/treeitem[@accessiblename='Standard']", 30000, null, "9a70974d-545b-4b48-be01-574fb4c61a42");
                _trialbalance_comparative1Info = new RepoItemInfo(this, "TrialBalance_Comparative1", ".//treeitem[@accessiblename='Trial Balance']/treeitem[@accessiblename='Comparative']", 30000, null, "24a6aa9e-3fa4-4ab4-9b0b-f9bf9f2685f8");
                _trialbalance_netchangesforperiodInfo = new RepoItemInfo(this, "TrialBalance_NetChangesForPeriod", ".//treeitem[@accessiblename='Trial Balance']/treeitem[@accessiblename='Net Changes for Period']", 30000, null, "584c4af2-78ec-4fee-85cf-4bd0d87a588e");
                _trialbalance_multiperiodInfo = new RepoItemInfo(this, "TrialBalance_MultiPeriod", ".//treeitem[@accessiblename='Trial Balance']/treeitem[@accessiblename='Multi-Period']", 30000, null, "d1a2505f-3ef6-45e6-bf2c-1967800a54da");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("2d21d7ba-e079-45e2-9dd7-3d4e4395c786")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("2d21d7ba-e079-45e2-9dd7-3d4e4395c786")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The ReportType item.
            /// </summary>
            [RepositoryItem("17639024-46f8-4d10-a99a-a1b09c6a791b")]
            public virtual Ranorex.Text ReportType
            {
                get
                {
                    return _reporttypeInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The ReportType item info.
            /// </summary>
            [RepositoryItemInfo("17639024-46f8-4d10-a99a-a1b09c6a791b")]
            public virtual RepoItemInfo ReportTypeInfo
            {
                get
                {
                    return _reporttypeInfo;
                }
            }

            /// <summary>
            /// The Details item.
            /// </summary>
            [RepositoryItem("8ef8d5f9-b807-4e01-a698-92d19d99dcc2")]
            public virtual Ranorex.Text Details
            {
                get
                {
                    return _detailsInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The Details item info.
            /// </summary>
            [RepositoryItemInfo("8ef8d5f9-b807-4e01-a698-92d19d99dcc2")]
            public virtual RepoItemInfo DetailsInfo
            {
                get
                {
                    return _detailsInfo;
                }
            }

            /// <summary>
            /// The Display item.
            /// </summary>
            [RepositoryItem("7886ad81-c881-4304-a3ff-37a101fe7864")]
            public virtual Ranorex.Button Display
            {
                get
                {
                    return _displayInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The Display item info.
            /// </summary>
            [RepositoryItemInfo("7886ad81-c881-4304-a3ff-37a101fe7864")]
            public virtual RepoItemInfo DisplayInfo
            {
                get
                {
                    return _displayInfo;
                }
            }

            /// <summary>
            /// The ReportList item.
            /// </summary>
            [RepositoryItem("e031a093-40e5-49a6-aa33-faeef61677c3")]
            public virtual Ranorex.Unknown ReportList
            {
                get
                {
                    return _reportlistInfo.CreateAdapter<Ranorex.Unknown>(true);
                }
            }

            /// <summary>
            /// The ReportList item info.
            /// </summary>
            [RepositoryItemInfo("e031a093-40e5-49a6-aa33-faeef61677c3")]
            public virtual RepoItemInfo ReportListInfo
            {
                get
                {
                    return _reportlistInfo;
                }
            }

            /// <summary>
            /// The BalanceSheetYTD item.
            /// </summary>
            [RepositoryItem("06e36a72-36fa-43ec-925e-e2bbabaa3094")]
            public virtual Ranorex.TreeItem BalanceSheetYTD
            {
                get
                {
                    return _balancesheetytdInfo.CreateAdapter<Ranorex.TreeItem>(true);
                }
            }

            /// <summary>
            /// The BalanceSheetYTD item info.
            /// </summary>
            [RepositoryItemInfo("06e36a72-36fa-43ec-925e-e2bbabaa3094")]
            public virtual RepoItemInfo BalanceSheetYTDInfo
            {
                get
                {
                    return _balancesheetytdInfo;
                }
            }

            /// <summary>
            /// The CustomerAgedSummaryYTD item.
            /// </summary>
            [RepositoryItem("4dec617f-5976-4131-b859-44771093d70d")]
            public virtual Ranorex.TreeItem CustomerAgedSummaryYTD
            {
                get
                {
                    return _customeragedsummaryytdInfo.CreateAdapter<Ranorex.TreeItem>(true);
                }
            }

            /// <summary>
            /// The CustomerAgedSummaryYTD item info.
            /// </summary>
            [RepositoryItemInfo("4dec617f-5976-4131-b859-44771093d70d")]
            public virtual RepoItemInfo CustomerAgedSummaryYTDInfo
            {
                get
                {
                    return _customeragedsummaryytdInfo;
                }
            }

            /// <summary>
            /// The VendorAgedSummaryYTD item.
            /// </summary>
            [RepositoryItem("d53341b1-7f60-4977-8238-3091a559d87c")]
            public virtual Ranorex.TreeItem VendorAgedSummaryYTD
            {
                get
                {
                    return _vendoragedsummaryytdInfo.CreateAdapter<Ranorex.TreeItem>(true);
                }
            }

            /// <summary>
            /// The VendorAgedSummaryYTD item info.
            /// </summary>
            [RepositoryItemInfo("d53341b1-7f60-4977-8238-3091a559d87c")]
            public virtual RepoItemInfo VendorAgedSummaryYTDInfo
            {
                get
                {
                    return _vendoragedsummaryytdInfo;
                }
            }

            /// <summary>
            /// The YearToDate item.
            /// </summary>
            [RepositoryItem("d6e6c9ea-d953-4594-a6d8-19e79d222731")]
            public virtual Ranorex.TreeItem YearToDate
            {
                get
                {
                    return _yeartodateInfo.CreateAdapter<Ranorex.TreeItem>(true);
                }
            }

            /// <summary>
            /// The YearToDate item info.
            /// </summary>
            [RepositoryItemInfo("d6e6c9ea-d953-4594-a6d8-19e79d222731")]
            public virtual RepoItemInfo YearToDateInfo
            {
                get
                {
                    return _yeartodateInfo;
                }
            }

            /// <summary>
            /// The BalanceSheet_Standard item.
            /// </summary>
            [RepositoryItem("38ebfd1c-69b2-4fb5-8fcc-8c40ca59c1b0")]
            public virtual Ranorex.TreeItem BalanceSheet_Standard
            {
                get
                {
                    return _balancesheet_standardInfo.CreateAdapter<Ranorex.TreeItem>(true);
                }
            }

            /// <summary>
            /// The BalanceSheet_Standard item info.
            /// </summary>
            [RepositoryItemInfo("38ebfd1c-69b2-4fb5-8fcc-8c40ca59c1b0")]
            public virtual RepoItemInfo BalanceSheet_StandardInfo
            {
                get
                {
                    return _balancesheet_standardInfo;
                }
            }

            /// <summary>
            /// The BalanceSheet_Comparative item.
            /// </summary>
            [RepositoryItem("61fa6f64-047c-4d43-919b-9bceaa5831e3")]
            public virtual Ranorex.TreeItem BalanceSheet_Comparative
            {
                get
                {
                    return _balancesheet_comparativeInfo.CreateAdapter<Ranorex.TreeItem>(true);
                }
            }

            /// <summary>
            /// The BalanceSheet_Comparative item info.
            /// </summary>
            [RepositoryItemInfo("61fa6f64-047c-4d43-919b-9bceaa5831e3")]
            public virtual RepoItemInfo BalanceSheet_ComparativeInfo
            {
                get
                {
                    return _balancesheet_comparativeInfo;
                }
            }

            /// <summary>
            /// The BalanceSheet_MultiPeriod item.
            /// </summary>
            [RepositoryItem("e6e4e153-b27a-4177-93c2-245785db9dd2")]
            public virtual Ranorex.TreeItem BalanceSheet_MultiPeriod
            {
                get
                {
                    return _balancesheet_multiperiodInfo.CreateAdapter<Ranorex.TreeItem>(true);
                }
            }

            /// <summary>
            /// The BalanceSheet_MultiPeriod item info.
            /// </summary>
            [RepositoryItemInfo("e6e4e153-b27a-4177-93c2-245785db9dd2")]
            public virtual RepoItemInfo BalanceSheet_MultiPeriodInfo
            {
                get
                {
                    return _balancesheet_multiperiodInfo;
                }
            }

            /// <summary>
            /// The IncomeStatement_Standard item.
            /// </summary>
            [RepositoryItem("ab56c225-40fe-4991-96dc-e56e7affbfa6")]
            public virtual Ranorex.TreeItem IncomeStatement_Standard
            {
                get
                {
                    return _incomestatement_standardInfo.CreateAdapter<Ranorex.TreeItem>(true);
                }
            }

            /// <summary>
            /// The IncomeStatement_Standard item info.
            /// </summary>
            [RepositoryItemInfo("ab56c225-40fe-4991-96dc-e56e7affbfa6")]
            public virtual RepoItemInfo IncomeStatement_StandardInfo
            {
                get
                {
                    return _incomestatement_standardInfo;
                }
            }

            /// <summary>
            /// The IncomeStatement_Comparative2Period item.
            /// </summary>
            [RepositoryItem("c6efccc7-1305-47b2-accc-def76e5e2f5d")]
            public virtual Ranorex.TreeItem IncomeStatement_Comparative2Period
            {
                get
                {
                    return _incomestatement_comparative2periodInfo.CreateAdapter<Ranorex.TreeItem>(true);
                }
            }

            /// <summary>
            /// The IncomeStatement_Comparative2Period item info.
            /// </summary>
            [RepositoryItemInfo("c6efccc7-1305-47b2-accc-def76e5e2f5d")]
            public virtual RepoItemInfo IncomeStatement_Comparative2PeriodInfo
            {
                get
                {
                    return _incomestatement_comparative2periodInfo;
                }
            }

            /// <summary>
            /// The IncomeStatement_Comparative4Period item.
            /// </summary>
            [RepositoryItem("2e805805-63da-42bb-952e-8bfcac702ee9")]
            public virtual Ranorex.TreeItem IncomeStatement_Comparative4Period
            {
                get
                {
                    return _incomestatement_comparative4periodInfo.CreateAdapter<Ranorex.TreeItem>(true);
                }
            }

            /// <summary>
            /// The IncomeStatement_Comparative4Period item info.
            /// </summary>
            [RepositoryItemInfo("2e805805-63da-42bb-952e-8bfcac702ee9")]
            public virtual RepoItemInfo IncomeStatement_Comparative4PeriodInfo
            {
                get
                {
                    return _incomestatement_comparative4periodInfo;
                }
            }

            /// <summary>
            /// The IncomeStatement_MultiPeriod1 item.
            /// </summary>
            [RepositoryItem("d6d7e454-e493-4572-9c60-f496c8d83871")]
            public virtual Ranorex.TreeItem IncomeStatement_MultiPeriod1
            {
                get
                {
                    return _incomestatement_multiperiod1Info.CreateAdapter<Ranorex.TreeItem>(true);
                }
            }

            /// <summary>
            /// The IncomeStatement_MultiPeriod1 item info.
            /// </summary>
            [RepositoryItemInfo("d6d7e454-e493-4572-9c60-f496c8d83871")]
            public virtual RepoItemInfo IncomeStatement_MultiPeriod1Info
            {
                get
                {
                    return _incomestatement_multiperiod1Info;
                }
            }

            /// <summary>
            /// The IncomeStatement_GrossMarginStandard item.
            /// </summary>
            [RepositoryItem("6adef295-fdbf-4317-b34f-6e2a2d320dff")]
            public virtual Ranorex.TreeItem IncomeStatement_GrossMarginStandard
            {
                get
                {
                    return _incomestatement_grossmarginstandardInfo.CreateAdapter<Ranorex.TreeItem>(true);
                }
            }

            /// <summary>
            /// The IncomeStatement_GrossMarginStandard item info.
            /// </summary>
            [RepositoryItemInfo("6adef295-fdbf-4317-b34f-6e2a2d320dff")]
            public virtual RepoItemInfo IncomeStatement_GrossMarginStandardInfo
            {
                get
                {
                    return _incomestatement_grossmarginstandardInfo;
                }
            }

            /// <summary>
            /// The IncomeStatement_GrossMarginComparative item.
            /// </summary>
            [RepositoryItem("c67ebc86-b340-4a80-b3cf-b2dc8a8186f8")]
            public virtual Ranorex.TreeItem IncomeStatement_GrossMarginComparative
            {
                get
                {
                    return _incomestatement_grossmargincomparativeInfo.CreateAdapter<Ranorex.TreeItem>(true);
                }
            }

            /// <summary>
            /// The IncomeStatement_GrossMarginComparative item info.
            /// </summary>
            [RepositoryItemInfo("c67ebc86-b340-4a80-b3cf-b2dc8a8186f8")]
            public virtual RepoItemInfo IncomeStatement_GrossMarginComparativeInfo
            {
                get
                {
                    return _incomestatement_grossmargincomparativeInfo;
                }
            }

            /// <summary>
            /// The TrialBalance_Standard2 item.
            /// </summary>
            [RepositoryItem("9a70974d-545b-4b48-be01-574fb4c61a42")]
            public virtual Ranorex.TreeItem TrialBalance_Standard2
            {
                get
                {
                    return _trialbalance_standard2Info.CreateAdapter<Ranorex.TreeItem>(true);
                }
            }

            /// <summary>
            /// The TrialBalance_Standard2 item info.
            /// </summary>
            [RepositoryItemInfo("9a70974d-545b-4b48-be01-574fb4c61a42")]
            public virtual RepoItemInfo TrialBalance_Standard2Info
            {
                get
                {
                    return _trialbalance_standard2Info;
                }
            }

            /// <summary>
            /// The TrialBalance_Comparative1 item.
            /// </summary>
            [RepositoryItem("24a6aa9e-3fa4-4ab4-9b0b-f9bf9f2685f8")]
            public virtual Ranorex.TreeItem TrialBalance_Comparative1
            {
                get
                {
                    return _trialbalance_comparative1Info.CreateAdapter<Ranorex.TreeItem>(true);
                }
            }

            /// <summary>
            /// The TrialBalance_Comparative1 item info.
            /// </summary>
            [RepositoryItemInfo("24a6aa9e-3fa4-4ab4-9b0b-f9bf9f2685f8")]
            public virtual RepoItemInfo TrialBalance_Comparative1Info
            {
                get
                {
                    return _trialbalance_comparative1Info;
                }
            }

            /// <summary>
            /// The TrialBalance_NetChangesForPeriod item.
            /// </summary>
            [RepositoryItem("584c4af2-78ec-4fee-85cf-4bd0d87a588e")]
            public virtual Ranorex.TreeItem TrialBalance_NetChangesForPeriod
            {
                get
                {
                    return _trialbalance_netchangesforperiodInfo.CreateAdapter<Ranorex.TreeItem>(true);
                }
            }

            /// <summary>
            /// The TrialBalance_NetChangesForPeriod item info.
            /// </summary>
            [RepositoryItemInfo("584c4af2-78ec-4fee-85cf-4bd0d87a588e")]
            public virtual RepoItemInfo TrialBalance_NetChangesForPeriodInfo
            {
                get
                {
                    return _trialbalance_netchangesforperiodInfo;
                }
            }

            /// <summary>
            /// The TrialBalance_MultiPeriod item.
            /// </summary>
            [RepositoryItem("d1a2505f-3ef6-45e6-bf2c-1967800a54da")]
            public virtual Ranorex.TreeItem TrialBalance_MultiPeriod
            {
                get
                {
                    return _trialbalance_multiperiodInfo.CreateAdapter<Ranorex.TreeItem>(true);
                }
            }

            /// <summary>
            /// The TrialBalance_MultiPeriod item info.
            /// </summary>
            [RepositoryItemInfo("d1a2505f-3ef6-45e6-bf2c-1967800a54da")]
            public virtual RepoItemInfo TrialBalance_MultiPeriodInfo
            {
                get
                {
                    return _trialbalance_multiperiodInfo;
                }
            }

            /// <summary>
            /// The ReportsTree folder.
            /// </summary>
            [RepositoryFolder("9c85d410-22b9-44ca-aa12-6c78fb12999d")]
            public virtual ReportCentreResFolders.ReportsTreeFolder ReportsTree
            {
                get { return _reportstree; }
            }
        }

        /// <summary>
        /// The ReportsTreeFolder folder.
        /// </summary>
        [RepositoryFolder("9c85d410-22b9-44ca-aa12-6c78fb12999d")]
        public partial class ReportsTreeFolder : RepoGenBaseFolder
        {
            RepoItemInfo _alljournalentriesInfo;
            RepoItemInfo _balancesheetInfo;
            RepoItemInfo _budgetInfo;
            RepoItemInfo _generalledgerInfo;
            RepoItemInfo _incomestatementInfo;
            RepoItemInfo _statementofcashflowsInfo;
            RepoItemInfo _trialbalanceInfo;
            RepoItemInfo _cashflowprojectiondetailInfo;
            RepoItemInfo _cashflowprojectionsummaryInfo;
            RepoItemInfo _realizedexchangegainorlossInfo;
            RepoItemInfo _unrealizedexchangegainorlossInfo;

            /// <summary>
            /// Creates a new ReportsTree  folder.
            /// </summary>
            public ReportsTreeFolder(RepoGenBaseFolder parentFolder) :
                    base("ReportsTree", "?/?/tree[@accessiblerole='Outline']", parentFolder, 30000, null, false, "9c85d410-22b9-44ca-aa12-6c78fb12999d", "")
            {
                _alljournalentriesInfo = new RepoItemInfo(this, "AllJournalEntries", "treeitem[@accessiblename='All Journal Entries']", 30000, null, "5be5d4bd-7014-4a89-a915-0f787071cfd8");
                _balancesheetInfo = new RepoItemInfo(this, "BalanceSheet", "treeitem[@accessiblename='Balance Sheet']", 30000, null, "ab8af46b-bf92-41f9-8cb4-3eaaf8d460f8");
                _budgetInfo = new RepoItemInfo(this, "Budget", "treeitem[@accessiblename='Budget']", 30000, null, "57db22a3-fafb-4c67-9370-daf523939d92");
                _generalledgerInfo = new RepoItemInfo(this, "GeneralLedger", "treeitem[@accessiblename='General Ledger']", 30000, null, "48345f6b-2bb1-4b3b-b8c2-84f7d3d38f95");
                _incomestatementInfo = new RepoItemInfo(this, "IncomeStatement", "treeitem[@accessiblename='Income Statement']", 30000, null, "58270af7-2020-4f5d-a8a5-d3130b3ac95e");
                _statementofcashflowsInfo = new RepoItemInfo(this, "StatementOfCashFlows", "treeitem[@accessiblename='Statement of Cash Flows']", 30000, null, "839d1e28-5e01-4e3f-8af4-bca7ec2102d0");
                _trialbalanceInfo = new RepoItemInfo(this, "TrialBalance", "treeitem[@accessiblename='Trial Balance']", 30000, null, "d137e274-f116-4b6b-b8b2-273a3a4db256");
                _cashflowprojectiondetailInfo = new RepoItemInfo(this, "CashFlowProjectionDetail", "treeitem[@accessiblename~'^Cash\\ Flow\\ Projection\\ Deta']", 30000, null, "02c30829-4dca-47b5-bcba-e10641c3be3c");
                _cashflowprojectionsummaryInfo = new RepoItemInfo(this, "CashFlowProjectionSummary", "treeitem[@accessiblename~'^Cash\\ Flow\\ Projection\\ Summ']", 30000, null, "da26024c-6992-4447-9f96-149467bf0a16");
                _realizedexchangegainorlossInfo = new RepoItemInfo(this, "RealizedExchangeGainOrLoss", "treeitem[@accessiblename~'^Realized\\ Exchange\\ Gain\\ or']", 30000, null, "17c2f0fd-c029-45c4-9974-d4f58e6d6d1f");
                _unrealizedexchangegainorlossInfo = new RepoItemInfo(this, "UnrealizedExchangeGainOrLoss", "treeitem[@accessiblename~'^Unrealized\\ Exchange\\ Gain\\ ']", 30000, null, "4bc1ad1c-49f9-4aed-ae32-e87d65ff8b4f");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("9c85d410-22b9-44ca-aa12-6c78fb12999d")]
            public virtual Ranorex.Tree Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Tree>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("9c85d410-22b9-44ca-aa12-6c78fb12999d")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The AllJournalEntries item.
            /// </summary>
            [RepositoryItem("5be5d4bd-7014-4a89-a915-0f787071cfd8")]
            public virtual Ranorex.TreeItem AllJournalEntries
            {
                get
                {
                    return _alljournalentriesInfo.CreateAdapter<Ranorex.TreeItem>(true);
                }
            }

            /// <summary>
            /// The AllJournalEntries item info.
            /// </summary>
            [RepositoryItemInfo("5be5d4bd-7014-4a89-a915-0f787071cfd8")]
            public virtual RepoItemInfo AllJournalEntriesInfo
            {
                get
                {
                    return _alljournalentriesInfo;
                }
            }

            /// <summary>
            /// The BalanceSheet item.
            /// </summary>
            [RepositoryItem("ab8af46b-bf92-41f9-8cb4-3eaaf8d460f8")]
            public virtual Ranorex.TreeItem BalanceSheet
            {
                get
                {
                    return _balancesheetInfo.CreateAdapter<Ranorex.TreeItem>(true);
                }
            }

            /// <summary>
            /// The BalanceSheet item info.
            /// </summary>
            [RepositoryItemInfo("ab8af46b-bf92-41f9-8cb4-3eaaf8d460f8")]
            public virtual RepoItemInfo BalanceSheetInfo
            {
                get
                {
                    return _balancesheetInfo;
                }
            }

            /// <summary>
            /// The Budget item.
            /// </summary>
            [RepositoryItem("57db22a3-fafb-4c67-9370-daf523939d92")]
            public virtual Ranorex.TreeItem Budget
            {
                get
                {
                    return _budgetInfo.CreateAdapter<Ranorex.TreeItem>(true);
                }
            }

            /// <summary>
            /// The Budget item info.
            /// </summary>
            [RepositoryItemInfo("57db22a3-fafb-4c67-9370-daf523939d92")]
            public virtual RepoItemInfo BudgetInfo
            {
                get
                {
                    return _budgetInfo;
                }
            }

            /// <summary>
            /// The GeneralLedger item.
            /// </summary>
            [RepositoryItem("48345f6b-2bb1-4b3b-b8c2-84f7d3d38f95")]
            public virtual Ranorex.TreeItem GeneralLedger
            {
                get
                {
                    return _generalledgerInfo.CreateAdapter<Ranorex.TreeItem>(true);
                }
            }

            /// <summary>
            /// The GeneralLedger item info.
            /// </summary>
            [RepositoryItemInfo("48345f6b-2bb1-4b3b-b8c2-84f7d3d38f95")]
            public virtual RepoItemInfo GeneralLedgerInfo
            {
                get
                {
                    return _generalledgerInfo;
                }
            }

            /// <summary>
            /// The IncomeStatement item.
            /// </summary>
            [RepositoryItem("58270af7-2020-4f5d-a8a5-d3130b3ac95e")]
            public virtual Ranorex.TreeItem IncomeStatement
            {
                get
                {
                    return _incomestatementInfo.CreateAdapter<Ranorex.TreeItem>(true);
                }
            }

            /// <summary>
            /// The IncomeStatement item info.
            /// </summary>
            [RepositoryItemInfo("58270af7-2020-4f5d-a8a5-d3130b3ac95e")]
            public virtual RepoItemInfo IncomeStatementInfo
            {
                get
                {
                    return _incomestatementInfo;
                }
            }

            /// <summary>
            /// The StatementOfCashFlows item.
            /// </summary>
            [RepositoryItem("839d1e28-5e01-4e3f-8af4-bca7ec2102d0")]
            public virtual Ranorex.TreeItem StatementOfCashFlows
            {
                get
                {
                    return _statementofcashflowsInfo.CreateAdapter<Ranorex.TreeItem>(true);
                }
            }

            /// <summary>
            /// The StatementOfCashFlows item info.
            /// </summary>
            [RepositoryItemInfo("839d1e28-5e01-4e3f-8af4-bca7ec2102d0")]
            public virtual RepoItemInfo StatementOfCashFlowsInfo
            {
                get
                {
                    return _statementofcashflowsInfo;
                }
            }

            /// <summary>
            /// The TrialBalance item.
            /// </summary>
            [RepositoryItem("d137e274-f116-4b6b-b8b2-273a3a4db256")]
            public virtual Ranorex.TreeItem TrialBalance
            {
                get
                {
                    return _trialbalanceInfo.CreateAdapter<Ranorex.TreeItem>(true);
                }
            }

            /// <summary>
            /// The TrialBalance item info.
            /// </summary>
            [RepositoryItemInfo("d137e274-f116-4b6b-b8b2-273a3a4db256")]
            public virtual RepoItemInfo TrialBalanceInfo
            {
                get
                {
                    return _trialbalanceInfo;
                }
            }

            /// <summary>
            /// The CashFlowProjectionDetail item.
            /// </summary>
            [RepositoryItem("02c30829-4dca-47b5-bcba-e10641c3be3c")]
            public virtual Ranorex.TreeItem CashFlowProjectionDetail
            {
                get
                {
                    return _cashflowprojectiondetailInfo.CreateAdapter<Ranorex.TreeItem>(true);
                }
            }

            /// <summary>
            /// The CashFlowProjectionDetail item info.
            /// </summary>
            [RepositoryItemInfo("02c30829-4dca-47b5-bcba-e10641c3be3c")]
            public virtual RepoItemInfo CashFlowProjectionDetailInfo
            {
                get
                {
                    return _cashflowprojectiondetailInfo;
                }
            }

            /// <summary>
            /// The CashFlowProjectionSummary item.
            /// </summary>
            [RepositoryItem("da26024c-6992-4447-9f96-149467bf0a16")]
            public virtual Ranorex.TreeItem CashFlowProjectionSummary
            {
                get
                {
                    return _cashflowprojectionsummaryInfo.CreateAdapter<Ranorex.TreeItem>(true);
                }
            }

            /// <summary>
            /// The CashFlowProjectionSummary item info.
            /// </summary>
            [RepositoryItemInfo("da26024c-6992-4447-9f96-149467bf0a16")]
            public virtual RepoItemInfo CashFlowProjectionSummaryInfo
            {
                get
                {
                    return _cashflowprojectionsummaryInfo;
                }
            }

            /// <summary>
            /// The RealizedExchangeGainOrLoss item.
            /// </summary>
            [RepositoryItem("17c2f0fd-c029-45c4-9974-d4f58e6d6d1f")]
            public virtual Ranorex.TreeItem RealizedExchangeGainOrLoss
            {
                get
                {
                    return _realizedexchangegainorlossInfo.CreateAdapter<Ranorex.TreeItem>(true);
                }
            }

            /// <summary>
            /// The RealizedExchangeGainOrLoss item info.
            /// </summary>
            [RepositoryItemInfo("17c2f0fd-c029-45c4-9974-d4f58e6d6d1f")]
            public virtual RepoItemInfo RealizedExchangeGainOrLossInfo
            {
                get
                {
                    return _realizedexchangegainorlossInfo;
                }
            }

            /// <summary>
            /// The UnrealizedExchangeGainOrLoss item.
            /// </summary>
            [RepositoryItem("4bc1ad1c-49f9-4aed-ae32-e87d65ff8b4f")]
            public virtual Ranorex.TreeItem UnrealizedExchangeGainOrLoss
            {
                get
                {
                    return _unrealizedexchangegainorlossInfo.CreateAdapter<Ranorex.TreeItem>(true);
                }
            }

            /// <summary>
            /// The UnrealizedExchangeGainOrLoss item info.
            /// </summary>
            [RepositoryItemInfo("4bc1ad1c-49f9-4aed-ae32-e87d65ff8b4f")]
            public virtual RepoItemInfo UnrealizedExchangeGainOrLossInfo
            {
                get
                {
                    return _unrealizedexchangegainorlossInfo;
                }
            }
        }

        /// <summary>
        /// The ReportOptionsAppFolder folder.
        /// </summary>
        [RepositoryFolder("01c30076-2b4d-43e6-ae5e-8548eaa8b84f")]
        public partial class ReportOptionsAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _okInfo;
            RepoItemInfo _detailbtnInfo;
            RepoItemInfo _vendorageddetailbtnInfo;
            RepoItemInfo _employeedetailbtnInfo;

            /// <summary>
            /// Creates a new ReportOptions  folder.
            /// </summary>
            public ReportOptionsAppFolder(RepoGenBaseFolder parentFolder) :
                    base("ReportOptions", "/form[@controlname='ReportOptionsForm']", parentFolder, 3000, null, true, "01c30076-2b4d-43e6-ae5e-8548eaa8b84f", "")
            {
                _okInfo = new RepoItemInfo(this, "OK", "button[@controlname='m_OKButton']", 3000, null, "e3f8047c-f92a-4607-bc1c-fc9aed24b3b2");
                _detailbtnInfo = new RepoItemInfo(this, "DetailBtn", "?/?/container[@controlname='m_summaryDetailControl']/radiobutton[@controlname='m_detailRdBtn']", 3000, null, "03eb8529-6757-42d4-a0e3-30f34570f0e6");
                _vendorageddetailbtnInfo = new RepoItemInfo(this, "VendorAgedDetailBtn", "container[@controlname='VCAgedOptionsForm']/?/?/radiobutton[@controlname='m_detailRdBtn']", 3000, null, "49c3da82-f17a-401a-8326-9b13ccf2718d");
                _employeedetailbtnInfo = new RepoItemInfo(this, "EmployeeDetailBtn", "container[@controlname='EmployeeRptOptForm']/?/?/radiobutton[@controlname='m_detailRdBtn']", 3000, null, "595418ed-e03a-4366-8494-213c13c4ce3b");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("01c30076-2b4d-43e6-ae5e-8548eaa8b84f")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("01c30076-2b4d-43e6-ae5e-8548eaa8b84f")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The OK item.
            /// </summary>
            [RepositoryItem("e3f8047c-f92a-4607-bc1c-fc9aed24b3b2")]
            public virtual Ranorex.Button OK
            {
                get
                {
                    return _okInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The OK item info.
            /// </summary>
            [RepositoryItemInfo("e3f8047c-f92a-4607-bc1c-fc9aed24b3b2")]
            public virtual RepoItemInfo OKInfo
            {
                get
                {
                    return _okInfo;
                }
            }

            /// <summary>
            /// The DetailBtn item.
            /// </summary>
            [RepositoryItem("03eb8529-6757-42d4-a0e3-30f34570f0e6")]
            public virtual Ranorex.RadioButton DetailBtn
            {
                get
                {
                    return _detailbtnInfo.CreateAdapter<Ranorex.RadioButton>(true);
                }
            }

            /// <summary>
            /// The DetailBtn item info.
            /// </summary>
            [RepositoryItemInfo("03eb8529-6757-42d4-a0e3-30f34570f0e6")]
            public virtual RepoItemInfo DetailBtnInfo
            {
                get
                {
                    return _detailbtnInfo;
                }
            }

            /// <summary>
            /// The VendorAgedDetailBtn item.
            /// </summary>
            [RepositoryItem("49c3da82-f17a-401a-8326-9b13ccf2718d")]
            public virtual Ranorex.RadioButton VendorAgedDetailBtn
            {
                get
                {
                    return _vendorageddetailbtnInfo.CreateAdapter<Ranorex.RadioButton>(true);
                }
            }

            /// <summary>
            /// The VendorAgedDetailBtn item info.
            /// </summary>
            [RepositoryItemInfo("49c3da82-f17a-401a-8326-9b13ccf2718d")]
            public virtual RepoItemInfo VendorAgedDetailBtnInfo
            {
                get
                {
                    return _vendorageddetailbtnInfo;
                }
            }

            /// <summary>
            /// The EmployeeDetailBtn item.
            /// </summary>
            [RepositoryItem("595418ed-e03a-4366-8494-213c13c4ce3b")]
            public virtual Ranorex.RadioButton EmployeeDetailBtn
            {
                get
                {
                    return _employeedetailbtnInfo.CreateAdapter<Ranorex.RadioButton>(true);
                }
            }

            /// <summary>
            /// The EmployeeDetailBtn item info.
            /// </summary>
            [RepositoryItemInfo("595418ed-e03a-4366-8494-213c13c4ce3b")]
            public virtual RepoItemInfo EmployeeDetailBtnInfo
            {
                get
                {
                    return _employeedetailbtnInfo;
                }
            }
        }

        /// <summary>
        /// The ReportDisplayAppFolder folder.
        /// </summary>
        [RepositoryFolder("eab6977d-29eb-4eda-80c9-244864ee3625")]
        public partial class ReportDisplayAppFolder : RepoGenBaseFolder
        {

            /// <summary>
            /// Creates a new ReportDisplay  folder.
            /// </summary>
            public ReportDisplayAppFolder(RepoGenBaseFolder parentFolder) :
                    base("ReportDisplay", "/form[@controlname='ReportForm']", parentFolder, 3000, null, true, "eab6977d-29eb-4eda-80c9-244864ee3625", "")
            {
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("eab6977d-29eb-4eda-80c9-244864ee3625")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("eab6977d-29eb-4eda-80c9-244864ee3625")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }
        }

    }
#pragma warning restore 0436
}